project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  reader-mode: true 
  repo-url: "https://github.com/math-finance-book/book-code.git"
  repo-actions: [source]
  chapters:
    - index.qmd
    - part: "Part I: Foundations"
      chapters:
        - Chapter_Arbitrage.qmd
        - Chapter_Intro.qmd
        - Chapter_OptionPricing.qmd
        - Chapter_Ito.qmd
        - Chapter_ItosFormula.qmd
    - part: "Part II: Black-Scholes and Extensions"
      chapters:
        - Chapter_BlackScholes.qmd
        - Chapter_FX.qmd
        - Chapter_Merton.qmd
        - Chapter_Exotics.qmd
    - part: "Part III: Stochastic Volatility"
      chapters:
        - Chapter_Vol.qmd
    - part: "Part IV: Numerical Methods"
      chapters:
        - Chapter_MC_Binomial.qmd
        - Chapter_FiniteDifferences.qmd
        - Chapter_Fourier.qmd
    - part: "Part V: Fixed Income"
      chapters:
        - Chapter_FixedIncome.qmd
        - Chapter_FixedIncomeDerivatives.qmd
        - Chapter_Vasicek.qmd
        - Chapter_Survey.qmd
    - part: "Appendix"
      chapters:
        - AppendixA.qmd
    
format:
  html:
    html-math-method: 
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    callout-icon: false


#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
