project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  sidebar:
    docked: true
    position: left
    toc: true
    sticky: true
    collapsed: true
    scroll: true
    border: true
    title: Table of Contents
    search: true
    search-placeholder: Search
    search-collapse: true
    search-results: true
    
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - Chapter4.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter8.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - ChapterFT.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    - Chapter14.qmd
  appendices:
    - AppendixA.qmd
    
format:
  html:
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    callout-icon: false
    mathjax: true
    mathjax-font-size: 10% !important
#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
