project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: Pricing and Hedging Derivative Securities
  author: 
    - Kerry Back
    - Mark Loewenstein
    
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - Chapter4.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter8.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    - Chapter14.qmd
  appendices:
    - AppendixB.qmd
    
format:
  html:
    number-sections: true
    theme: cosmo
    code-fold: true
    callout-icon: false
  pdf: default
  



