project:
  type: book
  output-dir: docs

book:
  title: "A Course in Derivative Securities"
  author: "Kerry Back"
  date: "9/14/2022"
  chapters:
    - index.qmd
    - Chapter1.qmc
    
format:
  html:
    theme: cosmo
    code-fold: true
  



