project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Steven L. Heston
    - Hong Liu
    - Mark Loewenstein
    
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - Chapter4.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter8.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    - Chapter14.qmd
  appendices:
    - AppendixA.qmd
    
format:
  html:
    number-sections: true
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    callout-icon: false
    mathjax: true
#pdf: default


execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
