project:
  type: book
  output-dir: docs

custom-callout:
  calculator:
    title: "Calculation Rule"
    icon: true
    icon-symbol: "fa-thumbs-up"
    color: "#008000"

filters:
  - custom-numbered-blocks

custom-numbered-blocks:
  groups:
    thmlike:
      colors: [ebda6c, 544a05]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    todos: default  
  classes:
    Theorem:
      group: thmlike
    Corollary:
      group: thmlike
    Exercise:
      group: thmlike
      collapse: true  
    Definition:
      group: thmlike
      colors: [d999d3, a01793]
    Feature: default
    TODO:
      label: "To do"
      colors: [e7b1b4, 8c3236]
      group: todos
      listin: [stilltodo]
    DONE:
      label: "Done"
      colors: [cce7b1, 86b754]  
      group: todos

#filters:
#  - black-formatter
 
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  reader-mode: true 
  repo-url: "https://github.com/math-finance-book/book-code.git"
  repo-actions: [source]
  chapters:
    - index.qmd
    - part: "Part I: Foundations"
      chapters:
        - Chapter_Intro.qmd
        - Chapter_Futures.qmd
        - Chapter_Arbitrage.qmd
        - Chapter_OptionPricing.qmd
    
    - part: "Part II: Mathematical Tools"
      chapters:
        - Chapter_Brownian.qmd 
        - Chapter_Ito.qmd
        - Chapter_Girsanov.qmd
        - Chapter_PDEs.qmd
    - part: "Part III: Black-Scholes and Extensions"
      chapters:
        - Chapter_BlackScholes.qmd
        - Chapter_FX.qmd
        - Chapter_Merton.qmd
        - Chapter_Exotics.qmd
    - part: "Part IV: Alternative Models"
      chapters:
        - Chapter_Vol.qmd
    - part: "Part V: Numerical Methods"
      chapters:
        - Chapter_MonteCarlo.qmd
        - Chapter_Binomial.qmd
        - Chapter_FiniteDifferences.qmd
        - Chapter_Fourier.qmd
    - part: "Part VI: Fixed Income"
      chapters:
        - Chapter_FixedIncome.qmd
        - Chapter_FixedIncomeDerivatives.qmd
        - Chapter_Vasicek.qmd
        - Chapter_Survey.qmd
    - part: "Appendix"
      chapters:
        - AppendixA.qmd
    
format:
  html:
    fig-height: 3
    html-math-method: 
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
 



#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
