project:
  type: book
  output-dir: docs

filters:
  - custom-numbered-blocks
#544a05
custom-numbered-blocks:
  classes:
    InProgress:
      label: "In Progress"
      colors: [eaacf2, 75387d]
      boxstyle: foldbox.simple
      collapse: true
    ToDo:
      label: "To Do"
      colors: [a7f2d8, 50997f]
      boxstyle: foldbox.simple
      collapse: true
    Done:
      label: "Done"
      colors: [e8cc97, 7d6538]
      boxstyle: foldbox.simple
      collapse: true
    Exercise:
      colors: [ede29d, 8c813a]
      boxstyle: foldbox.simple
      collapse: true
    Rule:
      label: "Calculation Rule"
      colors: [a1bced, 38568f]
      boxstyle: foldbox.simple
      collapse: false
    Principle:
      label: "Important Principle"
      colors: [e3aab2, 8f575f]
      boxstyle: foldbox.simple
      collapse: false
    Extra:
      label: "Theory Extra"
      colors: [d5deed, 6d778a]
      boxstyle: foldbox.simple
      collapse: true

#filters:
#  - black-formatter
 
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  reader-mode: true 
  repo-url: "https://github.com/math-finance-book/book-code.git"
  repo-actions: [source]
  chapters:
    - index.qmd
    - part: "Part I: Foundations"
      chapters:
        - Chapter_Intro.qmd
        - Chapter_Futures.qmd
        - Chapter_Arbitrage.qmd
        - Chapter_OptionPricing.qmd
    
    - part: "Part II: Mathematical Tools"
      chapters:
        - Chapter_Brownian.qmd 
        - Chapter_Ito.qmd
        - Chapter_GBM.qmd
        - Chapter_Girsanov.qmd
        - Chapter_Martingales.qmd
    - part: "Part III: Black-Scholes and Extensions"
      chapters:
        - Chapter_BlackScholes.qmd
        - Chapter_Americans.qmd
        - Chapter_Greeks.qmd
        - Chapter_FX.qmd
        - Chapter_Merton.qmd
        - Chapter_Asians.qmd
        - Chapter_Exotics.qmd
    - part: "Part IV: Alternative Models"
      chapters:
        - Chapter_GARCH.qmd
        - Chapter_StochasticVol.qmd
        - Chapter_Jumps.qmd
        - Chapter_VarianceSwaps.qmd
    - part: "Part V: Numerical Methods"
      chapters:
        - Chapter_MonteCarlo.qmd
        - Chapter_Binomial.qmd
        - Chapter_PDEs.qmd
        - Chapter_Fourier.qmd
        - Chapter_MachineLearning.qmd
    - part: "Part VI: Fixed Income"
      chapters:
        - Chapter_FixedIncome.qmd
        - Chapter_FixedIncomeDerivatives.qmd
        - Chapter_Vasicek.qmd
        - Chapter_Survey.qmd
    - part: "Appendix"
      chapters:
        - AppendixA.qmd
    
format:
  html:
    fig-height: 3
    html-math-method: 
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    execute:
      freeze: auto
    

 


#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
