project:
  type: book
  output-dir: docs

book:
  title: Mathematical Finance Book
  author: Kerry Back and Mark Loewenstein
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - Chapter4.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter8.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    - Chapter14.qmd
    
format:
  html:
    theme: cosmo
    code-fold: true
  



