project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  date: "2025"    
  chapters:
    - index.qmd
    - Chapter3.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter4.qmd
    - Chapter8.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - ChapterFT.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    - Chapter14.qmd
  appendices:
    - AppendixA.qmd
    
format:
  html:
    html-math-method: mathjax
    include-in-header: 
      text: |
        <script type="text/x-mathjax-config">
          MathJax.Hub.Config({
            "HTML-CSS": {
              scale: 400
            }
          });
        </script>
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: cosmo
      dark: cyborg
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    callout-icon: false


#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
