project:
  type: book
  output-dir: docs
  
number-depth: 2
callout-icon: false
bibliography: references.bib

book:
  title: "Pricing and Hedging Derivative Securities: Theory and Methods"
  author: 
    - Kerry Back
    - Hong Liu
    - Mark Loewenstein
  date: "2025"    
  chapters:
    - index.qmd
    - Chapter_Ito.qmd
    - Chapter_Intro.qmd
    - Chapter_Arbitrage.qmd
    - Chapter_BlackScholes.qmd
    - Chapter_FX.qmd
    - Chapter_Merton.qmd
    - Chapter_Exotics.qmd
    - Chapter_Vol.qmd
    - Chapter_MC_Binomial.qmd
    - Chapter_FiniteDifferences.qmd
    - Chapter_Fourier.qmd
    - Chapter_FixedIncome.qmd
    - Chapter_FixedIncomeDerivatives.qmd
    - Chapter_Vasicek.qmd
    - Chapter_Survey.qmd
  appendices:
    - AppendixA.qmd
    
format:
  html:
    html-math-method: mathjax
    include-in-header: 
      text: |
        <script type="text/x-mathjax-config">
          MathJax.Hub.Config({
            "HTML-CSS": {
              scale: 400
            }
          });
        </script>
    freeze: auto
    footnotes-hover: true
    number-sections: true
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    callout-icon: false


#pdf: default



execute:
  freeze: auto

fig-cap-location: top

comments:
  hypothesis: true
