project:
  type: book
  output-dir: docs
  

execute:
  freeze: auto

filters:
  - custom-callout
#  - black-formatter

custom-callout:

  Example:
    title: "Example"
    color: "#a1bced"
    icon: true
    icon-symbol: "fa-sun"
    appearance: "simple"
    collapse: true
    
  Rule:
    title: "Key Result"
    color: "#12801f"
    icon: true
    icon-symbol: "fa-thumbs-up"
    appearance: "simple"
    collapse: false
  
  Principle:
    title: "Important Principle"
    color: "#eb4034"
    icon: true
    icon-symbol: "fa-exclamation-circle"
    appearance: "simple"
    collapse: false
  
  Extra:
    title: "Theory Extra"
    color: "#a1bced"
    icon: true
    icon-symbol: "fa-truck-fast"
    appearance: "simple"
    collapse: true
  
 
number-depth: 2
callout-icon: true
bibliography: references.bib

book:
  sidebar:
    tools:
      - icon: chat-square-text
        href: https://chat.derivative-securities.org/
  title: Pricing and Hedging Derivative Securities
  author: 
    - Kerry Back, Rice University
    - Hong Liu, Washington University in St. Louis
    - Mark Loewenstein, University of Maryland
  reader-mode: true 
  repo-url: "https://github.com/math-finance-book/book-published-code.git"
  repo-actions: [source]
  chapters:
    - index.qmd

    - part: "Part 1: Introduction"
      chapters:
        - Chapter_IntroDerivatives.qmd
        - Chapter_IntroOptions.qmd
        - Chapter_IntroFutures.qmd
        - Chapter_Trees.qmd

    - part: "Part 2: Mathematical Foundations"
      chapters:
        - Chapter_BrownianMotion.qmd 
        - Chapter_Ito.qmd
        - Chapter_GeometricBrownianMotion.qmd

    - part: "Part 3: Option Pricing"
      chapters:
        - Chapter_ArbitragePricing.qmd
        - Chapter_BlackScholes_updated.qmd
        - Chapter_MertonMargrabeBlack.qmd
        - Chapter_Asians.qmd
        - Chapter_OtherExotics.qmd
    - part: "Part 4: Numerical Methods"
      chapters:
        - Chapter_MonteCarlo.qmd
        - Chapter_BinomialModel.qmd

    
format:
  html:
    fig-height: 3
    html-math-method: 
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    footnotes-hover: true
    number-sections: true
    theme: 
      light: flatly
      dark: superhero
    toc: false
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    include-in-header:
      text: |
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet"/>

    

 


#pdf: default







comments:
  hypothesis: true
