{{< include macros.qmd >}}

# More on Arbitrage Pricing {#sec-c:arbitrage} 

```{python}
#| eval: true
#| echo: false

import plotly
from IPython.display import display, HTML

plotly.offline.init_notebook_mode(connected=True)
display(
    HTML(
        '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
    )
)
```



## Martingale Pricing

A martingale is a stochastic process for which the expected value of tomorrow's value is today's value. In the context of our model, discounted values of non-dividend paying trading strategies are martingales. That is, if $X(0)$ is today's value of a portfolio with random payoff $X$ at time $t$,
$$  \frac{X(0)}{R(0)} = \sum_{s=1}^S p_s \frac{X_s}{e^{r t}} = \mathbb{E}^R\left[\frac{X}{R_t}\right] $$
where $R(0) = 1$, the initial investment in the risk-free asset. In this sense, the discounted value today is the expected discounted value in one period, where the expectation uses the risk-neutral probabilities.

#### Martingales

@eq-binomialC3 and @eq-binomialS3 can be written in an equivalent form, which, though somewhat less intuitive, generalizes more readily. First, let's introduce some notation for the price of the risk-free asset. Considering an investment of \$1 today that grows to $\mathrm{e}^{rt}$ at date $t$, it is sensible to take the price today to be $R=1$ and the price in the up and down states at date $t$ to be $R_u=R_d=\mathrm{e}^{rt}$.^[All of the equations appearing below are also true if instead we take $R=\mathrm{e}^{-rt}$ and $R_u=R_d=1$.] In terms of this notation, @eq-binomialC3--@eq-binomialR3 can be written as:

$$
\frac{C}{R} = p_u \frac{C_u}{R_u} + p_d \frac{C_d}{R_d}\;, 
$$ {#eq-binomialC4}

$$
\frac{S}{R} = p_u \frac{S_u}{R_u} + p_d \frac{S_d}{R_d}\;, 
$$ {#eq-binomialS4}

$$
1=p_u+p_d\;.
$$ {#eq-binomialR4}


@eq-binomialC4 and @eq-binomialS4 each state that the price of a security today divided by the price of the risk-free asset equals the expected future value of the same ratio, when we take expectations using the risk-neutral probabilities. In other words, the mean of the date--$t$ value of the ratio is equal to the ratio today.
A variable that changes randomly over time with the expected future value being always equal to the current value is called a martingale. Thus, we have shown that the ratio of the stock price to the price of the risk-free asset is a martingale when using the risk-neutral probabilities.

The ratio of one price to another is the value of the first (numerator) asset when we are using the second (denominator) asset as the numeraire. \index{numeraire} The term numeraire means a unit of measurement. For example, the ratio $C/R$ is the value of the call when we use the risk-free asset as the unit of measurement: it is the number of units of the risk-free asset for which one call option can be exchanged (to see this, note that $C/R$ units of the risk-free asset is worth $C/R \times R = C$ dollars, so $C/R$ units of the risk-free asset is worth the same as one call). Thus, we have shown that asset prices using the risk-free asset as numeraire are martingales relative to the risk-neutral probabilities.


## Change of Numeraire {#sec-s:change_numeraire}

Our choice of the risk-free asset to derive risk-neutral probabilities was somewhat arbitrary. In fact, any strictly positive non-dividend paying trading strategy can be used as a numeraire. In other words, instead of quoting the price of apples and oranges in dollars, we can quote prices in numbers of oranges. One apple is equal to the price of one apple in dollars divided by the price of oranges in dollars, and one dollar is equal to one divided by the price of oranges. In our model, instead of measuring payoffs in units of an investment in the risk-free asset, we can measure payoffs in different units. We explain this as follows.

The price of any non-dividend paying asset or dividend-reinvested trading strategy with strictly positive value is
$$Y(0) = \sum_{s=1}^S \pi_s Y_s $$
Rearranging, we can define probabilities $\text{prob}^Y_s = \frac{\pi_s Y_s}{Y(0)}$. Then we have $\sum_{s=1}^S \text{prob}^Y_s =1$ and we can write the price of the risk-free asset and any traded security as
$$1 = Y(0) \sum_{s=1}^S \text{prob}^Y_s \frac{e^{rt}}{Y_s} = Y(0) \mathbb{E}^Y\left[\frac{e^{rt}}{Y} \right]$$
$$S(0) = Y(0) \sum_{s=1}^S \text{prob}^Y_s \frac{S_s}{Y_s}  = Y(0) \mathbb{E}^Y\left[\frac{S}{Y}\right] $$
Notice $\frac{S}{Y}$ is a martingale using the probabilities $\text{prob}_s^Y$. The ratio $\frac{S}{Y}$ is the number of shares of $Y$ that security $S$ is worth. Therefore, using the probabilities $\text{prob}_s^Y$, the value of the number of shares of $Y$ an investment is worth follows a martingale.


::: Principle
If there are no arbitrage opportunities, then for each dividend-reinvested asset, there exists a probability measure such that the ratio of any other dividend-reinvested asset price to the first (numeraire) asset price is a martingale.
:::

An assignment of probabilities to events is called a probability measure, or simply a measure (because it measures the events, in a sense). Thus, we have described two different probability measures: one using the risk-free asset as numeraire and one using the stock as numeraire. The probability measure using the risk-free asset as numeraire defined in the previous section is universally called the risk-neutral probability. When we use one of these probabilities, we commonly say that we are changing numeraires.

We have applied this statement to the risk-free asset, which pays dividends (interest). However, the price $R_s=\mathrm{e}^{rt}$ for all $s=1,\dots,S$, includes the interest, so no interest has been withdrawn---the interest has been reinvested---prior to the maturity $t$ of the option. This is what we mean by a dividend-reinvested asset. In general, we apply the formulas developed in this and the following section to dividend-paying assets by considering the portfolios in which dividends are reinvested.



#### Other Numeraires in the Binomial Model

Note that the risk-neutral probabilities are the state prices multiplied by the gross return on the risk-free asset. Analogously, define numbers $\text{prob}^S_u = \pi_uS_u/S$ and $\text{prob}^S_d = \pi_dS_d/S$. Substituting for $\pi_u$ and $\pi_d$ in @eq-binomialC2--@eq-binomialR2 and continuing to use the notation $R$ for the price of the risk-free asset, we obtain

$$
\frac{C}{S} = \text{prob}^S_u \frac{C_u}{S_u} + \text{prob}^S_d \frac{C_d}{S_d}\;, 
$$ {#eq-binomialC5}

$$
1 = \text{prob}^S_u + \text{prob}^S_d\;,
$$ {#eq-binomialS5}

$$
\frac{R}{S} = \text{prob}^S_u \frac{R_u}{S_u} + \text{prob}^S_d \frac{R_d}{S_d}\;. 
$$ {#eq-binomialR5}


@eq-binomialS5 establishes that we can view the $\text{prob}^S$'s as probabilities (like the risk-neutral probabilities, they are positive because the state prices are positive). @eq-binomialC5 and @eq-binomialR5 both state that the ratio of a security price to the price of the stock is a martingale when we use the $\text{prob}^S$'s as probabilities. Thus, asset prices using the stock as numeraire are martingales when we use the $\text{prob}^S$ probabilities.



#### Practical Implementation

For this exposition, it was convenient to first calculate the state prices and then calculate the various probabilities. However, that is not the most efficient way to proceed in most applications. In a typical application, we would view the prices of the stock and risk-free asset in the various states of the world as given, and we would be attempting to compute the value of the call option. Note that @eq-binomialC2--@eq-binomialR2, @eq-binomialC4--@eq-binomialR4, and @eq-binomialC5--@eq-binomialR5 are all equivalent. In each case we would consider that there are three unknowns---the value $C$ of the call option and either two state prices or two probabilities. In each case the state prices or probabilities can be computed from the last two equations in the set of three equations and then the call value $C$ can be computed from the first equation in the set. All three sets of equations produce the same call value.

In fact, as we will see, it is not even necessary to calculate the probabilities. The fact that ratios of dividend-reinvested asset prices to the numeraire asset price are martingales tells us enough about the probabilities to calculate derivative values without having to calculate the probabilities themselves.

## Stochastic Discount Factor

Up until now, no mention of the true probabilities has been made. However, another pricing formula that is commonly encountered is to use a stochastic discount factor. Denote the actual probability of state $s$ as $\text{prob}_s$. If we define $m_s = \frac{\pi_s}{\text{prob}_s}$, we can write 
$$ P(X) = \sum_{s=1}^S \text{prob}_s m_s X_s = \mathbb{E}\left[m X\right] $$.

We call the random variable $m$ the stochastic discount factor. We can calculate an asset value as the expectation of its future value discounted (multiplied) by the stochastic factor $m$.

A further decomposition of $m$ is useful. Notice that
$$ 1 = \mathbb{E}\left[m e^{rt}\right] $$
so in a sense to be made precise later, $m e^{rt}$ is a martingale when we identify the time 0 value of $m$ as 1. Therefore, we can write the price of any asset with time $t$ value $X$ as
$$  P(X) = \mathbb{E}\left[m e^{rt} \frac{X}{e^{rt}}\right] = \sum_{s=1}^S \text{prob}_s m_s e^{rt} \frac{X_s}{e^{rt}} =\mathbb{E}^R\left[\frac{X}{e^{rt}}\right]$$
Therefore, the risk-neutral probabilities are
$$p_s = \text{prob}_s m_s e^{rt} $$
and the random variable $m e^{rt}$ changes the probability measure from the true probability measure to the risk-neutral measure: for any random variable $Z$, $\mathbb{E}[m e^{rt} Z] = \mathbb{E}^R[Z]$.

#### Stochastic Discount Factor in the Binomial Model

We now consider yet another reformulation of the pricing relations @eq-binomialC2--@eq-binomialR2. This formulation generalizes more easily to pricing when there are a continuum of states.
Let $\text{prob}_u$ denote the actual probability of the up state and $\text{prob}_d$ denote the probability of the down state. These probabilities are irrelevant for pricing derivatives in the two-state up-and-down model, but we use them to write the pricing relations @eq-binomialC2--@eq-binomialR2 as expectations with respect to the actual probabilities. To do this, we can define
\begin{align*}
m_u &= \frac{\pi_u}{\text{prob}_u}\; ,\\
m_d &= \frac{\pi_d}{\text{prob}_d}\;.
\end{align*}
Then @eq-binomialC2--@eq-binomialR2 can be written as

$$
C = \text{prob}_um_uC_u + \text{prob}_dm_dC_d\;,
$$ {#eq-binomialC6}

$$
S = \text{prob}_um_uS_u + \text{prob}_dm_dS_d\;,
$$ {#eq-binomialS6}

$$
R = \text{prob}_um_uR_u + \text{prob}_dm_dR_d\;.
$$ {#eq-binomialR6}


The right-hand sides are expectations with respect to the actual probabilities. For example, the right-hand side of @eq-binomialC6 is the expectation of the random variable that equals $m_uC_u$ in the up state and $m_dC_d$ in the down state. The risk-neutral probabilities can be calculated from $m_u$ and $m_d$ as
$p_u=\text{prob}_um_uR_u/R$ and $p_d=\text{prob}_dm_dR_d/R$. Likewise, the probabilities using the stock as the numeraire can be calculated from $m_u$ and $m_d$ as
$\text{prob}^S_u=\text{prob}_um_uS_u/S$ and $\text{prob}^S_d=\text{prob}_dm_dS_d/S$.

The random variable $m$ is the stochastic discount factor. @eq-binomialS6--@eq-binomialR6 show that we can calculate an asset value as the expectation of its future value discounted (multiplied) by the stochastic factor $m$.

## More General Models

Now, we drop the assumption that there are a finite number of possible future prices of the stock and allow a general distribution with potentially a continuum of possible values. Denote the future price as $S_t$. Our principle regarding the stochastic discount factor developed in the preceding section can in general be expressed as:^[We have proven this in the two-state model, but we will not prove it in general. As is standard in the literature, we simply adopt it as an assumption. A general proof is in fact difficult and requires a definition of no arbitrage that is considerably more complicated than the simple assumption @eq-binomialnoarbitrage that is sufficient in the two-state up-and-down model.] 

::: Principle
If there are no arbitrage opportunities, then there exists for each date $t$ a strictly positive random variable $m_t$, called a stochastic discount factor, such that the date--$0$ value of any dividend-reinvested asset with price $P$ is 
$$
P_0 = \mathbb{E}[m_tP_t]\;.
$$ {#eq-continuum1}
:::

Here, $\mathbb{E}[m_tS_t]$ denotes the expectation of the random variable $m_tS_t$. In a two-state model (or in any model with only a finite number of states of the world), the concept of an expectation is clear: it is just a weighted average of outcomes, the weights being the probabilities. In the two-state model, the right-hand side of @eq-binomialS6 is the same as the right-hand side of @eq-continuum1.^[
In general the expectation (or mean) of a random variable is an intuitive concept, and an intuitive understanding is sufficient for this book, so we will not give a formal definition. It should be understood that we are assuming implicitly, whenever necessary, that the expectation exists (which is not always the case). In this regard, it is useful to note in passing that a product of two random variables $XY$ has a finite mean whenever $X$ and $Y$ have finite variances.]


To convert from state prices to probabilities corresponding to different numeraires, we follow the same procedure as at the end of the previous section: we multiply together (i) the probability of the state, (ii) the value of $m_t$ in the state, and (iii) the gross return of the numeraire in the state. If there is a continuum of states, then the actual probability of any individual state is typically zero, so this multiplication produces a zero probability. However, we can nevertheless add up these probabilities to define the probability of any event $A$, an event being a set of states of the world. To do this, let $1_A$ denote the random variable that takes the value 1 when $A$ is true and which is zero otherwise. Then the probability of $A$ using $S$ as the numeraire is defined as \index{change of measure} \index{change of numeraire}
$$
\mathbb{E}\left[1_Am_t\frac{S_t}{S_0}\right]\;.
$$ {#eq-probSnumeraire}

This makes sense as a probability because it is nonnegative and because, if $A$ is the set of all states of the world, then its probability is $\mathbb{E}[m_tS_t/S_0]$, which equals one by virtue of @eq-continuum1. From @eq-probSnumeraire for the probability of any event $A$, it can be shown that the expectation of any random variable $X$ using $S$ as the numeraire is
$$
\mathbb{E}\left[Xm_t\frac{S_t}{S_0}\right]\;.
$$ {#eq-expSnumeraire}


Different numeraires lead to different probability measures and hence to different expectations. To keep this straight, we use the numeraire as a superscript on the expectation symbol: for example, $\mathbb{E}^S$ denotes expectation with respect to the probability measure that corresponds to $S$ being the numeraire. Also, we use the symbol $\text{prob}^S(A)$ to denote the probability of an event $A$ when we use $S$ as the numeraire. So, @eq-probSnumeraire and @eq-expSnumeraire are written as 

$$
\text{prob}^S(A) = \mathbb{E}\left[1_Am_t\frac{S_t}{S_0}\right]\;,
$$ {#eq-probSnumeraire2}

$$
\mathbb{E}^S[X] = \mathbb{E}\left[Xm_t\frac{S_t}{S_0}\right]\;.
$$ {#eq-expSnumeraire2}


#### Fundamental Pricing Formula

Our key result in the two-state up-and-down example considered earlier was that the ratio of the price of any dividend-reinvested asset to the price of the numeraire asset is not expected to change when we use the probability measure corresponding to the numeraire. We now demonstrate the same result in this more general model. Recall that $t$ denotes an arbitrary but fixed date at which we have defined the probabilities using $S$ as the numeraire in @eq-probSnumeraire. At each date $s<t$, let $\mathbb{E}^P_s$ denote the expectation given information at time $s$ and using a dividend-reinvested asset price $P$ as the numeraire (we continue to write the expectation at date $0$ without a subscript; i.e., $\mathbb{E}^S$ has the same meaning as $\mathbb{E}^S_0$). Let $Y$ denote the price of another dividend-reinvested asset. We will show that
$$
\frac{Y_s}{P_s} = \mathbb{E}^P_s \left[\frac{Y_t}{P_t}\right]\;.
$$ {#eq-preformula}

Thus, the expected future (date--$t$) value of the ratio $Y/P$ always equals the current (date--$s$) value when we change probability measures using $P$ as the numeraire. As discussed in the preceding section, the mathematical term for a random variable whose expected future value always equals its current value is martingale. Thus, we can express @eq-preformula as stating that the ratio $Y/P$ is a martingale when we compute expectations using the probability measure that corresponds to $P$ being the numeraire.

The usefulness of @eq-preformula is that it gives us a formula for the asset price $Y_s$ at any time $s$---and recall that this formula holds for every dividend-reinvested asset. The formula is obtained from @eq-preformula by multiplying through by $P_s$:

::: Principle
In the absence of arbitrage opportunities, prices $P$ and $Y$ of dividend-reinvested assets satisfy, for all $s<t$,
$$
Y_s = P_s\mathbb{E}^P_s \left[\frac{Y_t}{P_t}\right]\;.
$$ {#eq-formula}
:::

We call @eq-formula the fundamental pricing formula. \index{fundamental pricing formula}
It is at the heart of modern pricing of derivative securities. It is a present value relation: the value at time $s$ of the asset with price $Y$ is the expectation, under the appropriate probability measure, of its value $Y_t$ at time $t$ discounted by the (possibly random) factor $P_s/P_t$.

For example, assume the risk-free rate is constant. Letting $P_s = R_s$ denote the value $\mathrm{e}^{rs}$ of the risk-free asset and using it as the numeraire, @eq-formula becomes
$$
Y_s = \mathrm{e}^{rs}\mathbb{E}^R_s\left[\frac{Y_t}{\mathrm{e}^{rt}}\right] = \mathrm{e}^{-r(t-s)}\mathbb{E}^R_s [Y_t]\;,
$$ {#eq-riskneutralformula}

which means that the value $Y_s$ is the expected value of $Y_t$ discounted at the risk-free rate for the remaining time $t-s$, when the expectation is computed under the risk-neutral probability.

Notice that this implies $m_t e^{rt}$ is a martingale. This tells us how to change probabilities as follows: for any time $t$ random variable^[In other words, a random variable whose value is known at time $t$], $Z$,
$$E[m_t e^{rt} Z] = E^R[Z] $$
Similar remarks also apply to any dividend-reinvested trading strategy, $X$: $m_t X_t$ is a martingale. Then
$$E[m_t X_t Z] = X(0) E^X[Z]$$.

We end this section with a proof of @eq-preformula.^[The proof is due to Harrison and Kreps [@HK]. See also Geman, El Karoui and Rochet [@GKR]. We omit here technical assumptions regarding the existence of expectations.]




::: Extra

Consider any time $s<t$ and any event $A$ that is distinguishable by time $s$. Consider the trading strategy of buying one share of the asset with price $Y$ at time $s$ when $A$ has happened and financing this purchase by short selling $Y_s/P_s$ shares of the asset with price $P$. Each share of this asset that you short brings in $P_s$ dollars, so shorting $Y_s/P_s$ shares brings in $Y_s$ dollars, exactly enough to purchase the desired share of the first asset. Hold this portfolio until time $t$ and then liquidate it. Liquidating it generates 
$$1_A\left(Y_t-\frac{Y_s}{P_s}P_t\right)$$
dollars. The multiplication by the random variable $1_A$ is because we only implement this strategy when $A$ occurs (i.e., when $1_A=1$). Consider the security that pays this number of dollars at time $t$. Because we obtained it with a trading strategy that required no investment at any time, its price at time $0$ must be $0$. We already observed that we can represent the price in terms of state prices, so we conclude that
$$\mathbb{E} \left[m_t1_A\left(Y_t-\frac{Y_s}{P_s}P_t\right)\right] = 0\;\;.$$
When we divide by $P_0$, this still equals zero. Factoring $P_t$ outside the parentheses gives
$$\mathbb{E} \left[1_A\frac{P_t}{P_0}m_t\left(\frac{Y_t}{P_t}-\frac{Y_s}{P_s}\right)\right] = 0\;\;.$$
We see from @eq-expSnumeraire2 for expectations using $P$ as the numeraire that we can write this as
$$\mathbb{E}^P\left[1_A\left(\frac{Y_t}{P_t}-\frac{Y_s}{P_s}\right)\right]=0\;.$$
This is true for any event $A$ distinguishable at time $s$, so the expectation of $Y_t/P_t-Y_s/P_s$ must be zero given any information at time $s$ when we use $P$ as the numeraire; i.e.,
$$\mathbb{E}^P_s\left[\frac{Y_t}{P_t}-\frac{Y_s}{P_s}\right]=0\; ,$$
or, equivalently
$$\mathbb{E}^P_s\left[\frac{Y_t}{P_t}\right] = \frac{Y_s}{P_s}\;.$$
:::


## Multiple Cash Flows

Our valuation formulae work for dividend-paying assets or trading strategies that make periodic payments. We simply sum up the value of the individual cash flows. If a stock pays dividends $D_t$ up to and including time $T$ and the stock price at time $T$ is $S(T)$, then the stock price is given by
$$S(0)= \mathbb{E}\left[\sum_{t=1}^T m_t D_t + m_T S(T)\right] $$



## Further Discussion

How do the probabilities of different events change when we change probability measures? Which events become more likely and which become less likely? These are natural questions to ask. Let's consider the risk-neutral probability assuming the risk-free rate is constant. @eq-riskneutralformula can be rearranged as
$$\frac{\mathbb{E}^{R}_s[Y_t]}{Y_s} = \mathrm{e}^{r(t-s)}\,.$$
This means that the expected return on the dividend-reinvested asset with price $Y$ is the risk-free rate. Stocks generally have positive risk premia, meaning they are expected to return more than the risk-free rate. Hence, when we shift from the actual probabilities to the risk-neutral probability, we are decreasing expected returns. How does this happen? It is because we increase the probabilities of bad events (low stock returns) and decrease the probabilities of good events (high stock returns).

In Example \ref{example:binomial}, it is easy to calculate that the risk-neutral probabilities are $p_u=0.75$ and $p_d=0.25$. To value the call option, we did not need to specify the actual probabilities, but if the expected return of the stock is higher than the risk-free return -- that is, if the stock has a positive risk premium -- then it must be the case that $\text{prob}_u > 0.75$. For example, if the expected return is 8\%, then $\text{prob}_u=0.9$. Thus, if the stock has a positive risk premium, then the risk-neutral probability of the stock falling is higher than the actual probability.

The usual way to value risky assets is to discount expected future values at a risk-adjusted rate that is higher than the risk-free rate. What we have shown is that we can instead value risky assets by adjusting the probabilities and discounting at the risk-free rate. Instead of increasing the discount rate relative to the risk-free rate, we increase the probabilities of bad events. These are alternative ways of valuing risky assets.

## Exercises

::: {#exr-binomialcall}
 
 
Create a Python function in which the user inputs $S$, $S_d$, $S_u$, $K$, $r$ and $t$. Check that the no-arbitrage condition @eq-binomialnoarbitrage is satisfied. Compute the value of a call option in each of the following ways:

1. Compute the delta and use @eq-C0.
2. Compute the state prices and use @eq-binomialC2.
3. Compute the risk-neutral probabilities and use @eq-binomialC3.
4. Compute the probabilities using the stock as numeraire and use @eq-binomialC5.

Verify that all of these methods produce the same answer.
:::

::: {#exr-arbitrage2}
 
In a two-state model, a put option is equivalent to $\delta_p$ shares of the stock, where $\delta_p = (P_u-P_d)/(S_u-S_d)$ (this will be negative, meaning a short position) and some money invested in the risk-free asset. Derive the amount of money $x$ that should be invested in the risk-free asset to replicate the put option. The value of the put at date $0$ must be $x+\delta_pS$.
:::

::: {#exr-arbitrage3}

Using the result of the previous exercise, repeat @exr-binomialcall for a put option.
:::