{{< include macros.qmd >}}

# Digitals and Measures {#sec-c:digitals_measures} 

```{python}
#| eval: true
#| echo: false

import plotly
from IPython.display import display, HTML

plotly.offline.init_notebook_mode(connected=True)
display(
    HTML(
        '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
    )
)
```

This chapter studies the building blocks of calls and puts -- digitals and share digitals -- and values them using Ito's formula and measure changes.  Let $S$ denote a dividend-reinvested asset price.  We call the date at which we are valuing securities date $0$.

## Digitals {#sec-s:digitals}

A digital (or binary)  option pays a fixed amount in a certain event and zero otherwise.  Consider a digital that pays \$1 at some date $T$ if $S_T>K$, where $K$ is a number that is fixed by the contract.  This means that the digital pays $x$ dollars at date $T$ where $x$ is defined as
$$
x =  \begin{cases} 1 & \text{if $S_T>K$}\; ,\\
0 & \text{otherwise}\;.
\end{cases}
$$ {#eq-digital1}

What is the digital worth at date $0$?
 Using @eq-riskneutralformula, the value of the digital at date $0$ is $\mathrm{e}^{-rT}\\E^R[x]$.  Note that
\begin{align*}
\E^R[x] \;&=\; 1 \times \text{prob}^R(x=1)\; + \;0 \times \text{prob}^R(x\!\!=\!\!0) \\
\;&=\; \text{prob}^R(x=1)\\
\;&=\; \text{prob}^R\big(S_T > K\big)\;.
\end{align*}
So, the value of the digital is the 
 risk-neutral probability of the digital finishing in the money discounted at the risk-free rate.


Consider now a different digital that pays when the underlying asset price is less than $K$ at date $T$.  So, it pays $y$ dollars at date $T$ where
\begin{equation*}
y =  \begin{cases} 1 & \text{if $S_T<K$}\; ,\\
0 & \text{otherwise}\;.
\end{cases}
\end{equation*}
Using @eq-riskneutralformula again, the value of this digital at date $0$ is 
$$\mathrm{e}^{-rT}\\E^R[y] = \mathrm{e}^{-rT}\text{prob}^R(y=1) = \mathrm{e}^{-rT}\text{prob}^R\big(S_T<K\big)\; .$$
Again, this is the risk-neutral probability of the digital finishing in the money discounted at the risk-free rate. 

## Share Digitals

Now consider a contract that pays a share of the underlying asset at date $T$ when $S_T \geq K$.  The value of this contract at date $T$ is $xS_T$ where $x$ is defined in @eq-digital1. Our fundamental pricing formula (@eq-formula) tells us that the value of the share digital at date $0$ is 
$$Z_0 E^Z \left[\frac{xS_T}{Z_T}\right]\; ,$$
for any non-dividend-paying asset price $Z$.   We want to choose the numeraire to simplify the calculation of the expectation.  We get the most simplification by setting $Z=S$.  The value of the share digital at date $0$ is 
$$S_0 E^S \left[x\right] = S_0\text{prob}^S(x=1) = S_0\text{prob}^S\big(S_T>K\big)\,.$$
Thus, to value the share digital, we need to calculate the probability of it finishing in the money when we use $S$ as the numeraire.

We can also consider a digital that pays 1 share of the underlying asset when $S_T<K$.  By the same reasoning, the value of this share digital at date $0$ is
$$S_0\text{prob}^S\big(S_T<K\big)\,.$$
To finish the valuation of either a digital or a share digital, we need to know the distribution of $S_T$ under different probability measures.

## Changing Measures Changes Drifts

When we change probability measures, we cannot expect a process $B$ that was a Brownian motion to remain a Brownian motion.    The expected change in a Brownian motion must always be zero, but when we change probabilities, the expected change of $B$ is likely to become nonzero.  However, the Brownian motion $B$ will still be an Ito process under the new probability measure.  In fact, every Ito process under one probability measure is an Ito process under the new probability measure, and the diffusion coefficient of the Ito process is unaffected by the change in probabilities.^[To be a little more precise, this is true provided sets of states of the world having zero probability continue to have zero probability when the probabilities are changed.  Because of the way we change probability measures when we change numeraires (cf.  @eq-probSnumeraire) this will always be true for us.]  Changing probabilities only changes the drift of an Ito process.  

This should not be surprising.  @sec-s:quadraticvariation explains that a Brownian motion $B$ can be defined as a continuous martingale with paths that jiggle in such a way that the quadratic variation over any interval $[0,T]$ is equal to $T$.  Changing the probabilities will change the probabilities of the various paths (so it may affect the expected change in $B$) but it will not affect how each path jiggles. So, under the new probability measure, $B$ should still be like a Brownian motion but it may have a nonzero drift.  If we consider a general Ito process, the reasoning is the same.  The diffusion coefficient $\sigma$ determines how much each path jiggles, and this is unaffected by changing the probability measure.  Furthermore, instantaneous covariances---the $(\d  X)(\d  Y)$ terms---between Ito processes are unaffected by changing the probability measure.  Only drifts are affected.  We now calculate the changes in  drifts when we switch to the risk-neutral probability or use $S$ as the numeraire.

## Risk-Neutral Probability

Assume 
$$\frac{\d S}{S} = \mu\d t + \sigma \d B$$ {#eq-dSS}
where $B$ is a Brownian motion and $\mu$ and $\sigma$ can be quite general stochastic processes.  Also, the instantaneous risk-free rate $r$ can be a quite general stochastic process, and we set 
$$R_t = \e^{\int_0^t r_s\d s}$$
as before.

The Key Principle \ref{principle-fundamental} tells us that, in the absence of arbitrage opportunities, there is a probability measure (called the risk-neutral probability) with respect to which $S/R$ is a martingale.  

Setting $Y=S/R$, we have, from Calculation Rule \ref{rule:compounding} that
$$\frac{\d Y}{Y} = \frac{\d S}{S} - r\d t\,.$$
Because $Y$ is a martingale under the risk-neutral probability, it cannot have a drift under that probability measure, so the drift of $S$ must be the risk-free rate under that probability measure.  So, we have shown the following.

::: Principle
The expected rate of return of any asset under the risk-neutral probability must be the risk-free rate.
:::

Because the change of measure does not affect the volatility, we also have:

::: {.Rule #rule:riskneutral}
If $S$ is a dividend-reinvested asset price satisfying @eq-dSS, then
$$
\frac{\d  S}{S} =r\d   t+\sigma\d   B^*\;,
$$ {#eq-riskneutral11}
where $B^*$ is a Brownian motion under the risk-neutral probability. 
:::
 

## Underlying as the Numeraire

When we change measures using $S$ is the numeraire, the process
$Z_t$ defined as 
$$Z_t = \frac{R_t}{S_t} = \frac{\exp\left(\int_0^t r_s\d   s\right)}{S_t}$$
is a martingale.  Using the rule for ratios, we have
$$\frac{\d  Z}{Z} =r\d   t - \frac{\d  S}{S} + \left(\frac{\d  S}{S}\right)^2 = (r + \sigma^2)\d   t - \frac{\d  S}{S}\; .$$
Because the drift of $\d  Z/Z$ must be zero, this implies that the drift of $\d  S/
S$ is $(r + \sigma^2_s)\d   t$.  We conclude that:

::: {.Rule #rule:underlying_numeraire}
## 
If $S$ is a dividend-reinvested asset price satisfying @eq-dSS, then
$$
\frac{\d  S}{S} = (r+ \sigma^2_s)\d   t+\sigma\d   B^*\;,
$$ {#eq-own11}
where $B^*$ is a Brownian motion when $S$ is the numeraire.
:::

## Constant Parameters and the Values of Digitals

Now assume that $r$ and $\sigma$  are constants.  We continue to allow $\mu$ to be a quite general stochastic process.
We want to calculate the risk-neutral probabilities of $S_T>K$ and $S_T<K$.  With the assumption that $r$ and $\sigma$ are constants, Calculation Rule \ref{rule:riskneutral} implies that $S$ is a geometric Brownian motion under the risk-neutral probability.  

Now using the formulas @eq-tailprob01--@eq-tailprob3, with $\alpha = r-\sigma^2/2$, we have $\text{prob}^R\big(S_T > K\big) = \mathrm{N}(d_2)$ where 
$$
d_2 = \frac{\log S_0 - \log K +\left(r-\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\;.
$$ {#eq-digital_d2}

The notation $d_2$ is standard notation from the Black-Scholes formula (@sec-c_blackscholes), and we use it---rather than a simple $d$---to distinguish the number @eq-digital_d2 from a similar number---to be called $d_1$ of course---that we will see in the next section.  
We conclude:

::: Rule
## 
If the interest rate and volatility are constant, then the value of a digital option that pays \$1 when $S_T>K$ is $\mathrm{e}^{-rT}\mathrm{N}(d_2)$, where $d_2$ is defined in @eq-digital_d2. The value of a digital option that pays \$1 when $S_T<K$ is  $\mathrm{e}^{-rT}\mathrm{N}(-d_2)$.
:::



## Constant Parameters and the Values of Share Digitals

Continue to assume that $r$ and $\sigma$ are constants.  Under these assumptions, Calculation Rule \ref{rule:underlying_numeraire} implies that $S$ is a geometric Brownian motion with drift $r+\sigma^2$ when $S$ is used as the numeraire.  Using the formulas @eq-tailprob01--@eq-tailprob3, with $\alpha = r + \sigma^2/2$, we obtain $\text{prob}^S\big(S_T > K\big) = \mathrm{N}(d_1)$ where 
$$
d_1 = \frac{\log S_0 - \log K+\left(r+\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}= d_2 + \sigma\sqrt{T}\;.
$$ {#eq-digital_d1}

::: Rule
## 
If the interest rate and volatility are constant, then the value of a security that pays $S_T$ when $S_T>K$ and zero otherwise is $S_0\mathrm{N}(d_1)$, where $d_1$ is defined in @eq-digital_d1, and the value of a security that pays $S_T$ when $S_T < K$ and zero otherwise is $S_0\mathrm{N}(-d_1)$.

:::

## Another Risky Asset as the Numeraire
We have now studied the dynamics of the dividend-reinvested asset price $S$ when the risk-free asset and $S$ are used as the numeraires.  In subsequent chapters, we will need to know the dynamics of $S$ when another risky asset is used as the numeraire. 

Suppose $Y$ is another dividend-reinvested asset price and
$$\frac{\d Y}{Y} = \theta\d t + \phi \d W$$ {#eq-dYY}

where $W$ is a standard Brownian motion.  Let $\rho$ denote the correlation process of $B$ and $W$.  We allow $r$, $\mu$, $\sigma$, $\theta$, $\phi$, and $\rho$ to be quite general stochastic processes.  Using $Y$ as the numeraire, $Z_1$ defined as $R/Y$ and $Z_2$ defined as $S/Y$ are martingales.  Applying the rule for ratios, we have
$$\frac{\d Z_1}{Z_1} = r\d t - \frac{\d Y}{Y} +  \left(\frac{\d Y}{Y}\right)^2\,.$$
Setting the drift to be zero tells us that the drift of $\d Y/Y$ is $r + \phi^2$.  The rule for ratios also gives 
$$\frac{\d Z_2}{Z_2} = \frac{\d S}{S} - \frac{\d Y}{Y}  - \left(\frac{\d S}{S}\right)\left(\frac{\d Y}{Y}\right) + \left(\frac{\d Y}{Y}\right)^2 \,.$$
Setting the drift to be zero and using the fact that the drift of $\d Y/Y$ is $r+\phi^2$, we conclude that the drift of $\d S/S$ is
$r + \sigma\phi\rho$.  This produces the following:

::: Rule
## 
If $S$ is a dividend-reinvested asset price satisfying @eq-dSS and $Y$ is a dividend-reinvested asset price satisfying @eq-dYY, then  
$$
\frac{\d  S}{S} = (r+ \sigma\phi\rho)\d   t+\sigma\d   B^*\;,
$$ {#eq-other11}
where  $B^*$ denotes a Brownian motion under the probability measure corresponding to $Y$ being the numeraire.
:::



::: Extra

It is natural to ask at this point: What is the Brownian motion $B^*$ and where did it come from?  We have argued that once we know the drift, and the fact that the volatility does not change, we can immediately write down, for example, 
$$\frac{\d  S}{S} = (r-q)\d   t + \sigma\d   B^*$$
for a Brownian motion $B^*$ under the risk-neutral probability.  To answer this question, we will give here the definition of $B^*$ under the risk-neutral probability.  The definition shows that we are justified in writing down  @eq-riskneutral11--@eq-other11, but we will not repeat the definition each time we make a statement of this sort.     

We showed that $Z$ is a martingale under the risk-neutral probability, where $Z$ satisfies
$$
\frac{\d  Z}{Z} = (q-r)\d   t + \frac{\d  S}{S} = (q-r+\mu)\d   t + \sigma\d   B\;.
$$ {#eq-numeraire101}

Define $B^*_0 = 0$ and
$$
\d  B^* = \left(\frac{q-r+\mu}{\sigma}\right)\d   t + \d  B\;.
$$ {#eq-numeraire102}

Then 
$$\d  B^* = \frac{1}{\sigma}\left(\frac{\d  Z}{Z}\right)$$
and hence is a continuous martingale under the risk-neutral probability.  We can compute its quadratic variation as
$$(\d  B^*)^2 = \left(\frac{q-r+\mu}{\sigma}\right)^2(\d  t)^2 + 2\left(\frac{q-r+\mu}{\sigma}\right)(\d  t)(\d  B) + (\d  B)^2 = \d  t\; .$$
Therefore, by Levy's theorem (@sec-s:quadraticvariation), $B^*$ is a Brownian motion under the risk-neutral probability.   From  @eq-numeraire101 and @eq-numeraire102 we have
$$(q-r)\d   t + \frac{\d  S}{S} = \sigma\d   B^* \quad \Longleftrightarrow \quad \frac{\d  S}{S} = (r-q)\d   t + \sigma\d   B^*\;,$$
as in  @eq-riskneutral11.
:::
