{{< include macros.qmd >}}

# FX and Quantos {#sec-c:foreignexchange} 

```{python}
#| eval: true
#| echo: false

import plotly
from IPython.display import display, HTML

plotly.offline.init_notebook_mode(connected=True)
display(
    HTML(
        '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
    )
)
```


We will see in this chapter how to apply the Black-Scholes formulas to value currency options and options on foreign assets.  We will also discuss currency forwards and futures, quanto forwards, and return swaps.  

For concreteness, we will call one currency the domestic currency and the other the foreign currency. 
Let $X_t$ denote the exchange rate at time $t$ measured in units of the domestic currency per unit of the foreign currency.  Exchange rates can be confusing, because we can look at them from the perspective of either currency, so it may help to keep in mind that $X_t$ here means the price of a unit of the foreign currency, just as we might consider the price of a stock.   When we speak of the cost or value of something without specifying the currency, it should be understood to be the domestic currency that we mean.  If $S$ is the price of a foreign asset, denominated in units of the foreign currency, we can convert it into a domestic asset price simply by multiplying by the exchange rate:  $X_tS_t$ is the price of the asset, denominated in the domestic currency.  For example, if the domestic currency is dollars and the foreign currency is yen, then $S$ is in units of yen and $X$ is units of dollars per unit of yen, so $XS$ is in units of dollars.

Throughout the chapter, we will maintain assumptions similar to the Black-Scholes assumptions.  There is a foreign asset with price $S$ in the foreign currency.  It has a constant dividend yield $q$ and a constant volatility $\sigma_s$.  The exchange rate has a constant volatility $\sigma_x$ and a constant correlation $\rho$ with the foreign asset.  There is a domestic risk-free asset with constant interest rate $r$ and a foreign risk-free asset with constant interest rate $r_f$.  The term risk free means of course that they are risk-free in their respective currencies.  For example, an investment in the foreign risk-free asset is not risk free to a domestic investor, because of exchange rate risk.


## Currency Options\index{currency option}
A European call option on the exchange rate $X$ pays $\max(0,X_T-K)$ at its maturity $T$, where $K$ is the strike price (in domestic currency).  The underlying asset should be regarded as the foreign risk-free asset, the domestic price of which fluctuates with the exchange rate.   An investment in the foreign risk-free asset grows via reinvestment of interest at rate $r_f$, just as the number of shares held of a stock grows via reinvestment of dividends at rate $q$, if $q$ is its constant dividend yield.  In particular, the cost at date $0$ of obtaining one unit of foreign currency at date $T$ is the cost at date $0$ of $\mathrm{e}^{-r_fT}$ units of foreign currency, which is $\mathrm{e}^{-r_fT}X_0$.  Thus, the exchange rate is analogous to a stock price, with the foreign risk-free rate being its dividend yield.  This means we can apply the Black-Scholes formulas to value currency calls and puts:


::: Rule
## 
Calls and puts on foreign currency can be valued by the Black-Scholes formulas with inputs $X_0 =$ initial asset price, $r =$ risk-free rate, $\sigma_x =$ volatility, and $r_f =$ dividend yield.
:::




## Options on Foreign Assets Struck in Foreign Currency {#sec-s:foreignstrike}
An option on a foreign asset, with the strike price defined in the foreign currency, can be priced with the Black-Scholes formula, assuming the volatility and dividend yields of the asset are constant and that the (foreign) interest rate is constant.  This must be true, because we did not need to specify the currency (dollars, yen, etc.) when deriving the Black-Scholes formula.  The value given by the Black-Scholes formula is in the same currency as the asset.  To obtain a value in domestic currency for an option on a foreign asset, we simply multiply the Black-Scholes formula by the current exchange rate.

## Options on Foreign Assets Struck in Domestic Currency {#sec-s:domesticstrike}

A call option on a foreign asset with domestic strike price $K$ on the foreign asset with price $S$ pays
$$
\max(X_TS_T-K,0)
$$
at its maturity $T$.  The underlying price $X_TS_T$ is the value in domestic currency of the portfolio that with starts with $\mathrm{e}^{-qT}$ units of the asset and reinvests dividends until date $T$.  Thus, we can use the Black-Scholes formula to value it, taking the initial asset price to be $\mathrm{e}^{-qT}X_0S_0$ and the dividend rate to be zero (or taking the initial asset price to be $X_0S_0$ and the dividend rate to be $q$).  The volatility that should be input into the Black-Scholes formula is the volatility of the domestic currency price $\mathrm{e}^{-q(T-t)}X_tS_t$, which is the same as the volatility of $X_tS_t$.  
According to @eq-volatilityproduct, the volatility of the domestic currency price $XS$ is 
$$
\sigma = \sqrt{\sigma_x^2+\sigma_s^2+2\rho\sigma_x\sigma_s}\;.
$$ {#eq-foreignoptiondomcurrencyvol}

We conclude:

::: Rule
## 
Calls and puts on foreign assets struck in domestic currency can be valued by the Black-Scholes formulas with inputs $X_0S_0 =$ initial price, $r =$ risk-free rate, @eq-foreignoptiondomcurrencyvol =  volatility, $q =$ dividend yield.
:::


## Currency Forwards and Futures {#sec-s:currencyforwards}

Consider a forward contract maturing at some date $T$ on one unit of foreign currency.   In keeping with our convention for options, we will always assume (without loss of generality) that a forward contract is written on a single unit of currency.  Let $F_t$ denote the forward price (in domestic currency) at date $t\leq T$.  This means that someone who purchases (goes long) the contract at date $t$ will receive a unit of foreign currency, worth $X_T$, at date $T$ and must pay $F_t$ at date $T$.  \index{forward contract} The value of the long contract at date $T$ is therefore $X_T - F_t$.  The value at date $T$ of a short contract initiated at date $t$ is the opposite: $F_t-X_T$.  Naturally, the forward price $F_t$ is called the forward exchange rate. \index{forward exchange rate}

The deepest market for currency is the inter-bank forward market, but futures contracts are also traded on exchanges.  The difference between forwards and futures is that futures are marked to market daily.  \index{futures contract} \index{marking to market} Thus, there are daily cash flows with a futures contract, whereas the only cash flows on a forward contract occur at the maturity of the forward.  In both cases, there is no cash flow at the time the contract is bought/sold, so its market value is zero.  In @sec-s:futuresforwards we will discuss futures contracts further.  In particular, we will show, assuming continuous marking to market, that if there is a constant (domestic) risk-free rate---or, more generally, if there is an instantaneous risk-free rate that changes over time in a non-random way---then futures prices must equal forward prices in the absence of arbitrage opportunities.  Thus, our assumptions in this chapter imply that currency futures prices should equal currency forward prices.  We will consider currency forwards in the remainder of this section.

A forward contract on a traded asset can always be created synthetically simply by buying the asset and holding it, using borrowed money to finance the purchase and to finance any storage costs, assuming the storage costs can be estimated in advance.  \index{synthetic forward}  If the asset pays dividends or generates other positive cash flows, then we do not need to purchase the entire amount covered by the forward contract, because we can accumulate additional amounts of the asset by reinvesting the dividends.  There are no storage costs on currency and its dividend yield is equal to the foreign risk-free rate.  A forward contract on one unit of foreign currency maturing at date $T$ can be created synthetically at date $0$ by buying $\mathrm{e}^{-r_fT}$ units of foreign currency and borrowing the cost $\mathrm{e}^{-r_fT}X_0$ at the domestic risk-free rate.  This will lead to ownership of one unit of foreign currency at date $T$ and a liability, including interest, of $\mathrm{e}^{(r-r_f)T}X_0$ at date $T$.  Thus, the forward price at date $0$ must be $F_0 = \mathrm{e}^{(r-r_f)T}X_0$; otherwise, one could arbitrage by buying the forward and selling the synthetic forward, or vice versa.  More generally, 

::: Rule
## 
The forward exchange rate at date $t$, for a contract maturing at $T$, must be
$$
F_t = \mathrm{e}^{(r-r_f)(T-t)}X_t\;.
$$ {#eq-forwardexchangerate}

:::

The relation @eq-forwardexchangerate is called covered interest parity. \index{covered interest parity}The name stems from the fact that an investment in one of the risk-free assets (foreign or domestic) financed by borrowing in the other, with the currency risk hedged (covered) by a forward contract, is certain to generate zero value (otherwise, it would be an arbitrage opportunity).^[
A relation analogous to covered interest parity holds for any forward contract if the underlying asset has a constant dividend yield and storage costs that are a constant proportion of the value of the units stored.  For commodities, the term dividend yield must be interpreted in a broad sense, and is usually called convenience yield, \index{convenience yield}] because ownership of the physical asset may produce abnormal profits during temporary shortages, an advantage that is not obtained by owning a forward contract on the asset, just as dividends are not received by the owner of a forward contract.  Thus, one must consider the convenience of owning the physical asset as an advantage analogous to dividends.

Suppose that one has made a commitment to pay a certain amount of foreign currency (perhaps to a foreign manufacturer) at some date in the future.  The exchange rate risk that this commitment entails can obviously be hedged by buying the currency forward.  However, one can also create a synthetic forward, by buying currency today and investing it in the foreign risk-free asset.  The cash outflow can be incurred today, or it can be deferred by borrowing the cost of the currency at the domestic risk-free rate.  In the latter case, we have created a true synthetic forward.  In either case, we would call this a money market hedge \index{money market hedge} because we have utilized the foreign money market (risk-free asset) to create the hedge.

Later in this chapter we will construct replicating strategies for various contracts using the foreign risk-free asset and the domestic risk-free asset.  One can interpret these replicating strategies as money market hedges or synthetic currency forwards.  In practice, it will often be more convenient to use actual forwards rather than using the foreign risk-free asset.  Using actual currency forwards produces an equivalent (given that we are not considering transaction costs) replicating strategy.   Here is, in abstract, the way we convert from money market hedges to hedges using forwards.  As we have discussed,
\begin{align*}
\text{Long Currency Forward} &= \text{Long Synthetic Currency Forward} \\
&= \text{Long Foreign Risk-Free Asset} \\
&\qquad + \text{Short Domestic Risk-Free Asset}\;.
\end{align*}
Subtracting a short position is the same as adding a long position, so we can rearrange this as
\begin{multline*}
\text{Long Currency Forward} + \text{Long Domestic Risk-Free Asset}\\=  \text{Long Foreign Risk-Free Asset} \; .
\end{multline*}
Thus, an investment in the foreign risk-free asset can be replaced in any replicating strategy by long currency forwards  and an investment in the domestic risk-free asset.  

To be more precise about the sizes of the investments, consider replacing a money market hedge with a forward hedge at some date $t$ prior to the maturity of the forward and analyze the replacement per unit of the money market hedge (per unit of foreign currency invested in the foreign risk-free asset).  One unit of foreign currency invested in the foreign risk-free asset at date $t$ will grow to $\mathrm{e}^{r_f(T-t)}$ units by date $T$.  Thus, the corresponding forward contract should be on $\mathrm{e}^{r_f(T-t)}$ units of currency.  The value at date $t$ of both sides of the above equation should be the same, and the value of a forward contract at the date of initiation is zero, so the investment in the domestic risk-free asset should be the domestic currency equivalent of one unit of foreign currency, which is the exchange rate $X_t$.  Thus, we have

::: Rule
## 


$$
\begin{multline} 
 \text{$\mathrm{e}^{r_f(T-t)}$ Long Currency Forwards} \\+  \text{$X_t$ Long in the Domestic Risk-Free Asset}\\
= \text{1 Unit of Foreign Currency Long in the Foreign Risk-Free Asset}\;.
\end{multline} 
$$  {#eq-mmhedge}

:::

To check this, consider holding the portfolios until date $T$.  As explained in the first paragraph of this section, the currency forwards will have value $\mathrm{e}^{r_f(T-t)}[X_T-F_t]$, which by covered interest parity is $\mathrm{e}^{r_f(T-t)}X_T-\mathrm{e}^{r(T-t)}X_t$.  When we include the long position in the domestic risk-free asset with accumulated interest, the value at date $T$ of the portfolio on the left-hand side of @eq-mmhedge is  $\mathrm{e}^{r_f(T-t)}X_T$.  On the other, the right-hand side of @eq-mmhedge with accumulated interest will consist of $\mathrm{e}^{r_f(T-t)}$ units of foreign currency, also worth $\mathrm{e}^{r_f(T-t)}X_T$.

## Quantos {#sec-s:quantos}
A quanto \index{quanto} is a derivative written on a foreign asset the value of which is converted to domestic currency at a fixed exchange rate.  In other words, the contract pays in the domestic currency and the exchange rate is part of the contract.  Such contracts are very useful for investors who want to bet on foreign assets but do not want exposure to exchange rate risk.  Such an investor could simply buy the foreign asset and hedge the currency risk by selling currency futures or forwards, but doing so is a bit tricky because the amount of currency that needs to be hedged depends on how well the foreign asset does.  Thus, quantos can be desirable contracts.  Of course, when an investor purchases a quanto, the problem of hedging the exchange rate risk has simply been transferred to the seller.  In this and the following section, we will see how to value and how to replicate a contract that pays the price of a foreign asset at some future date $T$ with the price translated into the domestic currency at a fixed exchange rate.  The replicating strategy is the strategy that would be followed by the seller (or by an investor who wants to create a synthetic  on his own).    Specifically, in this section we will determine the value  at date $0$ (in domestic currency) of a contract that pays $\bar{X}S_T$ at date $T$, where $\bar{X}$ is a fixed exchange rate.  Later in the chapter, we will consider quanto forwards and quanto options.

In addition to being practically useful, this contract is an excellent example for demonstrating the methodology of pricing and hedging.  The best way to proceed in problems of this general type is to first value the contract and then calculate the replicating strategy.^[We did the same thing in @sec-c:blackscholes]:  we first derived the Black-Scholes formula and then found the replicating strategy (delta hedge) by differentiating the formula.  As discussed in @sec-s:introoptions, valuation is simplified by choosing a numeraire that will cancel the randomness in the contract payoff.  Our numeraire must be a dividend-reinvested (domestic) asset price, so we can choose $Z_t=X_t\mathrm{e}^{qt}S_t$ to be the numeraire asset price.  This is the value in the domestic currency of a strategy that is long one unit of the foreign asset at date $0$ and which reinvests the dividends of the asset into new shares.  As we will see immediately, using it as numeraire introduces randomness into the payoff through the exchange rate, and that poses some complications.  Applying our fundamental pricing @eq-formula, the value of the contract is

$$
Z_0 \\E^Z \left[\frac{\bar{X}S_T}{Z_T}\right] = \mathrm{e}^{-qT}X_0S_0\\E^Z \left[\frac{\bar{X}S_T}{X_TS_T}\right]
$$
$$
= \mathrm{e}^{-qT}\bar{X}S_0\\E^Z \left[\frac{X_0}{X_T}\right]\;.
$$ {#eq-quanto}



Now we need to evaluate $\\E^Z[X_0/X_T]$, which is the expected growth of $1/X$ when $Z$ is used as the numeraire.    We will show that
$$
\\E^Z \left[\frac{X_0}{X_T}\right] = \exp\left\{(r_f - r-\rho\sigma_x\sigma_s)T\right\}\;.
$$ {#eq-growthreciprocalX}

This implies:

::: Rule
## 
The value at date $0$ of a contract that pays $\bar{X}S_T$ at date $T$, where $\bar{X}$ is a fixed exchange rate and $S$ is the foreign price of an asset with a constant dividend yield $q$, is
$$
\exp\left\{(r_f - r-q-\rho\sigma_x\sigma_s)T\right\}\bar{X}S_0\;.
$$ {#eq-quanto1}

:::


::: Extra
 ## 

We will now prove @eq-growthreciprocalX.  The assumption that $S$ and $X$ have constant volatilities and  correlation means that  
\begin{align*}
\frac{\d  X}{X} &= \mu_x\d   t+\sigma_x\d   B_x\;,\\
\frac{\d  S}{S} &= \mu_s\d   t+\sigma_s\d   B_s\;,
\end{align*}
for some (possibly random) $\mu_x$ and $\mu_s$, where $B_s$ and $B_x$ are Brownian motions with correlation equal to $\rho$.  From Ito's formula, we have
\begin{align*}
\frac{\d  Z}{Z} &= q\d   t + \frac{\d  (XS)}{XS}\\
&= \left(q+\mu_x +\mu_s+ \rho\sigma_x\sigma_s\right)\d   t + \sigma_x\d   B_x + \sigma_s\d   B_s \\
&= \left(q+\mu_x +\mu_s+ \rho\sigma_x\sigma_s\right)\d   t + \sigma\left(\frac{\sigma_x}{\sigma}\d   B_x + \frac{\sigma_s}{\sigma}\d   B_s\right) \\
&= \left(q+\mu_x +\mu_s+ \rho\sigma_x\sigma_s\right)\d   t + \sigma\d   B\;,
\end{align*}
where we define $\sigma$  in @eq-foreignoptiondomcurrencyvol and $B$ by $B_0=0$ and
$$\d  B = \frac{\sigma_x}{\sigma}\d   B_x + \frac{\sigma_s}{\sigma}\d   B_s\; .$$
As discussed in @sec-s:volatilities, $B$ is a Brownian motion and $\sigma$ is the volatility of $Z$.
Notice that the correlation of $X$ and $Z$ is
\begin{align*}
(\d  B)(\d  B_x) &= \left(\frac{\sigma_x}{\sigma}\d   B_x + \frac{\sigma_s}{\sigma}\d   B_s\right)(\d  B_x)\\
&= \frac{\sigma_x + \rho\sigma_s}{\sigma}\d   t\;.
\end{align*}
Now we use @eq-other11 in @sec-s:girsanov which gives  the drift of an asset when another risky asset is used as the numeraire.  We use $Z$ as the numeraire and $X$ as the other asset, regarding $X$ as the domestic price of an asset with dividend yield $r_f$ as before.  Therefore, we substitute $r_f$ for $q$ in  @eq-other11, substitute $\sigma$ for the volatility of the numeraire asset price, substitute $\sigma_x$ for the volatility of the other asset, and substitute $(\sigma_x+\rho\sigma_s)/\sigma$ for their correlation.  This yields
$$\frac{\d  X}{X} = \left(r-r_f+\sigma_x^2+\rho\sigma_x\sigma_s\right)\d   t + \sigma_x\d   B^*_x\; ,$$
where $B^*_x$ is a Brownian motion when $Z$ is the numeraire.  
Now we apply Ito's formula for ratios to obtain
\begin{align*}
\frac{\d  (1/X)}{1/X} &= -\frac{\d  X}{X} + \left(\frac{\d  X}{X}\right)^2\\
&= \left(r_f-r-\rho\sigma_x\sigma_s\right)\d   t + \sigma_x\d   B^*_x\;.
\end{align*}
This implies  that $1/X$ is a geometric Brownian motion with growth rate $r_f-r-\rho\sigma_x\sigma_s$, from which @eq-growthreciprocalX follows.
:::


## Replicating Quantos {#sec-s:replicatingquantos}

The assets we will use to replicate the payoff $\bar{X}S_T$ are the foreign asset with price $S$, the foreign risk-free asset, and the domestic risk-free asset.  At the end of this section, we will explain how to replace the foreign risk-free asset with currency forwards, as discussed in @sec-s:currencyforwards.  Before beginning the calculations, we can make the following intuitive observations: 


-  The payoff $\bar{X}S_T$ has exposure to the foreign asset price $S$, so the replicating portfolio must be long the foreign asset.  
- The payoff $\bar{X}S_T$ has no exposure to the exchange rate, so the replicating portfolio cannot have any exposure to the exchange rate either.  Thus, the long position in the foreign risky asset must be offset by an equal short position in the foreign risk-free asset.  
- As a result of the previous observation, the value of the replicating portfolio, displayed in @eq-quanto1, will equal the investment in the domestic risk-free asset.  


Consequently, our real task is to compute the number of shares of the foreign asset that should be held, the remainder of the replicating portfolio being thereby determined.

The value of the replicating portfolio at any date $t\leq T$ must be the value at date $t$ of receiving the payoff $\bar{X}S_T$ at date $T$.  We have calculated this value at date $0$, and, clearly, @eq-quanto1 applies to general dates $t$, when we replace the time $T$ to maturity by $T-t$ and the asset price $S_0$ at the date of valuation by $S_t$.  That is, the value of the portfolio at any date $t\leq T$ must be $V_t$ defined as
$$
V_t = \exp\left\{(r_f - r-q-\rho\sigma_x\sigma_s)(T-t)\right\}\bar{X}S_t\;.
$$ {#eq-quanto2}

As just noted, we will need to invest this amount in the domestic risk-free asset at date $t$.  What remains to be done is to calculate the size of the long position in the foreign risky asset and the offsetting short position in the foreign risk-free asset.

From Ito's formula, we have
$$
\frac{\d  V}{V} = -(r_f - r-q-\rho\sigma_x\sigma_s)\d   t + \frac{\d  S}{S}\;.
$$ {#eq-quanto21}

Equivalently,
$$
\d  V =(r+q-r_f+\rho\sigma_x\sigma_s)V\d   t + V\frac{\d  S}{S}\;.
$$ {#eq-quanto5}

On the other hand, consider a strategy that invests $a_t$ units of the domestic currency in the foreign asset, $b_t$ units of the domestic currency in the foreign risk-free asset, and $c_t$ units of the domestic currency in the domestic risk-free asset.  Let $W=a+b+c$ denote the value of this portfolio.  The return on the foreign asset, per unit of domestic currency invested, is

$$
\frac{\d  (X\mathrm{e}^{qt}S)}{X\mathrm{e}^{qt}S} = q\d   t+\frac{\d  X}{X} + \frac{\d  S}{S} + \left(\frac{\d  X}{X} \right)\left( \frac{\d  S}{S}\right) 
$$
$$
= (q+\rho\sigma_x\sigma_s)\d   t+\frac{\d  X}{X} + \frac{\d  S}{S}\;.
$$ {#eq-quanto200}


Similarly, the rate of return on the foreign risk-free asset is
$$
\frac{\d  (\mathrm{e}^{r_ft}X)}{\mathrm{e}^{r_ft}X} = r_f\d   t + \frac{\d  X}{X}\;,
$$ {#eq-quanto300}

and of course the rate of return on the domestic risk-free asset is $r\d   t$.  Therefore, the change in the value of the portfolio will be

$$
\d  W = a\left[(q+\rho\sigma_x\sigma_s)\d   t+\frac{\d  X}{X} + \frac{\d  S}{S}\right] + b\left[r_f\d   t + \frac{\d  X}{X}\right] + cr\d   t
$$
$$
=( aq+a\rho\sigma_x\sigma_s + br_f+cr)\d   t +  (a+b)\frac{\d  X}{X} +a \frac{\d  S}{S}\; .
$$ {#eq-quanto6}


The change @eq-quanto6 of the portfolio value will match the change @eq-quanto5 of $V$ if and only if
$$
a= V, \qquad b= -V, \qquad c = V\;.
$$ {#eq-quanto7}

This implies:

::: Rule
## 
The strategy that replicates the payoff $\bar{X}S_T$ at date $T$ is to invest $V_t$ units of  domestic currency in the foreign asset, where $V_t$ is defined in @eq-quanto2.  This will purchase
$$
\frac{V_t}{X_tS_t} = \frac{\bar{X}}{X_t}\exp\left\{(r_f - r-q-\rho\sigma_x\sigma_s)(T-t)\right\}
$$ {#eq-quanto4}

shares of the foreign asset.  This position is financed entirely by borrowing at the foreign risk-free rate.  On the other hand, the same amount $V_t$ of the domestic currency is invested in the domestic risk-free asset. 
:::


From our analysis at the end of @sec-s:currencyforwards, we know that the  foreign risk-free asset in this replicating strategy can be replaced by currency forwards.  The strategy here involves borrowing at the foreign risk-free rate, so we should replace long by short in  @eq-mmhedge.  Borrowing $V_t$ units of  domestic currency means borrowing $V_t/X_t$ units of the foreign currency.  Therefore,  @eq-mmhedge gives us:

::: Rule
## 
An equivalent strategy for replicating the payoff $\bar{X}S_T$ at date $T$ is to invest $V_t$ units of  domestic currency in the foreign asset and to be short $\mathrm{e}^{r_f(T-t)}V_t/X_t$ currency forwards  at  date $t$.
:::
 

At the beginning of the previous section, we noted that an investor who wants to bet on a foreign asset but does not want the exchange rate exposure could simply buy the asset and sell the currency forward.  This shows how much of the asset he should buy and how much currency he should sell forward.

It is important to note that this strategy involves continuously buying and selling forwards, just as it involves continuously trading the foreign asset.    Buying at date $t$ a forward contract sold at date $s<t$ cancels the delivery obligation on the contract sold at $s$ and leaves a cash flow of $F_s-F_t$ to be paid/received at the maturity date $T$.  Therefore, the strategy accumulates a liability or asset, depending on the direction the forward price moves, to be received at $T$.  On the other hand, maintaining an investment of $V_t$ in the foreign asset will generate cash flows as the asset is sold or purchased over time.  As  @eq-quanto4 shows, whether it is sold or purchased depends on the direction the exchange rate moves.  These cash flows should be invested or borrowed at the domestic risk-free rate.  Thus, there is a liability or asset to be received at date $T$ that is not shown in the boxed statement immediately above, and there is an investment or liability in the domestic risk-free asset that is not shown.  It can be demonstrated that these cancel each other: if profits are made from trading forwards, then they (more precisely, their present value) will be consumed by the cost of buying the foreign asset, and vice versa.  Hedging with  forwards (and with futures) is considered in more detail in @sec-s:hedgingforwards.



## Quanto Forwards {#sec-s:quantoforwards}

In this section, we consider a contract similar to that of the previous section, except that it is a pure forward, meaning that the payment for the contract occurs at date $T$.  We maintain all of the assumptions of the previous section.  The payment at date $T$ is in domestic currency, and we define the quanto forward price in units of domestic currency.  Specifically, a long quanto forward contract, \index{quanto forward} initiated at date $t$ and maturing at date $T$ and initiated at the forward price $F^*_t$ will pay 
$$\bar{X}S_T-F^*_t$$ 
at date $T$.  The forward price $F^*_t$ should be the price that makes this contract have a value of 0 at date $t$.  

We already know how to replicate the underlying payoff $\bar{X}S_T$ of the forward contract at the cost $V_t$ defined in @eq-quanto2.  Thus, the synthetic quanto forward is to purchase the replicating strategy and to borrow the cost $V_t$ at the domestic risk-free rate.  This leads to the liability $\mathrm{e}^{r(T-t)}V_t$ at date $T$.  Therefore, we have:

::: Rule
## 
The quanto forward price is 
$$
F^*_t = \mathrm{e}^{r(T-t)}V_t = \exp\left\{(r_f - q-\rho\sigma_x\sigma_s)(T-t)\right\}\bar{X}S_t\;.
$$ {#eq-quantoforward0}

:::


Notice that borrowing $V$ in domestic currency to finance the replicating strategy of the previous section --- i.e., the domestic currency investments described in @eq-quanto7 --- means eliminating the domestic risk-free investment $c=V$ required in the previous section.  The replicating strategy for the quanto forward is simply to invest $V$ in the foreign asset and to finance the investment entirely by borrowing at the foreign risk-free rate.  As in the previous section, borrowing at the foreign risk-free rate can be replaced by borrowing at the domestic risk-free rate and selling currency forwards.  

## Quanto Options {#sec-s:quantooptions}

Consider now a European call option on a foreign asset, with strike $K$ set in the domestic currency and the value of the foreign asset being converted to domestic currency at a fixed exchange rate $\bar{X}$.   This is called a quanto call. \index{quanto call} We maintain all the assumptions of the previous two sections.

The value of the quanto call at maturity is
$\max(0, \bar{X}S_T-K)$.
To value this, we make use of what we learned in @sec-s:quantos.  Namely, the portfolio with value $V$ defined in @eq-quanto2 replicates the payoff $\bar{X}S_T$:  in each state of the world, $V_T = \bar{X}S_T$.  Therefore, the quanto call is equivalent to a standard European call on the portfolio with domestic currency price $V$.  The value is therefore given by the Black-Scholes formula.  From @eq-quanto21 for the dynamics of $V$, we see that the volatility of $V$ is the same as that of $S$; therefore, we should input $\sigma_s$ as the volatility in the Black-Scholes formula.  Furthermore, the portfolio $V$ is dividend-reinvested (it is the value of a claim to $\bar{X}S_T$ at date $T$ with no interim cash flows), so the dividend rate in the Black-Scholes formula should be zero. Thus, we have:


::: Rule
## 
The value of a quanto call is 


\begin{multline}
 V_0\mathrm{N}(d_1) - \mathrm{e}^{-rT}K\mathrm{N}(d_2) \\= \exp\left\{(r_f - r-q-\rho\sigma_x\sigma_s)T\right\}\bar{X}S_0\mathrm{N}(d_1) - \mathrm{e}^{-rT}K\mathrm{N}(d_2)\;,
\end{multline}
 {#eq-quantocall21}

where


$$
d_1 = \frac{\log\left(\frac{V_0}{K}\right)+\left(r+\frac{1}{2}\sigma_s^2\right)T}{\sigma_s\sqrt{T}}
$$
$$
= \frac{\log\left(\frac{\bar{X}S_0}{K}\right)+\left(r_f-q-\rho\sigma_x\sigma_s+\frac{1}{2}\sigma_s^2\right)T}{\sigma_s\sqrt{T}}\; ,
$$
$$
d_2 = d_1 - \sigma_s\sqrt{T}\;.
$$

Likewise, the value of a quanto put \index{quanto put} is given by the Black-Scholes formula:
$$\mathrm{e}^{-rT}K\mathrm{N}(-d_2) - V_0\mathrm{N}(-d_1)\; .$$
:::

Notice that this is simply the Black-Scholes call option formula with inputs $V_0=$ initial asset price, $K=$ exercise price, $r=$ interest rate, $\sigma_s=$ volatility, $0=$ dividend yield, and $T=$ time to maturity.

We can hedge a written quanto call the same way we hedge a written ordinary call: we buy delta shares of the underlying and borrow the difference between the cost of the delta shares and the option value.  However, for the quanto call, the underlying should be regarded as the portfolio with value $V$ described  in @sec-s:quantos.  This portfolio consists of investing $V_0$ units of domestic currency in the foreign asset, borrowing the same amount at the foreign risk-free rate, and investing $V_0$ units of domestic currency in the domestic risk-free asset.  The delta of the call is $\mathrm{N}(d_1)$, so the hedge consists of investing $\mathrm{N}(d_1)V_0$ units of domestic currency in the foreign asset, borrowing the same amount at the foreign risk-free rate, and investing $\mathrm{N}(d_1)V_0$ in the domestic risk-free asset.  The difference between the cost of this portfolio and the value of the option is
$$\mathrm{N}(d_1)V_0 - [V_0\mathrm{N}(d_1) - \mathrm{e}^{-rT}K\mathrm{N}(d_2)] = \mathrm{e}^{-rT}K\mathrm{N}(d_2)\; .$$
This amount is to be borrowed at the domestic risk-free rate.  Thus, the net investment in the domestic risk-free asset is
$$\mathrm{N}(d_1)V_0 - \mathrm{e}^{-rT}K\mathrm{N}(d_2)\; ,$$
which is just the value of the option.  To summarize:

::: Rule
## 
 To delta-hedge a written quanto call, one should invest $\mathrm{N}(d_1)V_0$ units of domestic currency in the foreign asset, borrow the same amount at the foreign risk-free rate, and invest the value of the option in the domestic risk-free asset.
:::


As in @sec-s:replicatingquantos, borrowing $\mathrm{N}(d_1)V_0$ units of domestic currency at the foreign risk-free rate can be replaced by borrowing the same amount at the domestic risk-free rate and selling $\mathrm{e}^{r_fT}\mathrm{N}(d_1)V_0/X_0$ currency forwards.  This results in:

::: Rule
## 
An equivalent delta hedge for a written quanto call is to  invest $\mathrm{N}(d_1)V_0$ units of domestic currency in the foreign asset, sell $\mathrm{e}^{r_fT}\mathrm{N}(d_1)V_0/X_0$ currency forward contracts at the market forward price $F_0$, and borrow $\mathrm{e}^{-rT}K\mathrm{N}(d_2)$ at the domestic risk-free rate.
:::


## Return Swaps {#sec-s:returnswaps}
There are many types and applications of return swaps, \index{return swap} but here is one important example that involves the concepts discussed in this chapter.  Suppose an investor wants to receive at date $T$ the difference in the rates of return of two assets that are denominated in different currencies.  The return will be calculated on a given notional principal.  \index{notional principal} For example, an investor may want to receive at the end of a year the Nikkei rate of return minus the rate of return on the S\&P 500, calculated on a \$1 million notional principal.  If the Nikkei earns 15\% over the year and the S\&P earns 10\%, then the payment to the investor is 5\% of \$1 million.  If the reverse happens---the Nikkei earns 10\% and the S\&P earns 15\%---then the investor must pay 5\% of \$1 million to the counterparty.

To model this,  let $S_f$ denote the price of a foreign asset and $S_d$ the price of a domestic asset.  Assume they have constant dividend yields $q_f$ and $q_d$.  If the returns are calculated excluding dividends, as is likely to be the case, then the payment to the investor is
$$\left(\frac{S_f_T-S_f_0}{S_f_0} - \frac{S_d_T-S_d_0}{S_d_0}\right)  A = \left(\frac{S_f_T}{S_f_0} - \frac{S_d_T}{S_d_0}\right)  A\; ,$$
where $A$ denotes the notional principal.  Of course, the investor may want the reverse swap, and we consider this particular case only for concreteness.

The swap may have nonzero market value at date $0$, which means that some payment will have to be made upfront.  To eliminate this, we can add a swap spread into the contract, affecting the cash flow at date $T$.  This is a constant number $a$ (which may be positive or negative), and including it changes the payment to the investor to
$$
\left(a+\frac{S_f_T}{S_f_0} - \frac{S_d_T}{S_d_0}\right)  A\;.
$$ {#eq-returnswap1}

The question we will address here is: what is the fair swap spread; i.e., \index{swap spread} for what number $a$ does the cash flow @eq-returnswap1 have zero market value at date $0$?

If the value is zero, then it is zero for any notional principal $A$, so we can conveniently take $A=1$.  The cash flow consists of three pieces, all of which are to be received/paid at date $T$: the constant $a$, the gross return on the foreign asset, and the gross return on the domestic asset.  The value at date $0$ of receiving $a$ units of domestic currency is obviously $\mathrm{e}^{-rT}a$.  As we have observed several times before, the value at date $0$ of receiving 
$S_d_T$ units of domestic currency at date $T$ is $\mathrm{e}^{-q_d t}S_d_0$, because this is the cost of enough shares to accumulate to one share at date $T$ via reinvestment of dividends.  Therefore, the value at date $0$ of receiving $S_d_T/S_d_0$ at date $T$ is  $\mathrm{e}^{-q_dT}S_d_0/S_d_0 = \mathrm{e}^{-q_dT}$.

What remains is to calculate the value of receiving $S_f_T/S_f_0$ units of domestic currency at date $T$.  We can do this by interpreting $1/S_f_0$ as the fixed exchange rate $\bar{X}$ in the definition of a quanto.^[To make sense of the units, note that the cash flow of $S_f_T/S_f_0$ units of domestic currency can be calculated as $S_f_T$ units of foreign currency times $1/S_f_0$ units of domestic currency per unit of foreign currency.  Therefore, the units of $1/S_f_0$ can be taken to be the units of an exchange rate.]  We need to assume as before that the foreign asset price $S_f$ and the exchange rate have constant volatilities and a constant correlation.  Denoting the volatilities by $\sigma_s$ and $\sigma_x$ and the correlation by $\rho$ as before, equation~@eq-quanto1 shows that the value of receiving $\bar{X}S_f_T = S_f_T/S_f_0$ units of domestic currency at date $T$ is
$$\exp\left\{(r_f - r-q_f-\rho\sigma_x\sigma_s)T\right\}\; .$$
Adding up the pieces, the value at date $0$ of the cash flow @eq-returnswap1 (with $A=1$) is
$$\mathrm{e}^{-rT}a + \exp\left\{(r_f - r-q_f-\rho\sigma_x\sigma_s)T\right\} - \mathrm{e}^{-q_dT}\; ,$$
so we conclude:

::: Rule
## 
The fair swap spread, which equates the value at date $0$ of receiving the cash flow @eq-returnswap1 at date T to zero, is
$$
a = \exp\left\{(r-q_d)T\right\} - \exp\left\{(r_f -q_f-\rho\sigma_x\sigma_s)T\right\}\;.
$$ {#eq-fairswapspread}


:::

\section[Uncovered Interest Parity]{Uncovered Interest Parity in the Risk-Neutral Probabilities}

When we use numerical methods to value American and path-dependent options, as in @sec-c:introcomputation, we typically focus on the dynamics of asset prices under the risk-neutral probability.  To apply these results to currency options or options on foreign assets, we need to know the dynamics of the exchange rate under the risk-neutral probability.  Because we can view the exchange rate as the domestic price of an asset with the foreign risk-free rate $r_f$ being its dividend yield, we have already calculated these dynamics in equation~@eq-riskneutral11 of @sec-s:girsanov.  The result is:

::: Rule
## 
The exchange rate $X$ must satisfy
$$
\frac{\d  X}{X} = (r-r_f)\d   t + \sigma_x\d   B^*_x
$$ {#eq-uncoveredparity}

for some process $\sigma_x$, where $B^*_x$ is a Brownian motion under the risk-neutral probability.
:::
  

This equation has an interesting interpretation in terms of uncovered interest parity, \index{uncovered interest parity} which is the theory that differences in interest rates across currencies will be offset on average by appreciation/depreciation of the currencies.  In other words, it is the theory that the strategy of borrowing in low-interest-rate currencies to invest in high-interest-rate currencies will not earn money on average because of depreciation of the high-interest-rate currency relative to the low-interest-rate currency.  It is well known that this theory is not always true in reality.  However, equation~@eq-uncoveredparity shows that it is true when we calculate expectations using the risk-neutral probability.

To see the interpretation of equation~@eq-uncoveredparity as uncovered interest parity, suppose that the foreign interest rate $r_f$ is lower than the domestic rate $r$.  Then one may be tempted to borrow at the foreign rate and invest at the domestic rate.  This would create a short position in the foreign currency.  @eq-uncoveredparity states that the exchange rate is expected (under the risk-neutral probability) to appreciate at the rate $r-r_f$; thus, repayment of the foreign currency will be more expensive in terms of domestic currency, offsetting the interest rate differential.


## {.unnumbered}

::: Exercise
 Create a python code to compare the values of call options on foreign assets that are (i) struck in foreign currency or (ii) struck in domestic currency.  Prompt the user to input $X_0$, $S_0$, $K$, $r$, $r_f$, $\sigma_x$, $\sigma_s$, $\rho$, $q$ and $T$.  Take the strike price of the option struck in foreign currency to be $K$ and take the strike price of the option struck in domestic currency to be $X_0K$ (so $K$ is interpreted as an amount in foreign currency).  You should be able to confirm, for example, that if $r=r_f$ and $\rho \geq 0$ then the option struck in domestic currency is more valuable.
:::
::: Exercise
 Repeat the preceding problem comparing (i) call options struck in foreign currency, versus (ii) quanto call options.  Use the same inputs as in the preceding problem and take the fixed exchange rate in the quanto to be $\bar{X}=X_0$.  You should be able to confirm, for example, that if $r=r_f$ and $\rho \geq 0$ then the option struck in foreign currency is more valuable.
:::
::: Exercise
 Create a python code in which the user inputs $r$ and $r_f$ and the exchange rate.  Compute the forward exchange rate at maturities $T=0.1, 0.2, \dots, 2.0$ and plot the forward rate against the maturity in a scatter plot. A market is said to be in contango if this curve is upward sloping and to be in backwardation if this curve is downward sloping.  For currencies, what determines whether the market is in contango or in backwardation?
:::
::: Exercise
 Create a Python function to simulate a path of the exchange rate and the forward exchange rate under the risk-neutral probability, prompting the user to input $X_0$, $r$, $r_f$, $\sigma_x$, and the maturity $T$ of the forward contract.
:::
::: Exercise
 Create a Python function to simulate a path of the exchange rate under the actual probability measure, prompting the user to input $X_0$, $\sigma_x$, and the expected rate of growth $\mu$ of the exchange rate under the actual probability measure.  Prompt the user also to input $S_0$, $r$, $r_f$, $\sigma_s$, $q$, $\rho$, a fixed exchange rate $\bar{X}$, a maturity $T$, and a number of periods $N$.  Calculate the gain/loss from the portfolio that promises to pay $\bar{X}S_T$ at date $T$ and uses a discretely rebalanced hedge, rebalancing at dates $t_1,\ldots t_N=T$, where $t_i-t_{i-1} = T/N$, similar to the calculation in the function `Simulated_Delta_Hedge_Profit`.  Use the money-market hedge, which means investing $V_0$ at date $0$, holding the number of shares of the foreign asset shown in  @eq-quanto4 at each date $t_i$, and having a short position in the foreign risk-free asset of the same value at each date $t_i$.  Cash flows generated at each date from buying/selling the foreign asset and lending/borrowing at the foreign risk-free rate should be withdrawn/deposited in the domestic risk-free asset.  Note: Because of discrete rebalancing, this is not a perfect hedge, and the investment in the domestic risk-free asset will not always equal $V_t$.  
:::
::: {#exr-e_forwardhedging}
  Repeat the previous exercise using the forward contract hedge discussed in @sec-s:replicatingquantos.  The cash flows generated from trading forwards cannot be withdrawn/deposited in the domestic risk-free asset, because they do not materialize until the maturity of the forward.  You will have to create a variable to keep track of the net asset/liability and include it in the valuation at date $T$.
:::
::: Exercise
 Derive the  money-market hedge and the forward contract hedge for a written quanto put.
:::
::: Exercise
 Suppose a customer has contracted with you for a return swap in which the customer will receive the cash flow @eq-returnswap1 for some number $a$, where $A=1$.  How can you hedge this?
:::
