{{< include macros.qmd >}}

# Options {#sec-c:options} 

```{python}
#| eval: true
#| echo: false

import plotly
from IPython.display import display, HTML

plotly.offline.init_notebook_mode(connected=True)
display(
    HTML(
        '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
    )
)
```


Financial options are rights to buy and sell assets at pre-specified prices.  The rights are traded on exchanges and also as private contracts (called over-the-counter or OTC).  A call option is a right to buy an asset.  A put option is a right to sell an asset.  The pre-specified price is called the exercise price, the strike price, or simply the strike.   The asset to which an option pertains is called the underlying asset, or, more briefly, the underlying.  

Here is a snapshot of market statistics regarding call options on Apple stock (AAPL) traded on the Chicago Board Options Exchange (CBO\\E).  We are accessing the data courtesy of Yahoo Finance.  


```{python}

#| label: aapl-table
#| fig-cap: "Market data for AAPL options"
#| execute: auto

import pandas as pd
import yfinance as yf
from datetime import datetime
import pytz
from datetime import datetime

est = pytz.timezone('US/Eastern')
fmt = '%Y-%m-%d %H:%M:%S'
now = datetime.today().astimezone(est).strftime(fmt)

ticker = "AAPL"         # ticker to pull
kind = "call"           # call or put
maturity = 4            # option maturity in order of maturities trading

tick = yf.Ticker(ticker.upper())

# Pull last stock price
close = tick.history().iloc[-1].Close

# Get maturity date
date = tick.options[maturity]

# Pull options data
df = (
    tick.option_chain(date).calls
    if kind == "call"
    else tick.option_chain(date).puts
)

df.lastTradeDate = df.lastTradeDate.map(
    lambda x: x.astimezone(est).strftime(fmt)
)

# Formatting
cols = [
    "strike",
    "bid",
    "ask",
    "lastPrice",
    "change",
    "percentChange",
    "lastTradeDate",
    "volume",
    "openInterest",
    "impliedVolatility",
]
df = df[cols]
df["impliedVolatility"] = df["impliedVolatility"].map("{:.1%}".format)
df["change"] = df["change"].round(2)
df["percentChange"] = (df["percentChange"]/100).map("{:.1%}".format)
df.columns = [
    "Strike",
    "Bid",
    "Ask",
    "Last Price",
    "Change",
    "% Change",
    "Time of Last Trade",
    "Volume",
    "Open Interest",
    "Implied Volatility",
] 
df = df.set_index("Strike")
print(f'Maturity date of options:\t{date}')
print(f"Code executed at \t{now}")
print(f"Last {ticker.upper()} price was \t${close:.2f}.")

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
print(df)
```

The maturity date for the particular contracts that are displayed is shown in the text above the table.  Many different maturities are traded throughout each day.  The data shown is 15 minutes delayed (and obviously more than 15 minutes if the code is executed outside trading hours).

The first column shows the strike prices of the calls and puts that are available for trading. The exchange chooses which strikes people can trade and at which maturities.  As the price of AAPL stock moves, the exchange will introduce new strikes to maintain a bracket around the stock price.  Typically, interest in trading the strikes that become further away from the stock price will decline, except for people closing positions.  Positions are closed when a trader makes an offsetting trade: buying the same maturity and strike if they sold before or selling if they bought before.  The offsetting trade cancels the option or obligation created by the initial trade, and the trader gains or loses the difference between the selling and buying prices.

When a strike is first introduced for trading, no one has a position in it.  Positions are created by trade.  We say that a buyer is long the option, and a seller is short.  The standard contract size is 100 shares, so a buyer of one contract is long options on 100 shares of the underlying asset (AAPL in this example), and a seller is short options on 100 shares.  The number of longs always equals the number of shorts.  If the first trade is for 1 contract, we say that open interest is 1 contract, meaning that there is 1 long and 1 short.  Subsequent trades increase open interest if new positions are created or reduce  open interest if existing positions are closed.  Open interest is shown in the penultimate column of the table.

When a trade is made on an exchange, the exchange clearinghouse becomes the counterparty to both sides.  For example, anyone who is long a call option has an option to buy the underlying asset at the strike *from the clearinghouse*.  Simlarly, anyone who is short a call option has an obligation to deliver the underlying asset *to the clearinghouse* and receive the strike, should the clearinghouse exercise the option.  The clearinghouse exercises options when an option of the same strike and maturity is exercised against it.  This causes the underlying asset to be passed through the clearinghouse from the short party to the long party when the long party exercises.  The strike is passed through in the opposite direction.  The short party against whom the clearinghouse exercises is chosen randomly among the people who are short that particular option.  The risk of a short party defaulting when an option is exercised is thus borne by the clearinghouse.  The clearinghouse wishes to minimize this risk and therefore requires a seller of an option to post collateral in a margin account.  This procedure provides the long party assurance that the option will be honored, which would otherwise be impossible with anonymous trade.  It also makes it possible for contracts to be cancelled by making offsetting trades with a different counterparty than the counterparty to the original trade.


::: Example
Suppose the first trade is person B buying and person S selling a single contract.  Then, open interest is 1 contract.  Suppose the second trade is person S buying and person R selling.  Then, open interest is still 1 contract, with B being long and R short.  Person S has a gain or loss depending on the trade prices but no longer has a position in the option.  If the next trade is person C buying a contract and person Q selling, then open interest is 2 contracts, with B and C being long a single contract each  and R and Q being short a single contract each.  If now B decides to exercise her option, then the clearinghouse will randomly choose either R or Q to exercise against, and the underlying asset will be transferred from that person to B, and the strike paid by B will be delivered to the same person. After the option exercise, open interest is 1 contract.
:::

The second column of the table shows the bid prices. The bid price is the highest price at which other traders are willing to buy (it is what traders are bidding for the option, as in bidding to buy a house).  So, if you submitted an order to sell at the market price (called a market order), you would trade at the bid, assuming the bid did not change before your order reached the exchange's computers.  Thus, the bid price is what you would pay for the right to buy AAPL at the strike price at any time up to and including the maturity date.

The ask price is the lowest price at which others are willing to sell (similar to the asking price for a house).  The difference between the ask price and the bid price is called the bid-ask spread.  An alternative to submitting a market order and trading at the bid or ask is to submit a limit order.  A limit order specifies a limit price: a buyer will not pay more than her specified limit price, and a seller will not receive less than his specified limit price.  A limit order provides a trader the opportunity to receive a better price than the current market price, but the downside is that the limit order may never execute. 

::: Example
Suppose you want to buy an option, and you submit a limit order with a price of $5.00. Of course, you will be happy to buy at a lower price also.  If the current market ask price is $4.90, then your order will execute immediately at $4.90.  On the other hand, if the market is trading at a bid of $5.10 and an ask of $5.25, then you cannot immediately buy at $5.00 or less, so your limit order will join the queue of limit orders, called the limit order book.  If the market for the option rises, then you will never be able to buy at $5.00, and your order will never execute.  However, if the market falls, then your $5.00 order will eventually become the best bid and execute against an incoming market sell order.
:::

For call options, bid and ask prices are lower for higher strikes.  It is better to have the right to buy AAPL at $100 a share than to have the right to buy it at $200 per share, so the market price of the former is higher than the price of the latter.

The fourth column of the table shows the most recent transaction price.  For strikes away from the current AAPL price, the most recent transaction may have been several days ago.  The change and %change are the changes during the current trading day relative to the last price of the prior day (more precisely, it is relative to the settlement price, which is discussed below).  The volume is the number of contracts traded on the most recent day on which the strike traded.  Implied volatility, shown in the last column, is discussed in @sec-c:blackscholes.



```{python}

# Pull options data
kind = "put"
df = (
    tick.option_chain(date).calls
    if kind == "call"
    else tick.option_chain(date).puts
)

df.lastTradeDate = df.lastTradeDate.map(
    lambda x: x.astimezone(est).strftime(fmt)
)

# Formatting
cols = [
    "strike",
    "bid",
    "ask",
    "lastPrice",
    "change",
    "percentChange",
    "lastTradeDate",
    "volume",
    "openInterest",
    "impliedVolatility",
]
df = df[cols]
df["impliedVolatility"] = df["impliedVolatility"].map("{:.1%}".format)
df["change"] = df["change"].round(2)
df["percentChange"] = (df["percentChange"]/100).map("{:.1%}".format)
df.columns = [
    "Strike",
    "Bid",
    "Ask",
    "Last Price",
    "Change",
    "% Change",
    "Time of Last Trade",
    "Volume",
    "Open Interest",
    "Implied Volatility",
] 
df = df.set_index("Strike")
print(f'Maturity date of options:\t{date}')
print(f"Code executed at \t{now}")
print(f"Last {ticker.upper()} price was \t${close:.2f}.")

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
print(df)
```


## Intrinsic Value and Time Value





## Investing in Options


## Hedging with Options


## Selling Options for Income


## Option Spreads


::: {#fig-option_portfolios fig-cap="The value at maturity of a portfolio of options is plotted, assuming all of the options have the same maturity.  Enter positive quantities for long positions in options and negative quantities for short positions.  Long or short positions in the underlying asset can also be included. Cash means a position in a risk-free asset sufficient to deliver the specified amount of cash at the option maturity, for example, a long or short position in a zero-couponbond that matures at the option maturity."}

<iframe width="780" height="400" src="https://derivatives-book-26ac36570fb8.herokuapp.com/chapter1/option_portfolios"></iframe>


:::

## Put-Call Parity


## American Options


## Dividends


