# Asset Pricing Basics {#c_basics}

This chapter introduces the "change of numeraire" (or "martingale")
method for valuing derivative securities. The method is introduced in a
binomial model and then extended to more general (continuum of states)
models. Computations in the more general model require the
continuous-time mathematics that will be presented in
@sec-c_continuoustime. We will begin with a brief description of
the basic derivatives (calls and puts) and some other financial
concepts. More detailed descriptions can be found in any of the many
introductory books on derivative securities (e.g., [@Hull] or
[@McDonald]).

It should be noted that the pricing and hedging results in this book are
not tied to any particular currency. However, for specificity (and as a
consequence of the author's habit) the discussion will generally be in
terms of dollars. Multiple currencies are addressed in
@sec-c_foreignexchange.

# Fundamental Concepts {#s_fundamentalconcepts}

## Longs, Shorts, and Margin {#longs-shorts-and-margin .unnumbered}

In financial markets, the owner of an asset is said to be "long" the
asset. If person A owes something to person B, the debt is an asset to
person B but a liability to person A. One also says that person A is
"short" the asset. For example, if someone borrows money and invests the
money in stocks, then the individual is short cash and long stocks.

One must invest some of one's own money when borrowing money to buy
stocks. For example, an individual could invest \$600, borrow \$400, and
buy \$1000 of stock. The \$600 is called the "margin" posted by the
investor, and buying stocks in this way is called buying "on margin."
The investor, or the portfolio, is also said to be "levered," because
buying \$1000 of stock with only a \$600 investment amplifies the risk
and return per dollar of investment. On a percentage basis, we would say
the account has 60% margin, the 60% being the ratio of the equity
(assets minus liabilities = \$1000 of stock minus \$400 debt) to the
assets (\$1000 of stock). !!!Replace next part with better explanation.  Include Fed Reg T.!!!  If the value of the stock drops sufficiently
far, then it may become doubtful whether the investor can repay the
\$400. In this case, the investor must either sell the stock or invest
more of his own funds (i.e., he receives a "margin call").  In other
words, in actual markets there are "margin requirements," that specify a
minimum percent margin an investor must have initially (when borrowing
money) and a minimum percent margin the investor must maintain.  

Rather than borrowing money to buy stocks, an investor can do the
opposite---he can borrow stocks to buy money. In this case, "buying
money" means selling the borrowed stocks for cash. Such an investor will
be short stocks and long cash. This is called "short selling" (or, more
briefly, "shorting") stocks. For example, suppose individual A borrows
100 shares of stock from individual B and then sells them to individual
C. Both B and C are long the 100 shares and A is short, so the net long
position is $2 x 100 - 100$, which is the original 100 shares that
B was long. A short seller of stocks must pay to the lender of the
stocks any dividends that are paid on the stock. In our example, both B
and C own the 100 shares so both expect to receive dividends. The
company will pay dividends only to C, and A must pay the dividends to B.

Of course, investors always wish to buy low and sell high. The usual
method is to buy stocks and hope they rise. An investor who short sells
also wishes to buy low and sell high, but he reverses the order---he
sells first and then hopes the stocks fall. The risk is that the stocks
will instead rise, which will increase the value of his liability (short
stock position) without increasing the value of his assets (long cash
position), thus putting him "under water." To shield the lender of the
stocks from this risk, a short seller must also invest some of his own
funds, and this amount is again called the investor's margin. For
example, an investor might invest \$600, and borrow and sell \$1000 of
stock. In this case, the investor will be long \$1600 cash and short
\$1000 worth of stock. His equity is \$600 and his percent margin is
calculated as \$600/\$1000 = 60%. Again, there are typically both
initial and maintenance margin requirements. An additional feature of
short selling for small individual investors is that they typically will
not earn interest on the proceeds of the short sale (the \$1000 cash
obtained from selling stocks in the above example).

In this book, we will assume there is a single risk-free rate at which
one can both borrow and lend. Moreover, we will assume that investors
earn this rate on margin deposits, including the proceeds of short sales
(and including any margin that may be required when buying and selling
forward and futures contracts). Thus, investors gain from buying on
margin if the asset return is sure to exceed the risk-free rate, and
they gain from short selling if the return on an asset is sure to be
below the risk-free rate. These assumptions are not reasonable for small
individual investors, but they are fairly reasonable for institutional
investors. We will assume that no asset has a return that is certain to
be above the risk-free rate nor certain to be below the risk-free rate,
because institutional investors could "arbitrage" such guaranteed
high-return or guaranteed low-return assets.

## Calls and Puts {#calls-and-puts .unnumbered}

Call and put options are the basic derivative securities and the
building blocks of many others. A derivative security is a security the
value of which depends upon another security.

A call option is the right to buy an asset at a pre-specified price. The
pre-specified price is called the exercise price, the strike price, or
simply the strike. We will often call the asset a "stock," but there are
options on many other types of assets also, and everything we say will
be applicable to those as well.[^1] The asset to which the call option
pertains is called the "underlying asset," or, more briefly, the
"underlying." If the market value of the asset exceeds the exercise
price, then we say the call option is "in the money." Buying a call
option is a way to bet on the upside of the underlying asset.

[^1]: One caveat is that by "asset" we mean something that can be
    stored; thus, for example, electricity is, practically speaking, not
    an asset.


A put option is the right to sell an asset at a pre-specified (exercise,
strike) price. Buying a put is a way to bet on an asset price becoming
low (similar to shorting). A put option is in the money if the exercise
price exceeds the value of the asset. Both puts and calls are
potentially valuable and hence the buyer of a put or call must pay the
seller.

A long put option provides insurance to someone who is long the
underlying asset, because it guarantees that the asset can always be
sold at the strike price of the put (of course, it can be sold at the
market price, if that is higher than the strike of the put).
Symmetrically, a long call option provides insurance to someone who is
short the underlying asset. The terminology in option markets reflects
the parallels between options and insurance contracts. In particular,
the seller of an option is said to "write" the option and the
compensation (price) he receives from the buyer is called the option
"premium," just as an insurance company writes insurance contracts in
exchange for premium income. Calculating the price at which one should
be willing to trade an option is the main topic of this book.

It is important to recognize the different situations of someone who is
short a call option and someone who is long a put. Both positions are
bets on the downside of the asset. Both the investor who is short a call
and the investor who is long a put may eventually sell the underlying
asset and receive the exercise price in exchange. However, the investor
who is long a put has an option to sell the asset at the exercise price
and the investor who is short a call has an *obligation* to sell the
asset at the exercise price, should the counterparty choose to exercise
the call. Thus, the investor who is long a put will be selling at the
exercise price when it is profitable to do so, whereas the investor who
is short a call will be selling at the exercise price when it is
unprofitable. The buyer of a put must pay the premium to the seller; he
then profits if the asset price is low, with his maximum possible profit
being quite large (the maximum value is attained when the market value
of the underlying asset reaches zero). In contrast, the seller of a call
receives premium income, and the premium is his maximum possible profit,
whereas his potential losses are unbounded. Thus, these are very
different positions.

Individuals who sell calls usually sell out-of-the-money covered calls.
"Covered" means that they own the underlying asset and can therefore
deliver the underlying if the call is exercised without incurring any
further expense---they experience only an "opportunity cost" in
delivering it for less than the market price.[^1] A call being out of
the money implies that the price of the underlying must rise before the
call would be exercised against the seller; thus, the seller of an
out-of-the money covered call still has some potential for profit from
the underlying. In addition, of course, the seller receives the premium
income from the call. Institutions often follow this strategy also,
using the premium income to "enhance" their return from the underlying.
One can hedge a short call without owning a full share of the underlying
asset, if one is able to rebalance the hedge over time. Calculating such
hedges is another of the principal topics of this book.

[^1]: In contrast, one who sells a call without owning the underlying is
    said to sell a "naked call." The seller of a naked call, or the
    seller of a put, must post margin, just like a short seller of
    stocks, in order to ensure that he can meet his obligation. However,
    this does not apply to sellers of covered calls.

In a certain sense, option markets are zero-sum games. The profit earned
by one counterparty to an option transaction is a loss suffered by the
other. However, options can allow for an increase in the welfare of all
investors by improving the allocation of risk. A producer who must
purchase a certain input may buy a call option, giving him the right to
buy the input at a fixed price. This caps his expense. The seller of the
call now bears the risk that the input price will be high---in this
case, the option will be exercised and he will be forced to sell at a
price below the market price. It may be that the seller is in a better
position to bear the risk (for example, he may have less of the risk in
his portfolio) and the option transaction may thereby improve the
allocation of risks across investors. The similarity to insurance should
be apparent.

Quite complex bets or hedges can be created by combining options. For
example, a long call and put with the same strike price is called a
"straddle." Such a portfolio is (almost) always in the money. It is in
fact a bet on volatility---a big move in the underlying asset value away
from the exercise price will lead to either the call or put having a
high value. Another important example of an option portfolio is a
"collar." A collar consists of a long put and a short call, or a short
call and a long put, with the options having the same maturity. As
mentioned before, a long put provides insurance to someone who is long
the underlying asset. Selling a call provides premium income that can be
used to offset the cost of the put (the most popular type of collar is a
zero-cost collar: a collar in which the premium of the call is equal to
the premium of the put). The cost of selling a call for an owner of the
underlying is that it sells off the upside of the underlying asset---if
the value of the asset exceeds the strike price of the call, then the
call will be exercised and the underlying asset must be delivered for
the strike price (rather than the higher market price). Thus, one can
purchase the downside insurance provided by a long put by selling part
of the upside potential of the asset, rather than paying the cost of the
insurance out of pocket. There are many other examples of option
portfolios that could be given.

Some puts and calls are traded on exchanges. In this case, the exchange
clearinghouse "steps between" the buyer and seller and becomes the
counterparty to both the buyer and seller. This eliminates the risk that
the seller might default on his obligation when the buyer chooses to
exercise his option. If the owner of an option chooses to exercise, the
clearinghouse randomly chooses someone who is short the option to
fulfill the obligation. Most exchange traded options are never
exercised, because any gain on a long contract can be captured by
selling the contract at the market price, thus cancelling the position.
Obviously, however, the right to exercise is essential, because it
determines the market price. Puts and calls are also transacted "over
the counter," which means that they are private contracts of the
counterparties. Moreover, puts and calls are embedded in many other
financial instruments. A prosaic but important example is that most
homeowners have the right to pay off their mortgages early. This means
they have call options on their mortgages, with exercise price equal to
the remaining mortgage principal. Similarly, callable bonds can be
redeemed early by the company issuing them, convertible bonds have
embedded call options on the company's stock (which are exercised by
"converting" the bonds) and there are many, many other examples. Puts
and calls also exist outside financial markets. For example, a company
may begin manufacturing a new product at a small scale; if the product
is successful, the scale can be expanded. In this case, the company buys
a call option on large-scale production with the premium being the cost
of launching small-scale production. Adapting the methods developed for
financial options to value such "real options" is an important and
growing field.

## Exercise Policies for Calls and Puts {#exercise-policies-for-calls-and-puts .unnumbered}

It may be rational to exercise a call if the asset value exceeds the
exercise price. Thus, denoting the price of the asset by $S$ and the
exercise price by $K$, the owner of a call option can profit by $S-K$
dollars by exercising the option when $S>K$. If $S<K$, exercise would be
irrational. Thus, the payoff to the owner of the call option is[^1]
$\max(0,S-K)$. It has been said that timing is everything, and the
timing here should be made clearer. The simplest type of option is
called a "European" option. A European option has a finite lifetime and
can only be exercised at its maturity date. For a European call option,
the exercise strategy just described is the optimal one, with $S$
representing the asset price at the maturity date of the option.
Equally, if not more, important are "American" options, which can be
exercised at any time before maturity.

[^1]: We use the standard notation: $\max(a,b)$ denotes the larger of
    $a$ and $b$ and $\min(a,b)$ denotes the smaller.

For an American call option, the exercise strategy just described is the
optimal one at the maturity date, but it may also be optimal to exercise
prior to maturity. Let $K$ denote the exercise price, $T$ the date the
option matures, and $S(t)$ the price of the underlying asset at date
$t \leq T$. The "intrinsic value" of the call option at date $t$ is
defined to be $\max(0,S(t)-K)$. One would of course never exercise
unless the intrinsic value is positive---i.e., unless the option is in
the money. Moreover, if the asset does not pay a dividend (or other type
of cash flow) prior to the option maturity then one should not exercise
in any circumstances prior to maturity. This is captured in the saying:
"calls are better alive than dead." Exercise being suboptimal is
equivalent to the value of the option exceeding the intrinsic value.

The principle that calls on non-dividend-paying assets are better alive
than dead follows from two facts: (i) it is generally a good thing (in
financial markets as well as in life) to keep one's options open, and
(ii) early exercise implies early payment of the exercise price and
hence foregone interest. The usual protest that is heard when this
statement is made is that one should surely exercise if he expects the
stock price to plummet, because by exercising (and then selling the
stock acquired) one can lock in the current stock price rather than
waiting for it to fall, in which case the option will surely be worth
less. This intuition is a reasonable one, but it ignores the fact that
the investor could short sell the stock if he expects it to plummet---he
doesn't need to exercise the option to lock in the current stock price.
In fact, shorting the stock and retaining the option is always better
than exercising, assuming the underlying asset does not pay a dividend.

Specifically, suppose an investor considers exercising at date $t$. As
an alternative to exercising early, consider shorting the stock at
date $t$ and retaining the option. This is always better than exercising
at date $t$, because the short position can be "covered" (the stock can
be purchased and returned to the lender to cancel the short position) at
cost $K$ at date $T$ by exercising the option, and paying $K$ at date
$T$ is better than paying it at date $t$, given that interest rates must
be nonnegative. To be more precise, note that exercise at date $t$
produces $S(t)-K$ dollars at date $t$. On the other hand, retaining the
option, shorting the stock at date $t$, and covering the short either by
exercising the option or buying the stock in the market (whichever is
cheaper) produces $S(t)$ dollars at date $t$ and
$$\max(0,S(T)-K) - S(T) = \max(-S(T), -K) = -\min(S(T),K) \geq -K$$
dollars at date $T$. If $S(T)>K$, one has $-K$ dollars at date $T$, in
which case retaining the option has been superior due to the time value
of money. Furthermore, if $S(T)<K$, the strategy of retaining the option
and shorting the stock produces $-S(T) > -K$ dollars at date $T$, so
retaining the option is superior due both to flexibility (waiting until
$T$ to decide whether to exercise turns out to be better than committing
at date $t$) and because of the time value of money.[^1]

[^1]: Recall that we are assuming investors earn interest on the
    proceeds of short sales; otherwise, the $S(t)$ dollars earned from
    exercising the option and selling the stock will be worth more than
    the $S(t)$ dollars earned from shorting the stock. In this case,
    early exercise could be optimal. However, assuming institutional
    investors can earn interest on the proceeds of shorts, such
    investors should prefer owning the option and shorting the stock to
    exercising. This means they should bid up the price of the option to
    the point where it exceeds the value $S(t)-K$ of exercise. If this
    is the case, then an investor who cannot earn interest on the
    proceeds of shorts should simply sell the option in the market
    rather than exercise it. Thus, a sufficient condition for calls to
    be "better alive than dead" is that there be some investors who can
    earn interest on the proceeds of shorts. This type of reasoning is
    possible for each situation in this book where the assumption of
    earning interest on margin deposits is important, and we will not
    deal with it in this much detail again.

Early exercise of a call option can be optimal when the underlying asset
pays a dividend. The above analysis does not apply in this case, because
paying the dividend to the lender of the stock is an additional cost for
the strategy of retaining the option and shorting the stock. If the
dividend is so small that it cannot offset the time value of money on
the exercise price, then early exercise will not be optimal. In other
cases, deriving the optimal exercise strategy is a complicated problem
that we will first begin to study in
Chap. [\[c_introcomputation\]](#c_introcomputation){reference-type="ref"
reference="c_introcomputation"}.

A European put option will be exercised at its maturity $T$ if the price
$S(T)$ of the underlying asset is below the exercise price $K$. In
general, the value at maturity can be expressed as $\max(0,K-S(T))$.
Early exercise of an American put can be optimal, regardless of whether
the underlying pays a dividend. While it is valuable to keep one's
options open (for puts as well as calls) the time value of money works
in the opposite direction for puts. Early exercise of a put option
implies early receipt of the exercise price, and it is better to receive
cash earlier rather than later. In general, whether early exercise is
optimal depends on how deeply the option is in the money---if the
underlying asset price is sufficiently low, then it will be fairly
certain that exercise will be optimal, whether earlier or late; in this
case, one should exercise earlier to earn interest on the exercise
price. How low it should be to justify early exercise depends on the
interest rate (a higher rate makes the time-value-of-money issue more
important, leading to earlier exercise) and the volatility of the
underlying asset price (a lower volatility reduces the value of keeping
one's options open, leading also to earlier exercise). We will begin to
study the valuation of American puts in
Chap. [\[c_introcomputation\]](#c_introcomputation){reference-type="ref"
reference="c_introcomputation"} also.

## Compounding Interest {#s_continuouscompounding .unnumbered}

During most of the first two parts of the book (the only exception being
Chap. [\[c_forwardexchange\]](#c_forwardexchange){reference-type="ref"
reference="c_forwardexchange"}) we will assume there is a risk-free
asset earning a constant rate of return. For simplicity, we will specify
the rate of return as a continuously compounded rate. For example, if
the annual rate with annual compounding is $r_a$, then the corresponding
continuously compounded rate is $r$ defined as $r = \log (1+r_a)$, where
"$\log$" denotes the natural logarithm function. This means that the
gross return over a year (one plus the rate of return) is
$e^r = 1+r_a$. More generally, an investment of $x$ dollars for a time
period of length $T$ (we measure time in years, so, e.g., a six-month
investment would mean $T=0.5$) will result in the ownership of
$xe^{rT}$ dollars at the end of the time period.

Expressing the interest rate as a continuously compounded rate enables
us to avoid having to specify in each instance whether the rate is for
annual compounding, semi-annual compounding, monthly compounding, etc.
For example, the meaning of an annualized rate $r_s$ for semi-annual
compounding is that an investment of $x$ dollars will grow over a year
to $x(1+r_s/2)^2$. The equivalent continuously compounded rate is
defined as $r = \log (1+r_s/2)^2$, and in terms of this rate we can say
that the investment will grow in six months to $xe^{0.5 r}$ and that it
will grow in one year to $xe^r$. We can interpret this rate as being
continuously compounded because compounding $n$ times per year at an
annualized rate of $r$ results in \$1 growing in a year to $(1+r/n)^n$
and
$$\lim_{n \rightarrow \infty} \left(1+\frac{r}{n}\right)^n = e^r\;\;.$$

To develop pricing and hedging formulas for derivative securities, it is
a great convenience to assume that investors can trade continuously in
time. This requires us to assume also that returns are computed
continuously. In the case of a risk-free investment of $x(t)$ dollars at
any date $t$ at a continuously compounded rate of $r$, we will say that
the interest earned in "an instant $d t$" is $x(t)r\,d t$ dollars.
This is only meaningful when we accumulate the interest over a
non-infinitesimal period of time. So consider investing $x(0)$ dollars
at time 0 and reinvesting interest in the risk-free asset over a time
period of length $T$. Let $x(t)$ denote the account balance at date $t$,
for $0\leq t \leq T$. The change in the account balance in each instant
is the interest earned, so we have
$d x(t) = x(t)r\,d t$. The real meaning of this equation is that
$x(t)$ satisfies the differential equation
$$\frac{d x(t)}{d t} = x(t)r\; ,$$
and it is well known (and easy to verify) that the solution is
$$x(t) = x(0)e^{rt}\; ,$$
leading to an account balance at the end of the time period of
$x(T) = x(0)e^{rT}$. Thus, the statement that "the interest earned in
an instant $d t$ is $x(t)r\,d t$" is equivalent to the statement that
interest is continuously compounded at the rate $r$.

In the last part of the book, we will drop the assumption that the
risk-free asset earns a constant rate of return. In this case, we will
still generally assume that there is a risk-free asset for very
short-term investments (i.e., for investments with infinitesimal
durations!). We will let $r(t)$ denote the risk-free rate for an
instantaneous investment at date $t$. This means that an investment of
$x(t)$ dollars at date $t$ in the risk-free asset earns interest in an
instant $d t$ equal to $x(t)r(t)\,d t$. Consider again an investment
of $x(0)$ dollars at date 0 in this instantaneously risk-free asset with
interest reinvested and let $x(t)$ denote the account balance at date
$t$. Then $x(t)$ must satisfy the differential equation
$$\frac{d x(t)}{d t} = x(t)r(t)\;\;.$$
The solution of this differential equation is
$$x(t) = x(0)exp\left(\int_0^t r(s)\,ds\right)\;\;.$$
The expression $\int_0^t r(s)\,ds$ can be interpreted as a continuous
sum over time of the rates of interest $r(s)$ earned at times $s$
between 0 and $t$. If these rates are all the same, say equal to $r$,
then $\int_0^t r(s)\,ds = rt$ and our compounding factor
$exp\left(\int_0^t r(s)\,ds\right)$ is $e^{rt}$ as before.

# State Prices in a One-Period Binomial Model {#s_oneperiodbinomial}

To introduce the concepts that will be discussed in the remainder of the
chapter, we will consider in this and the following section the
following very simple framework. There is a stock with price $S$ today
(which we will call date 0). At the end of some period of time of length
$T$, the stock price will take one of two values: either $S_u$ or $S_d$,
where $S_u > S_d$. If the stock price equals $S_u$ we say we are in the
"up" state of the world, and if it equals $S_d$ we say we are in the
"down" state. The stock does not pay a dividend. There is also a
risk-free asset earning a continuously compounded rate of interest $r$.
Finally we want to consider a European call option on the stock with
maturity $T$ and strike $K$. The value of the call option at the end of
the period is $C_u=\max(0,S_u-K)$ in the up state and
$C_d=\max(0,S_d-K)$ in the down state.

We will assume
$$\label{binomialnoarbitrage}
\frac{S_u}{S} > e^{rT} > \frac{S_d}{S}\;.$$ This condition means that
the rate of return on the stock in the up state is greater than the
risk-free rate, and the rate of return on the stock in the down state is
less than the risk-free rate. If it were not true, there would be an
arbitrage opportunity: if the rate of return on the stock were greater
than the risk-free rate in both states, then one should buy an infinite
amount of the stock on margin, and conversely if the rate of return on
the stock were less than the risk-free rate in both states, then one
should short an infinite amount of stock and put the proceeds in the
risk-free asset. So what we are assuming is that there are no arbitrage
opportunities in the market for the stock and risk-free asset.

The "delta" of the call option is $delta = (C_u-C_d)/(S_u-S_d)$.
Multiplying by $S_u-S_d$ gives us $delta(S_u-S_d) = C_u-C_d$ and
rearranging yields $delta S_u - C_u = delta S_d-C_d$, which is
critical to what follows. Consider purchasing $delta$ shares of the
stock at date 0 and borrowing
$$e^{-rT}(delta S_u-C_u) = e^{-rT}(delta S_d-C_d)$$
dollars at date 0.  Then you will owe 
$$delta S_u-C_u = delta S_d-C_d$$
dollars at date $T$, and hence the value of the portfolio at date $T$ in
the up state will be
$$\text{Value of delta shares} - \text{Dollars owed} = delta S_u - (delta S_u-C_u) = C_u\; ,$$
and the value of the portfolio at date $T$ in the down state will be
$$\text{Value of delta shares} - \text{Dollars owed} = delta S_d - (delta S_d-C_d) = C_d\;\;.$$
Thus, this portfolio of buying delta shares and borrowing money (i.e.,
buying delta shares on margin) "replicates" the call option.
Consequently, the value $C$ of the option at date 0 must be the date--0
cost of the portfolio; i.e.,

$$\label{C0}
C = \text{Cost of delta shares} - \text{Dollars borrowed} = delta S - e^{-rT}(delta S_u-C_u)\;.$$

Because the call option is equivalent to buying the stock on margin, it
can be considered a levered investment in the stock.

We will now rewrite the option pricing formula
[\[C0\]](#C0){reference-type="eqref" reference="C0"} in terms of "state
prices." By substituting for $delta$ in
[\[C0\]](#C0){reference-type="eqref" reference="C0"}, we can rearrange
it as $$\begin{align}\label{binomialC1}
C &= \frac{S-e^{-rT}S_d}{S_u-S_d} \times C_u + \frac{e^{-rT}S_u-S}{S_u-S_d}\times C_d\; .
\intertext{A little algebra also shows that}
\label{binomialS1}
S &= \frac{S-e^{-rT}S_d}{S_u-S_d} \times 
S_u + \frac{e^{-rT}S_u-S}{S_u-S_d}\times S_d\; ,
\intertext{and}
\label{binomialR1}
1 &= \frac{S-e^{-rT}S_d}{S_u-S_d} \times e^{rT}+ \frac{e^{-rT}S_u-S}{S_u-S_d}\times e^{rT}\;.
end{align}$$ It is convenient to denote the factors appearing in these
equations as $$\label{binomialstateprices}
\pi_u = \frac{S-e^{-rT}S_d}{S_u-S_d} \quad \text{and} \quad \pi_d = \frac{e^{-rT}S_u-S}{S_u-S_d}\;.$$
The numbers $\pi_u$ and $\pi_d$ are called the "state prices," for
reasons that will be explained below.

With these definitions, we can write
[\[binomialC1\]](#binomialC1){reference-type="eqref"
reference="binomialC1"}--[\[binomialR1\]](#binomialR1){reference-type="eqref"
reference="binomialR1"} as $$\begin{align}
C &= \pi_uC_u + \pi_dC_d\;,\label{binomialC2}\\
S &= \pi_uS_u+\pi_dS_d\;,\label{binomialS2}\\
1 &= \pi_ue^{rT} + \pi_d e^{rT}\;.\label{binomialR2}
end{align}$$ These equations have the following interpretation: the
value of a security today is its value in the up state times $\pi_u$
plus its value in the down state times $\pi_d$. This applies to
[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} by considering an investment of \$1 today in the
risk-free asset---it has value 1 today and will have value $e^{rT}$ in
both the up and down states at date $T$. Moreover, this same equation
will hold for any other derivative asset. For example, if we considered
a put option, then a delta--hedging argument analogous to that we just
gave for the call option will lead to a formula for the value $P$ of the
put today which can be expressed as $P = \pi_uP_u+\pi_dP_d$ for the same
$\pi_u$ and $\pi_d$ defined in
[\[binomialstateprices\]](#binomialstateprices){reference-type="eqref"
reference="binomialstateprices"}.  

In this model, we can think of any security as a portfolio of what are
called "Arrow securities" (in recognition of the seminal work of Kenneth
Arrow [@Arrow]). One of the Arrow securities pays \$1 at date $T$ if the
up state occurs and the other pays \$1 at date $T$ if the down state
occurs. For example, the stock is equivalent to a portfolio consisting
of $S_u$ units of the first Arrow security and $S_d$ units of the
second, because the stock is worth $S_u$ dollars in the up state and
$S_d$ dollars in the down state. Equations
[\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} show that  $\pi_u$ is the price of the first
Arrow security and $\pi_d$ is the price of the second. For example, the
right-hand side of [\[binomialS2\]](#binomialS2){reference-type="eqref"
reference="binomialS2"} is the value of the stock at date 0 viewed as a
portfolio of Arrow securities when the Arrow securities have prices
$\pi_u$ and $\pi_d$. Because the stock clearly is such a portfolio, its
price today must equal its value as that portfolio, which is what
[\[binomialS2\]](#binomialS2){reference-type="eqref"
reference="binomialS2"} asserts.

As mentioned before, the prices $\pi_u$ and $\pi_d$ of the Arrow
securities are called the "state prices," because they are the prices of
receiving \$1 in the two states of the world. The state prices should be
positive, because the payoff of each Arrow security is nonnegative in
both states and positive in one. A little algebra shows that the
conditions $\pi_u>0$ and $\pi_d>0$ are exactly equivalent to our
"no-arbitrage" assumption
[\[binomialnoarbitrage\]](#binomialnoarbitrage){reference-type="eqref"
reference="binomialnoarbitrage"}. Thus, we conclude that **in the
absence of arbitrage opportunities, there exist positive state prices
such that the price of any security is the sum across the states of the
world of its payoff multiplied by the state price.**

This conclusion generalizes to other models, including models in which
the stock price takes a continuum of possible values. We will discuss
more general models later in this chapter. It is a powerful result that
tremendously simplifies derivative security pricing.

# Probabilities and Numeraires

In this section, we will continue our analysis of the binomial example.
To apply the statement about state prices appearing in boldface type
above in the most convenient way, we will manipulate the state prices so
we can interpret the sums on the right-hand sides of
[\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} in terms of expectations. The expectation (or
"mean") of a random variable is of course its probability-weighted
average value.

In general, there are different expectations that are useful. In this
model, there are two that we can define: one corresponding to the
risk-free asset and one corresponding to the stock. Many readers will
have experience with the first in the form of "risk-neutral
probabilities."

The risk-neutral probabilities are defined as $\pi_ue^{rT}$ for the up
state and $\pi_de^{rT}$ for the down state. Denoting these as $p_u$ and
$p_d$ respectively, [\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} can be written as $$\begin{align}
C &= e^{-rT}[p_uC_u+p_dC_d]\;,\label{binomialC3}\\
S &= e^{-rT}[p_uS_u+p_dS_d]\;,\label{binomialS3}\\
1&= p_u+p_d\;.\label{binomialR3}
end{align}$$ The numbers $p_u$ and $p_d$ are both positive (because the
state prices are positive under our no-arbitrage assumption) and
[\[binomialR3\]](#binomialR3){reference-type="eqref"
reference="binomialR3"} states that they sum to one, so it is indeed
sensible to consider them as probabilities. Equations
[\[binomialC3\]](#binomialC3){reference-type="eqref"
reference="binomialC3"} and
[\[binomialS3\]](#binomialS3){reference-type="eqref"
reference="binomialS3"} state that the value of a security today is its
expected value at date $T$ (the expectation taken with respect to the
risk-neutral probabilities) discounted at the risk-free rate. Thus,
these are "present value" formulas. Unlike the Capital Asset Pricing
Model, for example, there is no risk premium in the discount rate. This
is the calculation we would do to price assets under the actual
probabilities if investors were risk neutral (or for zero-beta assets).
So, we can act as if investors are risk neutral by adjusting the
probabilities. Of course, we are not really assuming investors are risk
neutral. We have simply embedded any risk premia in the
probabilities.[^1]

[^1]: This fundamental idea is due to Cox and Ross [@CR].


Equations [\[binomialC3\]](#binomialC3){reference-type="eqref"
reference="binomialC3"} and
[\[binomialS3\]](#binomialS3){reference-type="eqref"
reference="binomialS3"} can be written in an equivalent form, which,
though somewhat less intuitive, generalizes more readily. First, let's
introduce some notation for the price of the risk-free asset.
Considering an investment of \$1 today which grows to $e^{rT}$ at date
$T$, it is sensible to take the price today to be $R=1$ and the price in
the up and down states at date $T$ to be $R_u=R_d=e^{rT}$.[^1] In terms
of this notation, [\[binomialC3\]](#binomialC3){reference-type="eqref"
reference="binomialC3"}--[\[binomialR3\]](#binomialR3){reference-type="eqref"
reference="binomialR3"} can be written as:

[^1]: All of the equations appearing below will also be true if instead
    we take $R=e^{-rT}$ and $R_u=R_d=1$.

$$\begin{align}
\frac{C}{R} &= p_u \frac{C_u}{R_u} + p_d \frac{C_d}{R_d}\;, \label{binomialC4}\\
\frac{S}{R} &= p_u \frac{S_u}{R_u} + p_d \frac{S_d}{R_d}\;, \label{binomialS4}\\
1&=p_u+p_d\;.\label{binomialR4}
end{align}$$ Each of equations
[\[binomialC4\]](#binomialC4){reference-type="eqref"
reference="binomialC4"} and
[\[binomialS4\]](#binomialS4){reference-type="eqref"
reference="binomialS4"} states that the price of a security today
divided by the price of the risk-free asset equals the expected future
value of the same ratio, when we take expectations using the
risk-neutral probabilities. In other words, the mean of the date--$T$
value of the ratio is equal to the ratio today. We will discuss the
interpretation and significance of these equations further below. First,
we consider the other type of expectation in this model, which is based
on probabilities corresponding to the stock.

Note that the risk-neutral probabilities are the state prices multiplied
by the gross return on the risk-free asset. Analogously, define numbers
$q_u = \pi_uS_u/S$ and $q_d = \pi_dS_d/S$. Substituting for $\pi_u$ and
$\pi_d$ in [\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} and continuing to use the notation $R$ for the
price of the risk-free asset, we obtain

$$\begin{align}
\frac{C}{S} &= q_u \frac{C_u}{S_u} + q_d \frac{C_d}{S_d}\;, \label{binomialC5}\\
1 &= q_u + q_d\;,\label{binomialS5}\\
\frac{R}{S}& = q_u \frac{R_u}{S_u} + q_d \frac{R_d}{S_d}\;. \label{binomialR5}
end{align}$$ Equation
[\[binomialS5\]](#binomialS5){reference-type="eqref"
reference="binomialS5"} establishes that we can view the $q$'s as
probabilities (like the risk-neutral probabilities, they are positive
because the state prices are positive). Equations
[\[binomialC5\]](#binomialC5){reference-type="eqref"
reference="binomialC5"} and
[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} both state that the ratio of a security price to
the price of the stock today equals the mean value of the same ratio at
date $T$, when we compute expectations using the $q$'s as probabilities.


Here is some useful terminology:

-   An assignment of probabilities to events is called a *probability
    measure*, or simply a *measure* (because it "measures" the events,
    in a sense). Thus, we have described two different probability
    measures in this section.

-   The ratio of one price to another is the value of the first
    (numerator) asset when we are using the second (denominator) asset
    as the *numeraire*. The term "numeraire" means a unit of
    measurement. For example, the ratio $C/S$ is the value of the call
    when we use the stock as the unit of measurement: it is the number
    of shares of stock for which one call option can be exchanged (to
    see this, note that $C/S$ shares is worth $C/S \times S = C$
    dollars, so $C/S$ shares is worth the same as one call.)

-   A variable that changes randomly over time with the expected future
    value being always equal to the current value is called a
    *martingale*.

The right-hand sides of
[\[binomialC4\]](#binomialC4){reference-type="eqref"
reference="binomialC4"}--[\[binomialS4\]](#binomialS4){reference-type="eqref"
reference="binomialS4"} and
[\[binomialC5\]](#binomialC5){reference-type="eqref"
reference="binomialC5"} and
[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} are expectations under different *probability
measures* (the $p$'s or $q$'s). The expected future (date--$T$) value
equals the current (date--0) value, so the random variables ($C/R$ and
$S/R$ or $C/S$ and $R/S$) are *martingales*. The values $C/R$ and $S/R$
are the values of the call and stock *using the risk-free asset as
numeraire*, and the values $C/S$ and $R/S$ are the values of the call
and risk-free asset *using the stock as numeraire*. Thus, we will
express [\[binomialC4\]](#binomialC4){reference-type="eqref"
reference="binomialC4"}--[\[binomialS4\]](#binomialS4){reference-type="eqref"
reference="binomialS4"} as "the call and stock are martingales when we
use the risk-free asset as numeraire." Likewise, we will express
[\[binomialC5\]](#binomialC5){reference-type="eqref"
reference="binomialC5"} and
[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} as "the call and risk-free asset are martingales
when we use the stock as numeraire." It should be understood in both
cases that "using an asset as numeraire" means that we also use the
corresponding probability measure (i.e., the $p$'s or $q$'s). In
general, our conclusion that assets can be priced in terms of positive
state prices when there are no arbitrage opportunities can be rephrased
as:

**if there are no arbitrage opportunities, then for each
(non-dividend-paying) asset, there exists a probability measure such
that the ratio of any other (non-dividend-paying) asset price to the
first (numeraire) asset price is a martingale.**[^1]

[^1]: We have applied this statement to the risk-free asset, which pays
    dividends (interest). However, the price $R_u=R_d=e^{rT}$ includes
    the interest, so no interest has been withdrawn---the interest has
    been reinvested---prior to the maturity $T$ of the option. This is
    what we mean by a "non-dividend-paying" asset. In general, we will
    apply the formulas developed in this and the following section to
    dividend-paying assets by considering the portfolios in which
    dividends are reinvested.

For this exposition, it was convenient to first calculate the state
prices and then calculate the various probabilities. However, that is
not the most efficient way to proceed in most applications. In a typical
application, we would view the prices of the stock and risk-free asset
in the various states of the world as given, and we would be attempting
to compute the value of the call option. Note that the sets of equations
[\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"},
[\[binomialC4\]](#binomialC4){reference-type="eqref"
reference="binomialC4"}--[\[binomialR4\]](#binomialR4){reference-type="eqref"
reference="binomialR4"}, and
[\[binomialC5\]](#binomialC5){reference-type="eqref"
reference="binomialC5"}--[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} are all equivalent. In each case we would
consider that there are three unknowns---the value $C$ of the call
option and either two state prices or two probabilities. In each case
the state prices or probabilities can be computed from the last two
equations in the set of three equations and then the call value $C$ can
be computed from the first equation in the set. All three sets of
equations produce the same call value.

In fact, as we will see, it will not even be necessary to calculate the
probabilities. The fact that ratios of non-dividend paying asset prices
to the numeraire asset price are martingales will tell us enough about
the probabilities to calculate derivative values without having to
calculate the probabilities themselves.

We conclude this section with another reformulation of the pricing
relations [\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"}. This formulation will generalize more easily to
pricing when there are a continuum of states, the subject of the next
section.
Let $\text{prob}_u$ denote the actual probability of the up state and
$\text{prob}_d$ denote the probability of the down state. These
probabilities are irrelevant for pricing derivatives in the binomial
model, but we will use them to write the pricing relations
[\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} as expectations with respect to the actual
probabilities. To do this, we can define

$$\begin{aligned}
\phi_u &= \frac{\pi_u}{\text{prob}_u}\; ,\\
\phi_d &= \frac{\pi_d}{\text{prob}_d}\;.
end{aligned}$$ Then
[\[binomialC2\]](#binomialC2){reference-type="eqref"
reference="binomialC2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"} can be written as $$\begin{align}
C &= \text{prob}_u\phi_uC_u + \text{prob}_d\phi_dC_d\;,\label{binomialC6}\\
S &= \text{prob}_u\phi_uS_u + \text{prob}_d\phi_dS_d\;,\label{binomialS6}\\
R &= \text{prob}_u\phi_uR_u + \text{prob}_d\phi_dR_d\;.\label{binomialR6}
end{align}$$ The right-hand sides are expectations with respect to the
actual probabilities. For example, the right-hand side of equation
[\[binomialC6\]](#binomialC6){reference-type="eqref"
reference="binomialC6"} is the expectation of the random variable that
equals $\phi_uC_u$ in the up state and $\phi_dC_d$ in the down state.
The risk-neutral probabilities can be calculated from $\phi_u$ and
$\phi_d$ as $p_u=\text{prob}_u\phi_uR_u/R$ and
$p_d=\text{prob}_d\phi_dR_d/R$. Likewise, the probabilities using the
stock as the numeraire can be calculated from $\phi_u$ and $\phi_d$ as
$q_u=\text{prob}_u\phi_uS_u/S$ and $q_d=\text{prob}_d\phi_dS_d/S$. In
the following section, we will assume (which can be shown to be true
under some technical conditions) that relations such as
[\[binomialC6\]](#binomialC6){reference-type="eqref"
reference="binomialC6"}--[\[binomialR6\]](#binomialR6){reference-type="eqref"
reference="binomialR6"} hold in a general (non-binomial) model given the
absence of arbitrage opportunities. We will then show, using definitions
analogous to the definitions of $p_u$, $p_d$, $q_u$, and $q_d$ in this
paragraph, that relations analogous to
[\[binomialC4\]](#binomialC4){reference-type="eqref"
reference="binomialC4"}--[\[binomialR4\]](#binomialR4){reference-type="eqref"
reference="binomialR4"} and
[\[binomialC5\]](#binomialC5){reference-type="eqref"
reference="binomialC5"}--[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} hold.

# Asset Pricing with a Continuum of States

In this section, we will define the concepts of state prices and
probabilities corresponding to different numeraires in a more general
framework than that of the preceding section. This leads to what we will
call the "fundamental pricing equation," namely equation
[\[formula\]](#formula){reference-type="eqref" reference="formula"}.
There are really no new concepts in this section, only a bit more
mathematics.

Consider a non-dividend-paying security having the random price $S(T)$
at date $T$. We call the contingencies that affect the price $S(T)$ the
"states of the world." Our principle regarding state prices developed in
the preceding section can in general be expressed as:[^1] **if there are
no arbitrage opportunities, there exists for each date $T$ a positive
random variable $\phi(T)$ such that the value at date 0 of a
non-dividend-paying security with price $S$ is**

[^1]: We have proven this in the binomial model, but we will not prove
    it in general. As is standard in the literature, we will simply
    adopt it as an assumption. A general proof is in fact difficult and
    requires a definition of "no arbitrage" that is considerably more
    complicated than the simple assumption
    [\[binomialnoarbitrage\]](#binomialnoarbitrage){reference-type="eqref"
    reference="binomialnoarbitrage"} that is sufficient in the binomial
    model.
    
$$\label{continuum1}
S(0) = E[\phi(T)S(T)]\;.$$

Here, $E[\phi(T)S(T)]$ denotes the expectation of the random variable
$\phi(T)S(T)$. The random variable $\phi(T)$ is called the "state price
density."[^1] In a binomial model (or in any model with only a finite
number of states of the world), the concept of an expectation is clear:
it is just a weighted average of outcomes, the weights being the
probabilities. In the binomial model, the right-hand side of equation
[\[binomialS6\]](#binomialS6){reference-type="eqref"
reference="binomialS6"} is the same as the right-hand side of equation
[\[continuum1\]](#continuum1){reference-type="eqref"
reference="continuum1"}.[^2]

[^1]: The term "density" reflects the fact that in each state of the
    world $\phi(T)$ can be interpreted as the state price per unit of
    probability, just as the normal meaning of density is "mass per unit
    of volume."

[^2]: In general the expectation (or mean) of a random variable is an
    intuitive concept, and an intuitive understanding will be sufficient
    for this book, so I will not give a formal definition. It should be
    understood that we are assuming implicitly, whenever necessary, that
    the expectation exists (which is not always the case). In this
    regard, it is useful to note in passing that a product of two random
    variables $XY$ has a finite mean whenever $X$ and $Y$ have finite
    variances.

To convert from state prices to probabilities corresponding to different
numeraires, we follow the same procedure as at the end of the previous
section: we multiply together (i) the probability of the state, (ii) the
value of $\phi(T)$ in the state, and (iii) the gross return of the
numeraire in the state. If there is a continuum of states, then the
actual probability of any individual state will typically be zero, so
this multiplication will produce a zero probability. However, we can
nevertheless "add up" these probabilities to define the probability of
any event $A$, an "event" being a set of states of the world. To do
this, let $1_A$ denote the random variable that takes the value 1 when
$A$ is true and which is zero otherwise. Then the probability of $A$
using $S$ as the numeraire is defined as

$$\label{probSnumeraire}
E\left[1_A\phi(T)\frac{S(T)}{S(0)}\right]\;.$$

This makes sense as a probability because it is nonnegative and because,
if $A$ is the set of all states of the world, then its probability is
$E[\phi(T)S(T)/S(0)]$, which equals one by virtue of
[\[continuum1\]](#continuum1){reference-type="eqref"
reference="continuum1"}. From the definition
[\[probSnumeraire\]](#probSnumeraire){reference-type="eqref"
reference="probSnumeraire"} of the probability of any event $A$, it can
be shown that the expectation of any random variable $X$ using $S$ as
the numeraire is

$$\label{expSnumeraire}
E\left[X\phi(T)\frac{S(T)}{S(0)}\right]\;.$$

The use of the symbol $S$ to denote the price of the numeraire may be
confusing, because $S$ is usually used to denote a stock price. The
numeraire here could be any non-dividend-paying asset. For example, we
can take $S(t)=e^{rt}$, the price of the risk-free asset. The
definition of probabilities as

$$\label{riskneutralprob00}
E[1_A\phi(T)e^{rT}]$$ will be called the "risk-neutral probability
measure" or simply "risk-neutral measure" as before.

Different numeraires lead to different probability measures and hence to
different expectations. To keep this straight, we will use the numeraire
as a superscript on the expectation symbol: for example, $E^S$ will
denote expectation with respect to the probability measure that
corresponds to $S$ being the numeraire. Also, we will use the symbol
$\text{prob}^S(A)$ to denote the probability of an event $A$ when we use
$S$ as the numeraire. So,
[\[probSnumeraire\]](#probSnumeraire){reference-type="eqref"
reference="probSnumeraire"} and
[\[expSnumeraire\]](#expSnumeraire){reference-type="eqref"
reference="expSnumeraire"} will be written as

$$\begin{aligned}
\text{prob}^S(A) &= E\left[1_A\phi(T)\frac{S(T)}{S(0)}\right]\;,\label{probSnumeraire2}\\
\label{expSnumeraire2}
E^S[X] &= E\left[X\phi(T)\frac{S(T)}{S(0)}\right]\;.
end{aligned}$$

Our key result in the preceding section was that the ratio of the price
of any non-dividend paying asset to the price of the numeraire asset is
not expected to change when we use the probability measure corresponding
to the numeraire. We will demonstrate the same result in this more
general model. Recall that $T$ denotes an arbitrary but fixed date at
which we have defined the probabilities using $S$ as the numeraire in
[\[probSnumeraire\]](#probSnumeraire){reference-type="eqref"
reference="probSnumeraire"}. At each date $t<T$, let $E^S_t$ denote the
expectation given information at time $t$ and using $S$ as the numeraire
(we will continue to write the expectation at date 0 without a
subscript; i.e., $E^S$ has the same meaning as $E^S_0$). Let $Y$ denote
the price of another non-dividend-paying asset. We will show that

$$\label{preformula}
\frac{Y(t)}{S(t)} = E^S_t \left[\frac{Y(T)}{S(T)}\right]\;.$$ Thus, the
expected future (date--$T$) value of the ratio $Y/S$ always equals the
current (date--$t$) value when we use $S$ as the numeraire. As discussed
in the preceding section, the mathematical term for a random variable
whose expected future value always equals its current value is
"martingale." Thus, we can express equation
[\[preformula\]](#preformula){reference-type="eqref"
reference="preformula"} as stating that the ratio $Y/S$ is a martingale
when we compute expectations using the probability measure that
corresponds to $S$ being the numeraire.

The usefulness of equation
[\[preformula\]](#preformula){reference-type="eqref"
reference="preformula"} is that it gives us a formula for the asset
price $Y(t)$ at any time $t$---and recall that this formula holds for
every non-dividend paying asset. The formula is obtained from
[\[preformula\]](#preformula){reference-type="eqref"
reference="preformula"} by multiplying through by $S(t)$:

$$\label{formula}
Y(t) = S(t)E^S_t \left[\frac{Y(T)}{S(T)}\right]\;.$$

**We will call equation [\[formula\]](#formula){reference-type="eqref"
reference="formula"} the fundamental pricing formula.** It is at the
heart of modern pricing of derivative securities. It is a present value
relation: the value at time $t$ of the asset is the expectation of its
value $Y(T)$ at time $T$ "discounted" by the (possibly random) factor
$S(t)/S(T)$. To emphasize that the numeraire can be any
non-dividend-paying asset (and not necessarily a stock price, as the
symbol $S$ might suggest), we can write equation
[\[formula\]](#formula){reference-type="eqref" reference="formula"} in
the equivalent form $$\label{formula10}
Y(t) = \text{num}(t)E^\text{num}_t \left[\frac{Y(T)}{\text{num}(T)}\right]\;,\tag{\ref{formula}$'$}$$
where now $\text{num}(t)$ denotes the price of the (non-dividend-paying)
numeraire asset at time $t$.

For example, letting $R(t)$ denote the value $e^{rt}$ of the risk-free
asset and using it as the numeraire, equation
[\[formula\]](#formula){reference-type="eqref" reference="formula"}
becomes $$\label{riskneutralformula}
Y(t) = e^{rt}E^R_t\left[\frac{Y(T)}{e^{rT}}\right] = e^{-r(T-t)}E^R_t [Y(T)]\;,$$
which means that the value $Y(t)$ is the expected value of $Y(T)$
discounted at the risk-free rate for the remaining time $T\!-\!t$, when
the expectation is computed under the risk-neutral probability measure.

We end this section with a proof of
[\[preformula\]](#preformula){reference-type="eqref"
reference="preformula"}, a proof that the reader may skip if
desired.[^1]

[^1]: The proof is due to Harrison and Kreps [@HK]. See also Geman, El
    Karoui and Rochet [@GKR]. We omit here technical assumptions
    regarding the existence of expectations.
    
\begin{petit} Consider any time $t$ and any event $A$ that is distinguishable by time $t$.  Consider the trading strategy of buying one share of the asset with price $Y$ at time $t$ when $A$ has happened and financing this purchase by short selling $Y(t)/S(t)$ shares of the asset with price $S$.  Each share of this asset that you short brings in $S(t)$ dollars, so shorting $Y(t)/S(t)$ shares brings in $Y(t)$ dollars, exactly enough to purchase the desired share of the first asset.  Hold this portfolio until time $T$ and then liquidate it.  Liquidating it will generate 

$$1_A\left(Y(T)-\frac{Y(t)}{S(t)}S(T)\right)$$
dollars. The multiplication by the random variable $1_A$ is because we
only implement this strategy when $A$ occurs (i.e., when $1_A=1$).
Consider the security that pays this number of dollars at time $T$.
Because we obtained it with a trading strategy that required no
investment at time $t$, its price at time 0 must be 0. We already
observed that we can represent the price in terms of state prices, so we
conclude that
$$E \left[\phi(T)1_A\left(Y(T)-\frac{Y(t)}{S(t)}S(T)\right)\right] = 0\;\;.$$
When we divide by $S(0)$, this will still equal zero.  Factoring $S(T)$ outside the parentheses gives
$$E \left[1_A\frac{S(T)}{S(0)}\phi(T)\left(\frac{Y(T)}{S(T)}-\frac{Y(t)}{S(t)}\right)\right] = 0\;\;.$$
We see from the formula
[\[expSnumeraire2\]](#expSnumeraire2){reference-type="eqref"
reference="expSnumeraire2"} for expectations using $S$ as the numeraire
that we can write this as
$$E^S\left[1_A\left(\frac{Y(T)}{S(T)}-\frac{Y(t)}{S(t)}\right)\right]=0\;.$$
This is true for any event $A$ distinguishable at time $t$, so the
expectation of $Y(T)/S(T)-Y(t)/S(t)$ must be zero given any information
at time $t$ when we use $S$ as the numeraire; i.e.,
$$E^S_t\left[\frac{Y(T)}{S(T)}-\frac{Y(t)}{S(t)}\right]=0\; ,$$
or, equivalently
$$E^S_t\left[\frac{Y(T)}{S(T)}\right] = \frac{Y(t)}{S(t)}\;.$$
end{petit}

# Introduction to Option Pricing {#s_introoptions}
A complete development of derivative pricing requires the
continuous-time mathematics to be covered in the next chapter. However,
we can present the basic ideas using the tools already developed.
Consider the problem of pricing a European call option. Let $T$ denote
the maturity of the option and $K$ its strike price, and let $S$ denote
the price of the underlying. We will assume for now that the underlying
does not pay dividends, but we will make no assumptions about the
distribution of its price $S(T)$ at the maturity of the option. Assume
there is a risk-free asset with constant interest rate $r$.

Our convention will be that date 0 denotes the date at which we are attempting to value a derivative. 
The value of the option at maturity is $\max(0,S(T)-K)$. Consider a
contract that pays $S(T)$ at date $T$ when $S(T) \geq K$ and that pays
zero when $S(T)<K$, and consider another contract that pays $K$ at date
$T$ when $S(T)\geq K$ and zero when $S(T)<K$. In
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"}, we will call the first contract a "share
digital" and the second contract a "digital." The call option is
equivalent to a portfolio that is long the first contract and short the
second, because the value of the call at maturity is $S(T)-K$ when
$S(T)\geq K$ and it is zero otherwise. So, we can value the call if we
can value the share digital and the digital. This "splitting up" of
complex payoffs into simpler contracts is a key to analyzing many types
of derivatives.

## Pricing Share Digitals {#pricing-share-digitals .unnumbered}

Consider first the problem of valuing the share digital. Let $Y(t)$
denote its value at each date $t \leq T$. We seek to find $Y(0)$. Our
fundamental pricing formula
[\[formula\]](#formula){reference-type="eqref" reference="formula"}
tells us that
$$Y(0) = \text{num}(0) E^\text{num} \left[\frac{Y(T)}{\text{num}(T)}\right]\; ,$$
for any numeraire with price $\text{num}(t)$. We want to choose the
numeraire to simplify the calculation of the expectation. The
expectation only involves the states of the world in which
$S(T) \geq K$, because $Y(T)=0$ when $S(T)<K$. In the states of the
world in which $S(T) \geq K$, the value of the share digital is $S(T)$.
The calculation of the expectation would be simplified if the value were
a constant when it was nonzero, because, if you are to receive a
constant amount in a certain event, your expected payoff is the constant
times the probability of the event (e.g., the expected payoff of a
gamble that pays \$1 when a fair die rolls a 6 is 1/6). This suggests we
should use the stock as the numeraire, because then we will have
$$\frac{Y(T)}{\text{num}(T)} = \frac{S(T)}{S(T)} = 1$$
when $S(T) \geq K$, implying that
$$E^\text{num} \left[\frac{Y(T)}{\text{num}(T)}\right] = \text{prob}^S\big(S(T)\geq K\big)\; ,$$
where $\text{prob}^S$ denotes the probability using $S$ as the numeraire.  This implies that the value of the share digital is
$$S(0) \times \text{prob}^S\big(S(T)\geq K\big)\;.$$

The remaining question is obviously how to compute the probability. We
will **not** use the formula
[\[probSnumeraire\]](#probSnumeraire){reference-type="eqref"
reference="probSnumeraire"} which expresses the probability in terms of
an expectation involving state prices. To attempt to do so would simply
raise the question of how to compute the state prices. Instead, we use
the fundamental pricing formula again, this time replacing the
derivative value $Y$ with the value of the risk-free asset. This is
exactly analogous to computing the "$q$ probabilities" from
[\[binomialS5\]](#binomialS5){reference-type="eqref"
reference="binomialS5"} and
[\[binomialR5\]](#binomialR5){reference-type="eqref"
reference="binomialR5"} in
Sects. [\[s_oneperiodbinomial\]](#s_oneperiodbinomial){reference-type="ref"
reference="s_oneperiodbinomial"}. Recall that the fundamental formula
holds for any non-dividend-paying asset, so it holds for $R(t)=e^{rt}$,
telling us that the ratio $R(t)/S(t)$ is a martingale when we use $S$ as
the numeraire. In a continuous-time model (at least until we introduce
stochastic volatility) this will give us exactly the information we need
to compute the distribution of $S(T)$ when we use $S$ as the numeraire,
and from the distribution of $S(T)$ we can easily compute
$\text{prob}^S\big(S(T)\geq K\big)$. This calculation will be covered in
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"} for the Black-Scholes model.

## Pricing Digitals {#pricing-digitals .unnumbered}
Now consider the problem of pricing the digital. We will change notation
to let $Y(t)$ denote now the value of the digital at time $t$. Again we
want to compute
$$Y(0) = \text{num}(0) E^\text{num}\left[\frac{Y(T)}{\text{num}(T)}\right]\; ,$$
and again this expectation only involves the states of the world in
which $S(T) \geq K$. In these states of the world, the value of the
digital is already a constant $K$, so we should take the numeraire to
have a constant value at $T$, so that the ratio $Y(T)/\text{num}(T)$
will be constant in the states in which $S(T) \geq K$. This means that
we should take the numeraire to be the risk-free asset. For this
numeraire, the pricing formula is
$$Y(0) = e^{-rT}E^R[Y(T)] = e^{-rT}K\times \text{prob}^R \big(S(T)\geq K\big)\; ,$$
so we need to compute the risk-neutral probability that $S(T) \geq K$.
We will do this by using the fact that $S(t)/R(t) = e^{-rt}S(t)$ is a
martingale under the risk-neutral probability measure. This is analogous
to computing the risk-neutral probabilities from
[\[binomialS4\]](#binomialS4){reference-type="eqref"
reference="binomialS4"} and
[\[binomialR4\]](#binomialR4){reference-type="eqref"
reference="binomialR4"} in
Sects. [\[s_oneperiodbinomial\]](#s_oneperiodbinomial){reference-type="ref"
reference="s_oneperiodbinomial"}.

This calculation will also be covered in
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"} for the Black-Scholes model.


Readers familiar with the Black-Scholes formula may already have surmised that, under the Black-Scholes assumptions, 
$$\text{prob}^S\big(S(T)\geq K\big) = \N(d_1) \quad \text{and} \quad \text{prob}^R\big(S(T)\geq K\big) = \N(d_2)\; ,$$
where $\N$ denotes the cumulative normal distribution function . The
numbers $d_1$ and $d_2$ are different, and hence these are different
probabilities, even though they are both probabilities of the option
finishing in the money ($S(T) \geq K$). They are different probabilities
because they are computed under different numeraires.

## A Remark {#a-remark .unnumbered}

It seems worthwhile here to step back a bit from the calculations and
try to offer some perspectives on the methods developed in this chapter.
The change of numeraire technique probably seems mysterious. Even though
one may agree that it works after following the steps in the chapter,
there is probably a lingering question about why it works. The author's
opinion is that it may be best to regard it simply as a "computational
trick." Fundamentally it works because valuation is linear. Linearity
simply means that the value of a cash flow $X=X_1+X_2$ is the sum of the
values of the cash flows $X_1$ and $X_2$ and the value of the cash flow
$aX$ is $a$ times the value of $X$, for any constant $a$. This linearity
is manifested in the statement that the value of a cash flow is the sum
across states of the world of the state prices multiplied by the size of
the cash flow in each state. The change of numeraire technique exploits
the linearity to further simplify the valuation exercise. There are
other ways the linearity can be used (for example, it produces solvable
partial differential equations) but the particular trick we have
developed in this chapter seems the most useful to the author (and to
others, though perhaps not to everyone). After enough practice with it,
it will seem as natural as other computational tricks one might have
learned.

# An Incomplete Markets Example {#s_incomplete}

In this section, we consider a more difficult valuation problem than the
binomial model and discuss the general implications of this example. We
only need to make the problem slightly more difficult to see the issues.
Consider a "trinomial" model, in which the asset price takes three
possible values: $S_u > S_m > S_d$ ("$m$" for middle, medium, median,
\...). We continue to make the "no arbitrage" assumption
[\[binomialnoarbitrage\]](#binomialnoarbitrage){reference-type="eqref"
reference="binomialnoarbitrage"}. State prices $\pi_u$, $\pi_m$ and
$\pi_m$ must satisfy equations analogous to
[\[binomialS2\]](#binomialS2){reference-type="eqref"
reference="binomialS2"}--[\[binomialR2\]](#binomialR2){reference-type="eqref"
reference="binomialR2"}; specifically,

\begin{subequations}\label{binomialSR10combined}
\begin{align}
S &= \pi_uS_u+\pi_mS_m+\pi_dS_d\;,\label{binomialS10}\\
1 &= \pi_ue^{rT} + \pi_me^{rT} +\pi_d e^{rT}\;.\label{binomialR10}
end{align}end{subequations}
In the binomial case, these equations can be solved for $\pi_u$ and
$\pi_d$, as shown in
[\[binomialstateprices\]](#binomialstateprices){reference-type="eqref"
reference="binomialstateprices"}. However, in the trinomial case, we
have only two equations in three unknowns. Thus, there exist many
solutions.

Given any particular solution $(\pi_u,\pi_m,\pi_d)$ of
[\[binomialSR10combined\]](#binomialSR10combined){reference-type="eqref"
reference="binomialSR10combined"}, we can define the risk-neutral
probabilities $p_u$, $p_m$ and $p_d$ as before---e.g.,
$p_u = \pi_ue^{rT}$. Likewise, we can define the probabilities using
the stock as numeraire. Thus, we can value calls and puts and other
derivative securities. However, the values we obtain will depend on the
particular solution $(\pi_u,\pi_m,\pi_d)$. There are many arbitrage-free
values for a call option, one for each solution of
[\[binomialSR10combined\]](#binomialSR10combined){reference-type="eqref"
reference="binomialSR10combined"}.

The reason that there are many arbitrage-free values for a call (or put)
is that a call cannot be replicated in a trinomial model using the stock
and risk-free asset; we can say equivalently that there is no "delta
hedge" for a call option. Recall that we first found the value of a call
in the binomial model by finding the replicating portfolio and
calculating its cost. A similar analysis is impossible in the trinomial
model. To see this, consider a portfolio of $a$ dollars invested in the
risk free asset and $b$ dollars invested in the stock. The value of the
portfolio at date $T$ will be $ae^{rT} + bS_x/S$, where
$x \in \{u,m,d\}$. To replicate the call, we need $a$ and $b$ to satisfy

$$\begin{align}
ae^{rT} + bS_u/S &= \max(0,S_u-K)\; ,\\
ae^{rT} + bS_m/S &= \max(0,S_m-K)\; ,\\
ae^{rT} + bS_d/S &= \max(0,S_d-K)\;.
end{align}$$ These are three linear equations in the two unknowns $a$
and $b$. For any strike price $K$ between $S_d$ and $S_u$, none of the
equations is redundant, and the system has no solution. When there are
state-contingent claims (such as the call option payoff) that cannot be
replicated by trading in the marketed assets (the stock and risk-free
asset in this case), one says that the market is "incomplete." Thus, the
trinomial model is an example of an incomplete market.

To value derivative securities in this situation, we have to select some
particular solution $(\pi_u,\pi_m,\pi_d)$ of
[\[binomialSR10combined\]](#binomialSR10combined){reference-type="eqref"
reference="binomialSR10combined"} and assume that the market uses that
solution for valuation. Equivalently, we can assume the market uses a
particular set of risk-neutral probabilities $(p_u, p_m, p_d)$. This
type of valuation is often called "equilibrium" valuation, as opposed to
arbitrage valuation, because to give a foundation for our particular
choice of risk-neutral probabilities, we would have to assume something
about the preferences and endowments of investors and the production
possibilities. We will encounter incomplete markets when we consider
stochastic volatility in
Chap. [\[c_stochasticvolatility\]](#c_stochasticvolatility){reference-type="ref"
reference="c_stochasticvolatility"}.

# Problems {#problems .unnumbered}
\addcontentsline{toc}{section}{Problems}
\begin{prob} 
\label{e_binomialcall} 
Create an Excel worksheet in which the user inputs $S$, $S_d$, $S_u$, $K$, $r$ and~$T$.  Check that the no-arbitrage condition eqref{binomialnoarbitrage} is satisfied.  Compute the value of a call option in each of the following ways:

1.  Compute the delta and use [\[C0\]](#C0){reference-type="eqref"
    reference="C0"}.

2.  Compute the state prices and use
    [\[binomialC2\]](#binomialC2){reference-type="eqref"
    reference="binomialC2"}.

3.  Compute the risk-neutral probabilities and use
    [\[binomialC3\]](#binomialC3){reference-type="eqref"
    reference="binomialC3"}.

4.  Compute the probabilities using the stock as numeraire and use
    [\[binomialC5\]](#binomialC5){reference-type="eqref"
    reference="binomialC5"}

Verify that all of these methods produce the same answer.
end{prob}
\begin{prob} 
In a binomial model, a put option is equivalent to $delta_p$ shares of the stock, where $delta_p = (P_u-P_d)/(S_u-S_d)$ (this will be negative, meaning a short position) and some money invested in the risk-free asset.  Derive the amount of money $x$ that should be invested in the risk-free asset to replicate the put option.  The value of the put at date~0 must  be $x+delta_pS$.
end{prob}

\begin{prob}
Using the result of the previous exercise, repeat Problem~\ref{e_binomialcall} for a put option.
end{prob}
\begin{prob} Here is a chance to apply option pricing theory to real life.  Suppose you have a ``significant other'' who would marry you if you ask.  

1.  What type of option do you have on marriage? Can you tell when it is
    in the money?

2.  Under what circumstances should you exercise this option early?

3.  What is the put option in a marriage contract called? (You shouldn't
    need a hint for this one, but, just in case, it is the name of a
    song made popular by Dolly Parton!).

Before anyone might be tempted to take this too literally, it should be
pointed out that, in some "real option" settings, keeping one's options
open has both advantages and disadvantages. Airbus' decision to build a
new larger passenger plan can be seen as the early exercise of a call
option, justified perhaps because by committing to do so it discouraged
Boeing from launching a similar project, both companies presumably
believing that the market is too small for both to enter. Thus, the
exercise of a real option (commitment) can change the environment in
ways that do not arise, or at least we assume not to arise, in financial
markets.
end{prob}