{{< include macros.qmd >}}

# Pricing Digitals {#sec-c_digitals} 

```{python}
#| eval: true
#| echo: false

import plotly
from IPython.display import display, HTML

plotly.offline.init_notebook_mode(connected=True)
display(
    HTML(
        '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
    )
)
```


A complete development of derivative pricing requires the continuous-time mathematics to be covered in the next chapter.  However, we can present the basic ideas using the tools already developed.  Consider the problem of pricing a European call option.  Let $T$ denote the maturity of the option and $K$ its strike price, and let $S$ denote the price of the underlying.  We will assume for now that the underlying does not pay dividends, but we will make no assumptions about the distribution of its price $S(T)$ at the maturity of the option.  Assume there is a risk-free asset with constant interest rate $r$.

Our convention will be that date $0$ denotes the date at which we are attempting to value a derivative. 
The value of the option at maturity is $\max(0,S(T)-K)$.  Consider a contract that pays $S(T)$ at date $T$ when $S(T) \geq K$ and that pays zero when $S(T)<K$, and consider another contract that pays $K$ at date $T$ when $S(T)\geq K$ and zero when $S(T)<K$.  In @sec-c_blackscholes, we will call the first contract a share digital \index{share digital} and the second contract a digital.  \index{digital} The call option is equivalent to a portfolio that is long the first contract and short the second, because the value of the call at maturity is $S(T)-K$ when $S(T)\geq K$ and it is zero otherwise.  So, we can value the call if we can value the share digital and the digital.  This splitting up of complex payoffs into simpler contracts is a key to analyzing many types of derivatives.

### Pricing Share Digitals

Consider first the problem of valuing the share digital.  Let $Y(t)$ denote its value at each date $t \leq T$.   We seek to find $Y(0)$.  Our fundamental pricing @eq-formula tells us that
$$Y(0) = A(0) E^A \left[\frac{Y(T)}{A(T)}\right]\; ,$$
for any numeraire with price $A(t)$.  We want to choose the numeraire to simplify the calculation of the expectation.  The expectation only involves the states of the world in which $S(T) \geq K$, because $Y(T)=0$ when $S(T)<K$.  In the states of the world in which $S(T) \geq K$, the value of the share digital is $S(T)$.  The calculation of the expectation would be simplified if the value were a constant when it was nonzero, because, if you are to receive a constant amount in a certain event, your expected payoff is the constant times the probability of the event (e.g., the expected payoff of a gamble that pays \$1 when a fair die rolls a 6 is 1/6).  This suggests we should use the stock as the numeraire, because then we will have
$$\frac{Y(T)}{A(T)} = \frac{S(T)}{S(T)} = 1$$
when $S(T) \geq K$, implying that
$$E^A \left[\frac{Y(T)}{A(T)}\right] = \text{prob}^S\big(S(T)\geq K\big)\; ,$$
where $\text{prob}^S$ denotes the probability using $S$ as the numeraire.  This implies that the value of the share digital is
$$S(0) \times \text{prob}^S\big(S(T)\geq K\big)\;.$$
The remaining question is obviously how to compute the probability.  We will **not** use @eq-probSnumeraire which expresses the probability in terms of an expectation involving state prices.  To attempt to do so would simply raise the question of how to compute the state prices.  Instead, we use the fundamental pricing formula again, this time replacing the derivative value $Y$ with the value of the risk-free asset.  This is exactly analogous to computing the $q$ probabilities from  @eq-binomialS5 and @eq-binomialR5 in @sec-s_oneperiodbinomial.  Recall that the fundamental formula holds for any dividend-reinvested asset, so it holds for $R(t)=\mathrm{e}^{rt}$, telling us that the ratio $R(t)/S(t)$ is a martingale when we use $S$ as the numeraire.  In a continuous-time model (at least until we introduce stochastic volatility) this will give us exactly the information we need to compute the distribution of $S(T)$ when we use $S$ as the numeraire, and from the distribution of $S(T)$ we can easily compute $\text{prob}^S\big(S(T)\geq K\big)$.  This calculation will be covered in @sec-c_blackscholes for the Black-Scholes model.

### Pricing Digitals
Now consider the problem of pricing the digital.  We will change notation to let $Y(t)$ denote now the value of the digital at time $t$.  Again we want to compute
$$Y(0) = A(0) E^A\left[\frac{Y(T)}{A(T)}\right]\; ,$$
and again this expectation only involves the states of the world in which $S(T) \geq K$.  In these states of the world, the value of the digital is already a constant $K$, so we should take the numeraire to have a constant value at $T$, so that the ratio $Y(T)/A(T)$ will be constant in the states in which $S(T) \geq K$.  This means that we should take the numeraire to be the risk-free asset.  For this numeraire, the pricing formula is
$$Y(0) = \mathrm{e}^{-rT}E^R[Y(T)] = \mathrm{e}^{-rT}K\times \text{prob}^R \big(S(T)\geq K\big)\; ,$$
so we need to compute the risk-neutral probability that $S(T) \geq K$.   We will do this by using the fact that $S(t)/R(t) = \mathrm{e}^{-rt}S(t)$ is a martingale under the risk-neutral probability measure.  This is analogous to computing the risk-neutral probabilities from  @eq-binomialS4 and @eq-binomialR4 in @sec-s_oneperiodbinomial.
This calculation will also be covered in @sec-c_blackscholes for the Black-Scholes model.


Readers familiar with the Black-Scholes formula may already have surmised that, under the Black-Scholes assumptions, 
$$\text{prob}^S\big(S(T)\geq K\big) = \mathrm{N}(d_1) \quad \text{and} \quad \text{prob}^R\big(S(T)\geq K\big) = \mathrm{N}(d_2)\; ,$$ where $\mathrm{N}$ denotes the cumulative normal distribution function .  The numbers $d_1$ and $d_2$ are different, and hence these are different probabilities, even though they are both probabilities of the option finishing in the money ($S(T) \geq K$).  They are different probabilities because they are computed under different numeraires.  


## An Incomplete Markets Example {#sec-s_incomplete}

In this section, we consider a more difficult valuation problem than the binomial model and discuss the general implications of this example.  We only need to make the problem slightly more difficult to see the issues.  Consider a trinomial model, \index{trinomial model} in which the asset price takes three possible values: $S_u > S_m > S_d$ ($m$ for middle, medium, median, ...).   We continue to make the no arbitrage assumption @eq-binomialnoarbitrage.  State prices $\pi_u$, $\pi_m$ and $\pi_m$ must satisfy equations analogous to @eq-binomialS2--@eq-binomialR2; specifically,


$$
S = \pi_uS_u+\pi_mS_m+\pi_dS_d\;,
$$ {#eq-binomialS10}

$$
1 = \pi_u\mathrm{e}^{rT} + \pi_m\mathrm{e}^{rT} +\pi_d \mathrm{e}^{rT}\;.
$$ {#eq-binomialR10}


In the binomial case, these equations can be solved for $\pi_u$ and $\pi_d$, as shown in @eq-binomialstateprices.  However, in the trinomial case, we have only two equations in three unknowns.  Thus, there exist many solutions.

Given any particular solution $(\pi_u,\pi_m,\pi_d)$ of  @eq-binomialS10 - @eq-binomialR10, we can define the risk-neutral probabilities $p_u$, $p_m$ and $p_d$ as before---e.g., $p_u = \pi_u\mathrm{e}^{rT}$.  Likewise, we can define the probabilities using the stock as numeraire.  Thus, we can value calls and puts and other derivative securities.  However, the values we obtain will depend on the particular solution $(\pi_u,\pi_m,\pi_d)$.  There are many arbitrage-free values for a call option, one for each solution of @eq-binomialS10 - @eq-binomialR10.

The reason that there are many arbitrage-free values for a call (or put) is that a call cannot be replicated in a trinomial model using the stock and risk-free asset; we can say equivalently that there is no delta hedge for a call option.  Recall that we first found the value of a call in the binomial model by finding the replicating portfolio and calculating its cost.  A similar analysis is impossible in the trinomial model.  To see this, consider a portfolio of $a$ dollars invested in the risk free asset and $b$ dollars invested in the stock.  The value of the portfolio at date $T$ will be $a\mathrm{e}^{rT} + bS_x/S$, where $x \in \{u,m,d\}$.  To replicate the call, we need $a$ and $b$ to satisfy

$$
a\mathrm{e}^{rT} + bS_u/S = \max(0,S_u-K)\; ,
$$
$$
a\mathrm{e}^{rT} + bS_m/S = \max(0,S_m-K)\; ,
$$
$$
a\mathrm{e}^{rT} + bS_d/S = \max(0,S_d-K)\;.
$$
These are three linear equations in the two unknowns $a$ and $b$.  For any strike price $K$ between $S_d$ and $S_u$, none of the equations is redundant, and the system has no solution.  When there are state-contingent claims (such as the call option payoff) that cannot be replicated by trading in the marketed assets (the stock and risk-free asset in this case), one says that the market is incomplete.  Thus, the trinomial model is an example of an incomplete market. \index{incomplete market}

To value derivative securities in this situation, we have to select some particular solution $(\pi_u,\pi_m,\pi_d)$ of  @eq-binomialS10 - @eq-binomialR10 and assume that the market uses that solution for valuation.  Equivalently, we can assume the market uses a particular set of risk-neutral probabilities $(p_u, p_m, p_d)$.  This type of valuation is often called equilibrium valuation, \index{equilibrium pricing} as opposed to arbitrage valuation, because to give a foundation for our particular choice of risk-neutral probabilities, we would have to assume something about the preferences and endowments of investors and the production possibilities.  We will encounter incomplete markets when we consider stochastic volatility in @sec-c_stochasticvolatility.

