# Valuing Derivatives in the Extended Vasicek Model {#c_vasicek}
\chaptermark{The Extended Vasicek Model}
In the preceding chapter, we presented models for valuing swaptions, caps, and floors based on assumptions that certain forward rates have constant volatilities.  As noted, the assumptions used to value swaptions on the one hand and caps and floors on the other are inconsistent.  Because the values of fixed-income derivatives are derived from the yield curve, one can obtain a consistent model by developing a model of how the yield curve will evolve over time.  In this chapter, we will give a fairly full account of one popular and relatively simple model.  The next chapter contains much briefer descriptions of other models.

We will begin by describing the basic Vasicek model.  The extended Vasicek model (of which there are several versions) includes time-dependent parameters, so that it can be fit to the yield curve at the time it is used and possibly also to other market variables, such as cap prices or yield volatilities.  


# The Short Rate and Discount Bond Prices {#s_vasicek1}

An assumption of the Vasicek model and related models discussed in the
next chapter is that there is an instantaneously risk-free rate. Letting
$r(s)$ denote this rate at date $s$, the meaning of this assumption, as
discussed in
Sect. [\[s_continuouscompounding\]](#s_continuouscompounding){reference-type="ref"
reference="s_continuouscompounding"}, is that there is an asset with
price process
$$R(t) = \exp\left(\int_0^t r(s)\,\D s\right)\; .$$
The instantaneous rate of return on this asset is
$$\frac{\D R(t)}{R(t)} = r(t)\,\D t\; .$$
There is no random term (of the form $\sigma\,\D B$) in this rate of
return; thus, we view the return as known at date $t$, whence the name
"instantaneously risk-free." If there were another instantaneously
risk-free asset with rate of return $\hat{r}(t)$ which differed from
$r(t)$ on a non-negligible set of dates and states of the world, there
would be an arbitrage opportunity. Hence, we will assume there is a
unique instantaneously risk-free rate. We will call this rate the "short
rate." The interpretation of the price $R(t)$ is that it is the amount
that would be accumulated by date $t$, beginning with \$1 at date 0 and
continuously rolling over the investment in the instantaneously
risk-free asset. It is conceptually similar to the net asset value of a
money market fund, so $R$ is sometimes called the price of a money
market account. We will also call it an "accumulation factor."

The probability measure associated with $R$ being the numeraire is
called the risk-neutral measure, just as when the short rate is
constant. Under the risk-neutral measure, the price $P(t,u)$ at date $t$
of a discount bond maturing at $u$ must be
\begin{equation}\label{basicbondprice}
P(t,u) = R(t) E^R_t \left[\frac{1}{R(u)}\right] = E^R_t \left[ \exp\left(-\int_t^u r(s)\,\D s\right)\right]\;,
\end{equation}
the first equality being a result of our fundamental pricing formula
[\[formula\]](#formula){reference-type="eqref" reference="formula"} and
the fact that the discount bond pays \$1 at maturity and the second
equality following from the definition of $R$. Thus, a model for the
evolution of the short rate under the risk-neutral measure implies a
model for discount bond prices and hence the yield curve.

# The Vasicek Model {#s_vasicek}

In the basic Vasicek \cite{Vasicek} model, \index{Vasicek model}it is assumed that
\begin{equation}\label{vasicek}
\D r(t) = \kappa\big[\theta-r(t)\big]\,\D t+\sigma\,\D B(t)
\end{equation}
for constants $\kappa\geq 0$, $\theta$, and $\sigma$, where $B$ is a
Brownian motion under the risk-neutral measure. In this model, $\theta$
is the long-run mean of the short rate process and $\kappa$ is
interpreted as the rate of mean reversion. When $r(t) >\theta$, the
drift term will be negative and push $r$ down towards $\theta$.
Likewise, when $r(t) <\theta$, the drift term will be positive and push
$r$ up towards $\theta$. The rate at which $r$ drifts towards $\theta$
is obviously determined by $\kappa$. **We are going to depart from our
convention and call $\sigma$ the "volatility" of the short rate** even
though $\sigma^2\,\D t$ is the instantaneous variance of $\D r$ rather
than $\D r/r$.

The short rate is normally distributed in the Vasicek model.  Given information at date~$t$---i.e., knowledge of $r(t)$---then, if $\kappa>0$,
 the rate $r(s)$ for $s>t$ is normally distributed with mean\footnote{These results on the mean and variance of $r(s)$ follow from the solution \eqref{vasicek_sol} of the Vasicek equation \eqref{vasicek}.}
\begin{equation}\label{vasicekmean}
\theta + \E^{-\!\kappa (s-t)}\big[r(t)-\theta\big]
\end{equation}
and variance
\begin{equation}\label{vasicekvariance}
\frac{\sigma^2\left(1-\E^{-2\kappa(s-t)}\right)}{2\kappa}\;.
\end{equation}
For any $r(t)$, the mean converges to $\theta$ at long horizons (i.e.,
as $s \rightarrow \infty$), justifying the interpretation of $\theta$ as
the long run mean. In fact, the mean converges exponentially to $\theta$
at rate $\kappa$. The variance at long horizons is $\sigma^2/2\kappa$.
On the other hand, if $\kappa=0$, then the short rate is a Brownian
motion with volatility $\sigma$. The mean of $r(s)$ is $r(t)$ for $s>t$,
and the variance of $r(s)$ is $(s-t)\sigma^2$. Thus, the uncertainty at
long horizons, as measured by the variance, is unbounded when
$\kappa=0$. Whether $\kappa$ is positive or not, an implication of the
normal distribution is that there is a positive probability of the short
rate $r(s)$ being negative at any date $s>t$, which should not be the
case for (nominal) interest rates. However, the probability of negative
rates over any given horizon will be small if the variance is
sufficiently small. From the formula
[\[vasicekvariance\]](#vasicekvariance){reference-type="eqref"
reference="vasicekvariance"}, we see that, when $\kappa>0$, the variance
will be small if either the volatility $\sigma$ is small or the rate of
mean reversion $\kappa$ is large.

These facts about the distribution of the short rate demonstrate the
importance of assuming mean reversion ($\kappa>0$). If $\kappa=0$, the
short rate (because it is a Brownian motion) has the property that for
any real number $K$, with probability one there will be some date $s>t$
such that $r(s)>K$, irrespective of the starting position $r(t)$.
Likewise, there will be some date $s'>t$ such that $r(s')<-K$. Thus, the
short rate "wanders" off in both directions in an unbounded way. This
property may be reasonable for the logarithm of a stock price, because a
stock price may become arbitrarily high or arbitrarily close to zero
(implying that the logarithm is unbounded both above and below).
However, it is not reasonable for an interest rate, which should exhibit
more stability. The assumption of mean reversion ($\kappa>0$) provides
this stability, guaranteeing that the uncertainty at long horizons is
bounded and that on average the short rate will converge back to a
finite long-run mean. Nevertheless, we will give results in this chapter
for the case $\kappa=0$, because this is a particularly simple model and
because it is the basic building block for what is called the
"continuous-time Ho-Lee model." The actual Ho-Lee model, which is a
binomial model, will be discussed in the following chapter.

The relative simplicity of the Vasicek model stems from the fact that
under assumption [\[vasicek\]](#vasicek){reference-type="eqref"
reference="vasicek"} the accumulation factor $R$ is lognormally
distributed. Specifically, at any date $t$ and given any date $u>t$, the
random variable
$$\int_t^u r(s)\,\D s$$
is normally distributed.  Its mean and variance depend on the parameters $\kappa$, $\theta$, and $\sigma$ and the length of the time interval $u-t$.  The mean also depends on the short rate $r(t)$ at date~$t$.  Therefore, the discount bond price depends on the same things.  

We will now present an explicit formula for discount bond prices, based
on the fundamental formula
[\[basicbondprice\]](#basicbondprice){reference-type="eqref"
reference="basicbondprice"}.
By taking the Itô differential of $r(s)$ in the following, one can verify that it is the solution of the Vasicek model \eqref{vasicek}:\footnote{Equation \eqref{vasicek_sol} implies the distributional properties of $r(s)$ stated earlier.
The integral $\int_t^s \E^{-\!\kappa (s-y)} \,\D B(y)$ is normally distributed with mean zero; therefore equation~\eqref{vasicek_sol} shows that the mean of $r(s)$ in the case $\kappa>0$ is as given in \eqref{vasicekmean}.  The variance is computed, following the rules in Chap.~\ref{c_continuoustime}, as $\int_t^s \E^{-2\kappa (s-y)}\,\D y$, which simplifies to the formula given in \eqref{vasicekvariance}.}
\begin{equation}\label{vasicek_sol}
r(s) =  \theta - \E^{-\!\kappa (s-t)}\big[\theta-r(t)\big]+ \sigma 
\int_t^s \E^{-\!\kappa (s-y)} \,\D B(y).
\end{equation}
If $\kappa=0$, this simplifies to
\begin{equation}\label{vasicek_sol2}
r(s) = r(t) + \sigma\int_t^s\D B(y)= r(t) + \sigma[B(s)-B(t)]\;. \tag{\ref{vasicek_sol}$'$}
\end{equation}
These equations imply the following.
\mybox{
In the Vasicek model, consider dates $t<u$ and define $\tau=u-t$.  Given the short rate $r(t)$ at date $t$,
the discount bond price has the form
\begin{subequations}\label{vasicekbondcombined}
\begin{equation}\label{vasicekbond}
P(t,u) = \exp\left(-a(\tau)-b(\tau)r(t)\right)\;, 
\end{equation}
where, if $\kappa=0$,
\begin{align}
a(\tau)&=-\sigma^2\tau^3/6\;,\label{vasicek_ak0}\\
b(\tau) &= \tau\;,\label{vasicek_bk0}
\intertext{and, if $\kappa>0$,}
a(\tau)&= \theta\tau-\frac{\theta}{\kappa}\left(1-\E^{-\kappa\tau}\right)-\frac{\sigma^2}{4\kappa^3}\left(2\kappa\tau -\E^{-2\kappa\tau}+4\E^{-\kappa\tau}-3\right)\;,\label{vasicek_a}\tag{\ref{vasicek_ak0}$'$}\\
b(\tau)&= \frac{1}{\kappa}\left(1-\E^{-\kappa\tau}\right)\;.\label{vasicek_b}\tag{\ref{vasicek_bk0}$'$}
\end{align}
\end{subequations}
}

\begin{petit}
We will end this section with a proof of \eqref{vasicekbondcombined} in the case $\kappa=0$.  The formula for $\kappa>0$ can be established by the same reasoning, the calculations being only slightly more complicated.
From  \eqref{vasicek_sol2}, we have
\begin{align*}
\int_t^u r(s)\,\D s & = \int_t^u \left[r(t)+\sigma \int_t^s \D B(y)\right]\,\D s\\
&=\tau\, r(t)+\sigma \int_t^u \left\{\int_t^s \D B(y) \right\} \,\D s\; .
\end{align*}
We can change the order of integration in the double integral above to obtain
\begin{align*}
\int_t^u \left\{\int_t^s \D B(y) \right\} \,\D s &=\int_t^u \left\{\int_y^u \D s\,\right\} \D B(y)\\
&=\int_t^u (u-y)\,\D B(y)\;.
\end{align*}
Given the information at date $t$, this is a normally distributed random variable with mean zero and variance equal to
$$\int_t^u (u-y)^2\,\D y = \frac{\tau^3}{3}\; .$$
Therefore, 
$\int_t^u r(s)\,\D s$
is normally distributed with mean  $\tau\, r(t)$ and variance $\sigma^2\tau^3/3$.  We now use the fact that if $x$ is normally distributed with mean $\mu$ and variance $\sigma^2$, then the mean of $\E^x$ is $\E^{\mu+\sigma/2}$.  Substituting this into  \eqref{basicbondprice} gives the result.
\end{petit}

# Estimating the Vasicek Model

One way to choose the parameters $\kappa$, $\theta$ and $\sigma$ of the
Vasicek model is to imply them from market bond prices and the formula
[\[vasicekbondcombined\]](#vasicekbondcombined){reference-type="eqref"
reference="vasicekbondcombined"}. This is analogous to implying the
volatility of a stock from market option prices and the Black-Scholes
formula. This can also be viewed as an alternative to fitting a cubic
spline, as discussed in
Chap. [\[c_fixedincomeconcepts\]](#c_fixedincomeconcepts){reference-type="ref"
reference="c_fixedincomeconcepts"}. Rather than selecting the parameters
of the cubic spline to provide the best approximation to market bond
prices, one can choose the Vasicek parameters $\kappa$, $\theta$ and
$\sigma$. The formula
[\[basicbondprice\]](#basicbondprice){reference-type="eqref"
reference="basicbondprice"} will then give prices of discount bonds of
all maturities.[^1]

[^1]: Of course, the fit to market bond prices will typically be poorer
    with fewer parameters; therefore, the Vasicek yield curve will
    typically not fit as well as a cubic spline.

An alternative procedure is to estimate the parameters from historical
data on the short rate. The short rate is a theoretical construct and
one must choose some proxy to use for empirical work, for example, the
Federal Funds rate, or the yield of a short-term (typically one-month or
three-month) Treasury bill. One also needs to use a proxy for the short
rate when implying the parameters from market bond prices as described
in the previous paragraph (or one could view the short rate as one of
the parameters to be implied).

An issue that arises when estimating the model from historical data is that the Vasicek equation \eqref{vasicek} characterizes the evolution of the short rate relative to a Brownian motion under the risk-neutral measure, whereas the historical data is governed by the actual measure.  Vasicek \cite{Vasicek} actually assumed that  \eqref{vasicek} holds relative to a Brownian motion under the actual probability measure.  We will write his assumption as
\begin{equation}\label{vasicekactual}
\D r(t) = \kappa^*[\theta^*-r(t)]\,\D t + \sigma^*\,\D B^*(t)\;,
\end{equation}
where $\kappa^*$, $\theta^*$, $\sigma^*$ are constants and $B^*$ is a
Brownian motion under the actual probability measure.[^1] Vasicek then
assumed a constant "market price of risk" $\lambda$ and deduced that[^2]

[^1]: Note that our notation is the reverse of what many people use:
    here $B$ denotes a Brownian motion under the risk-neutral measure
    (under which we will primarily operate) and $B^*$ denotes a Brownian
    motion under the actual measure.

[^2]: The price of risk is the new drift of $B^*$ when we change from
    the actual measure to the risk-neutral measure. See
    Appendix [\[a_girsanov\]](#a_girsanov){reference-type="ref"
    reference="a_girsanov"}.
    \begin{equation}\label{vasicekpriceofrisk}
\D r(t) = \kappa^*[\theta^*-r(t)]\,\D t + \sigma^*\lambda\,\D t + \sigma^*\,\D B(t)\;, \tag{\ref{vasicek}$'$}
\end{equation}
where $B$ is a Brownian motion under the risk-neutral measure. This is
the same as [\[vasicek\]](#vasicek){reference-type="eqref"
reference="vasicek"} when we define $\kappa=\kappa^*$,
$\sigma=\sigma^*$, and $\theta = \theta^*+\sigma^*\lambda/\kappa^*$.
This means that the mean-reversion and volatility parameters are the
same under the actual and risk-neutral measures, whereas the long-run
mean parameters $\theta$ and $\theta^*$ are related via the market price
of risk. Thus, to estimate $\kappa$, $\theta$ and $\sigma$ in
[\[vasicek\]](#vasicek){reference-type="eqref" reference="vasicek"}, we
could estimate $\kappa^*=\kappa$, $\sigma^*=\sigma$, and $\theta^*$ from
[\[vasicekactual\]](#vasicekactual){reference-type="eqref"
reference="vasicekactual"} and historical data and then choose $\theta$
to best fit market bond prices.

We can estimate the parameters of
[\[vasicekactual\]](#vasicekactual){reference-type="eqref"
reference="vasicekactual"} by linear regression. Suppose we have data on
a proxy for the short rate at dates $t_0, t_1, \ldots, t_N$, with
$t_{i}-t_{i-1}=\varDelta t$ for each $i$. The solution
[\[vasicek_sol\]](#vasicek_sol){reference-type="eqref"
reference="vasicek_sol"} of the Vasicek equation
[\[vasicek\]](#vasicek){reference-type="eqref" reference="vasicek"} for
the short rate, adapted to
[\[vasicekactual\]](#vasicekactual){reference-type="eqref"
reference="vasicekactual"}, implies the following equation for the
changes in the short rate:

\begin{multline*}
r(t_i) - r(t_{i-1}) = \left(1- \E^{-\!\kappa^* \varDelta t}\right)\theta^* -\left(1- \E^{-\!\kappa^* \varDelta t}\right)r(t_{i-1}) \\+ \sigma^* 
\int_{t_{i-1}}^{t_i} \E^{-\!\kappa^* (t_i-a)} \,\D B^*(a)\; .
\end{multline*}
We can write this as
$$r(t_i) - r(t_{i-1}) = a + b\,r(t_{i-1}) + \varepsilon$$
where $\varepsilon$ is a normally distributed random variable, independent of $r(t_{i-1})$, with mean zero and variance
$$\sigma^{*2} 
\int_{t_{i-1}}^{t_i} \E^{-2\kappa^* (t_i-a)}\,\D a = \frac{\sigma^{*2}\left(1-\E^{-2\kappa^*\varDelta t}\right)}{2\kappa^*}\; .$$
We can estimate $a$, $b$ and the variance of $\varepsilon$ by linear regression and then obtain $\kappa^*$, $\theta^*$ and $\sigma^*$ from the equations
\begin{align*}
a& = \left(1- \E^{-\!\kappa^* \varDelta t}\right)\theta^*\; ,\\
b&= -\left(1- \E^{-\!\kappa^* \varDelta t}\right)\; ,\\
\text{var}(\varepsilon) &= \frac{\sigma^{*2}\left(1-\E^{-2\kappa^*\varDelta t}\right)}{2\kappa^*}\;.
\end{align*}

# Hedging in the Vasicek Model {#s_vasicekhedging}

Because the Brownian motion driving the short rate also drives all the
discount bond prices, the bond prices are (instantaneously) perfectly
correlated in the Vasicek model (and also in the extensions we will
consider next). This is true in any model in which there is a single
factor, such as the short rate, that determines all bond prices. The
volatilities of the bond returns determine the hedge ratios for hedging
one bond with another.

Equation [\[vasicekbond\]](#vasicekbond){reference-type="eqref"
reference="vasicekbond"} and Itô's formula (the rule that, if $P=\E^X$,
then $\D P/P = dX + (dX)^2/2$) imply that for any date $t$ and any fixed
maturity date $u>t$, we have
\begin{equation}\label{vasicekbondreturn}
\frac{\D P(t,u)}{P(t,u)} = r(t)\,\D t - \sigma b(u\!-\!t)\,\D B(t)\;.
\end{equation}
Because $B$ is a Brownian motion under the risk-neutral measure, this
equation implies that the expected rate of return on a discount bond
under the risk-neutral measure is the short rate. This is not a
surprise, because it is true for every asset under the risk-neutral
measure. What is important in this equation is that the volatility is a
non-random function of the date $t$, given the maturity $u$.

As an example, consider hedging a short two-year bond with a long position in a one-year bond at some date~$t$.  
According to the formula
[\[vasicekbondreturn\]](#vasicekbondreturn){reference-type="eqref"
reference="vasicekbondreturn"}, the change in the value of the short
position in the two-year bond will be
$$-P(t,t+2)r(t)\,\D t-P(t,t+2)\sigma b(2)\,\D B(t)$$
Suppose we hold $x$ units of the one-year bond as a hedge and borrow 
$$xP(t,t+1)-P(t,t+2)$$
dollars at the instantaneously risk-free rate to finance the hedge.  Then the change in the value of the portfolio will be
\begin{multline*}
xP(t,t+1)r(t)\,\D t+xP(t,t+1)\sigma b(1)\,\D B(t) \\- P(t,t+2)r(t)\,\D t-P(t,t+2)\sigma b(2)\,\D B(t) \\- [xP(t,t+1)-P(t,t+2)]\,r\D t \\= xP(t,t+1)\sigma b(1) \,\D B(t) -P(t,t+2)\sigma b(2)\,\D B(t)\;,
\end{multline*}
so a perfect hedge is obtained by setting
$$x = \frac{b(2)P(t,t+2)}{b(1)P(t,t+1)}\; .$$
In the case $\kappa=0$, this simplifies to $x=2P(t,t+2)/P(t,t+1)$, which means that the dollar value $xP(t,t+1)$ of the holding in the one-year bond is 
  twice the dollar value of the short position in the two-year bond.  One holds twice as much of the one-year bond, because it is half as volatile as the two-year bond in this model.

By this same reasoning, one can compute a perfect hedge for any discount bond by using another discount bond of any maturity.  In fact, one can hedge any term structure derivative in this model by investing the right amount in a bond of any maturity.  This is clearly overly simplistic, and such arbitrary hedges would not be used in practice.

There is a close connection between hedging in this model and duration hedging, \index{duration hedging}as discussed in Sect.~\ref{s_duration}.  To see this, consider a coupon
bond that at date $t$ has remaining cash flows $C_1, ..., C_n$ at dates $t+\tau_1 < \cdots < t+\tau_n$ and price $P(t)$.  Its price should satisfy
$$
P(t) = \sum_{j=1}^n C_jP(t,t+\tau_j)\;.
$$
In the Vasicek model, the random part of the change in the price of the coupon bond is
$$-\sigma\left(\sum_{j=1}^n b(\tau_j)C_jP(t,t+\tau_j)\right)\,\D B(t) \; ,$$
and the random part of the return is
\begin{equation}\label{vasicekcouponreturn}
-\sigma\left(\sum_{j=1}^n \frac{b(\tau_j)C_jP(t,t+\tau_j)}{P(t)}\right)\,\D B(t)\;.
\end{equation}

Consider the case $\kappa=0$.  Then $b(\tau_j)=\tau_j$, so the random part of the return of the coupon bond  is
$$-\sigma\left(\sum_{j=1}^n \frac{\tau_jC_jP(t,t+\tau_j)}{P(t)}\right)\,\D B(t)\; .$$
The factor in parentheses is Duration$'$ defined in
[\[newduration100\]](#newduration100){reference-type="eqref"
reference="newduration100"}. Denoting it now as $D(t)$ and recognizing
that the expected rate of return of the bond must be the short rate, we
have, in the Vasicek model with $\kappa=0$,
$$\frac{\D P(t)}{P(t)} = r(t)\,\D t - \sigma D(t)\,\D B(t)\; .$$
It follows that in this model one can hedge any fixed-income liability
by holding enough of any coupon bond such that the dollar value
multiplied by its duration equals the dollar value of the liability
multiplied by its duration. In
Sect. [\[s_duration\]](#s_duration){reference-type="ref"
reference="s_duration"}, we noted that duration matching works for
parallel shifts in the yield curve. Later, we will see that in the
Vasicek model with $\kappa=0$ only parallel shifts in the yield curve
are possible. Therefore, it should not be surprising that duration
matching works in this model.

In the case $\kappa>0$, one can interpret the volatility of the coupon
bond similarly. The analogue to duration for this model is the weighted
average of the function $b(\tau_j)$ of the times to maturity, as the
formula
[\[vasicekcouponreturn\]](#vasicekcouponreturn){reference-type="eqref"
reference="vasicekcouponreturn"} shows. The weights again are the
fractions of the bond value that each cash flow contributes.


# Extensions of the Vasicek Model

To fit the model to current market conditions at the time the model is
being used, the parameters $\kappa$, $\theta$ and $\sigma$ can be taken
to be time-dependent. The model with time-dependent parameters is
studied in Hull and White [@HW] and is usually called the Hull-White
model. It is convenient to denote by $\theta(t)$ the time-dependent
function replacing the constant $\kappa\theta$ in the definition of the
Vasicek model [\[vasicek\]](#vasicek){reference-type="eqref"
reference="vasicek"}; that is, we redefine as $\theta$ what was
previously $\kappa\theta$.[^1] As usual, we will let date 0 be the date
at which we are using the model. The model is then, for $t>0$,

[^1]: Some authors (including Hull and White) do not make this
    definition---i.e., they denote by $\kappa(t)\theta(t)$ what we are
    denoting by $\theta(t)$---so be careful when combining results from
    different sources.
    \begin{equation}\label{hw500}
\D r(t) = \theta(t)\,\D t - \kappa(t)r(t)\,\D t + \sigma(t)\,\D B(t)\;.
\end{equation}

We will focus on the simplest case, in which $\kappa$ and $\sigma$ are
constants, deferring discussion of the general case to the last section
of this chapter. The general case is quite similar, with the formulas
being only slightly more complicated.
So, we assume now that
\begin{equation}\label{hw5000}
\D r(t) = \theta(t)\,\D t - \kappa r(t)\,\D t + \sigma \,\D B(t)\;. \tag{\ref{hw500}$'$}
\end{equation}
for a non-random function $\theta$.  
We will call this model with $\kappa>0$ the Hull-White model.  The model with 
$\kappa=0$ (i.e., in the absence of mean reversion) is called the
continuous-time Ho-Lee model. We will refer to the general case
[\[hw500\]](#hw500){reference-type="eqref" reference="hw500"} as the
general Hull-White model, and we will discuss it in
Sect. [\[s_generalHW\]](#s_generalHW){reference-type="ref"
reference="s_generalHW"}.
  In the Hull-White model, we can interpret $\theta(t)/\kappa$ as a time-varying long-run mean of the short rate process, because we have
$$\D r(t) = \kappa\left[ \frac{\theta(t)}{\kappa} - r(t)\right]\,\D t + \sigma\,\D B(t)\; .$$

\vfil\eject
One can show by the following by directly differentiating.
\mybox{
In the Hull-White model,
\begin{subequations}\label{vasicek_solcombined}
\begin{equation}\label{vasicekextension_sol}
r(s) = \phi(s) + \hat{r}(s)\;,
\end{equation}
where 
\label{vasicekextension_solcombined}
\begin{equation}\label{phi102}
\phi(s) =  \int_0^s\E^{-\kappa(s-y)}\theta(y)\,\D y\;,
\end{equation}
and
\begin{equation}\label{rhat102}
\hat{r}(s) = \E^{-\kappa s}r(0)+\sigma\int_0^s\E^{-\kappa(s-y)}\,\D B(y)\;.
\end{equation}
When $\kappa=0$ (the continuous-time Ho-Lee model), these formulas simplify to
\begin{equation}\label{phi103}
\phi(s) =  \int_0^s\theta(y)\,\D y\;. \tag{\ref{phi102}$'$}
\end{equation}
and
\begin{equation}\label{rhat103}
\hat{r}(s) = r(0)+\sigma B(s)\;. \tag{\ref{rhat102}$'$}
\end{equation}
\end{subequations}
}
Note that \eqref{rhat102} and \eqref{rhat103} imply
\begin{equation}\label{rhat10001}
\D\hat{r}(t) = -\kappa \hat{r}(t)\,\D t + \sigma\,\D B(t)\; ,
\end{equation}
where $\kappa=0$ for \eqref{rhat103}.  Thus, $\hat{r}$ is a Vasicek short-rate process having a long-run mean of zero.

The virtue of the expression for $r$ given in
[\[vasicekextension_solcombined\]](#vasicekextension_solcombined){reference-type="eqref"
reference="vasicekextension_solcombined"} is that the basic bond pricing
equation [\[basicbondprice\]](#basicbondprice){reference-type="eqref"
reference="basicbondprice"} now gives us
\begin{align}
P(t,u) &= E^R_t \left[ \exp\left(-\int_t^u r(s)\,\D s\right)\right]\notag\\
&= E^R_t \left[ \exp\left(-\int_t^u \phi(s) + \hat{r}(s)\,\D s\right)\right]\notag\\
&= E^R_t \left[ \exp\left(-\int_t^u \phi(s)\,\D s\right)\exp\left(-\int_t^u  \hat{r}(s)\,\D s\right)\right]\notag\\
&= \exp\left(-\int_t^u \phi(s)\,\D s\right)E^R_t \left[ \exp\left(-\int_t^u \hat{r}(s)\,\D s\right)\right]\;.\label{vasicekpullsout}
\end{align}
Thus, the non-random part $\phi(s)$ of the short-rate process "pulls
out" of the expectation in the pricing formula. Furthermore, we have
already calculated the expectation in
[\[vasicekpullsout\]](#vasicekpullsout){reference-type="eqref"
reference="vasicekpullsout"} because it is the discount bond price in
the Vasicek model with a long-run mean of zero. This yields the
following.

\mybox{Consider dates $t<u$ and define $\tau=u-t$.  The price at date $t$ of a discount bond maturing at date $u$ in the extended Vasicek model is
\begin{subequations}\label{extendedvasicekbondcombined}
\begin{equation}\label{extendedvasicekbond}
P(t,u) = \exp\left(-\int_t^u \phi(s)\,\D s-a(\tau)-b(\tau)\hat{r}(t)\right)\;,
\end{equation}
where, in the continuous-time Ho-Lee model,
\begin{align}
a(\tau)&=-\sigma^2\tau^3/6\;,\label{extendedvasicekbond_ak0}\\
b(\tau) &= \tau\;,\label{extendedvasicekbond_bk0}
\intertext{and, in the Hull-White model,}
a(\tau)&= -\frac{\sigma^2}{4\kappa^3}\left(2\kappa\tau -\E^{-2\kappa\tau}+4\E^{-\kappa\tau}-3\right)\;,\label{extendedvasicek_a}\tag{\ref{extendedvasicekbond_ak0}$'$}\\
b(\tau)&= \frac{1}{\kappa}\left(1-\E^{-\kappa\tau}\right)\;.\label{extendedvasicek_b}\tag{\ref{extendedvasicekbond_bk0}$'$}
\end{align}
\end{subequations}
}


Using the fact that the expected rate of return on a discount bond must
be the short rate under the risk-neutral measure, we obtain from
[\[extendedvasicekbond\]](#extendedvasicekbond){reference-type="eqref"
reference="extendedvasicekbond"} and
[\[rhat10001\]](#rhat10001){reference-type="eqref"
reference="rhat10001"} that, for each fixed maturity date $u$,

\begin{equation}\label{extendedvasicekbondreturn}
\frac{\D P(t,u)}{P(t,u)} = r(t)\,\D t - \sigma b(\tau)\,\D B(t)\;.
\end{equation}
Thus, the volatilities are determined by the function $b$, just as in
the basic Vasicek model. The computation of hedge ratios is therefore
analogous to the computations presented in
Sect. [\[s_vasicekhedging\]](#s_vasicekhedging){reference-type="ref"
reference="s_vasicekhedging"} for the basic Vasicek model. In fact, the
volatilities of discount bond returns in the Hull-White model are the
same as in the Vasicek model with $\kappa>0$, and the volatilities in
the continuous-time Ho-Lee model are the same as in the Vasicek model
with $\kappa=0$.


# Fitting Discount Bond Prices and Forward Rates {#s_vasicek_fitting}

It is simple to fit the Hull-White model and continuous-time Ho-Lee
model to market discount bond prices by choosing the function $\phi$. We
will use the superscript "mkt" to denote market prices. Letting date 0
denote the date at which we are fitting the model, we want to have
$$P^{\text{mkt}}(0,u) = P(0,u)$$
for all maturities $u$, where $P(0,u)$ denotes the model prices given in
[\[extendedvasicekbond\]](#extendedvasicekbond){reference-type="eqref"
reference="extendedvasicekbond"} as
$$P(0,u) = \exp\left(-\int_0^u \phi(s)\,\D s-a(u)-b(u)r(0)\right)\; .$$
The functions $a$ and $b$ depend on $\kappa$ and $\sigma$, but we regard them now as having already been chosen.  Therefore, to match the model prices to market prices, we simply have to set
\begin{equation}\label{vasicekcalibration101}
\exp\left(-\int_0^u \phi(s)\right) = \exp\left(a(u)+b(u)r(0)\right)P^{\text{mkt}}(0,u)\;.
\end{equation}

Usually we will only need to solve
[\[vasicekcalibration101\]](#vasicekcalibration101){reference-type="eqref"
reference="vasicekcalibration101"} for a finite number of maturities $u$
in order to calibrate the model sufficiently. We will illustrate this in
the analysis of coupon bond options in
Sect. [\[s_vasicek_swaptions\]](#s_vasicek_swaptions){reference-type="ref"
reference="s_vasicek_swaptions"}. However, the equation can be solved in
principle for each maturity $u$ as follows: take the natural logarithm
of both sides, multiply by minus 1, and differentiate with respect to
$u$ to obtain
\begin{equation}\label{extendedvasicekforwards1}
\phi(u) = -\frac{\partial a(u)}{\partial u} - \frac{\partial b(u)}{\partial u}r(0) - \frac{ \partial \log P^{\text{mkt}}(0,u)}{\partial u}\;.
\end{equation}


Equation \eqref{extendedvasicekforwards1} gives the solution of the model for $\phi(u)$, and it also has an important interpretation.  We can obviously rearrange it as
\begin{equation}\label{extendedvasicekforwards}
\phi(u) +\frac{\partial a(u)}{\partial u} + \frac{\partial b(u)}{\partial u}r(0) = -\frac{ \partial \log P^{\text{mkt}}(0,u)}{\partial u}\;. \tag{\ref{extendedvasicekforwards1}$'$}
\end{equation}
The expression 
$$-\frac{\partial \log P^{\text{mkt}}(0,u)}{\partial u}$$
is the *market* instantaneous forward rate at date 0 for maturity $u$.
The left-hand side of
[\[extendedvasicekforwards\]](#extendedvasicekforwards){reference-type="eqref"
reference="extendedvasicekforwards"} is equal to
$$-\frac{\partial \log P(0,u)}{\partial u}\; ,$$
and hence is the *model* instantaneous forward rate at date 0 for
maturity $u$. Therefore, fitting the model to the yield curve is
equivalent to fitting model forward rates to market forward rates.[^1]

[^1]: To understand the interpretation of the derivatives of the log
    bond prices as forward rates, consider the market prices
    $P^{\text{mkt}}(0,u)$. Recall from our discussion in
    Sect. [\[s_forwardrates\]](#s_forwardrates){reference-type="ref"
    reference="s_forwardrates"} that to lock in at date 0 the rate of
    interest on a \$1 loan from dates $u$ to $u'$, one can buy a unit of
    the discount bond maturing at $u$ and raise the funds
    $P^{\text{mkt}}(0,u)$ required by short-selling
    $P^{\text{mkt}}(0,u)/P^{\text{mkt}}(0,u')$ units of the bond
    maturing at $u'$, which leads to an obligation of
    $P^{\text{mkt}}(0,u)/P^{\text{mkt}}(0,u')$ dollars at date $u'$. The
    continuously compounded forward rate for the loan between dates $u$
    and $u'$ is therefore $x$ defined by
    $$\E^{(u'-u)x} = \frac{P^{\text{mkt}}(0,u)}{P^{\text{mkt}}(0,u')}\; .$$
    Equivalently,
    $$x = \frac{\log P^{\text{mkt}}(0,u) -\log P^{\text{mkt}}(0,u')}{u'-u} = - \frac{\log P^{\text{mkt}}(0,u') -\log P^{\text{mkt}}(0,u)}{u'-u}\; .$$
    As we make the maturity of the loan shorter, with
    $u' \rightarrow u$, the limit of the above (the forward rate for an
    instantaneous loan) is by definition the derivative (the usual
    calculus derivative) of $-\log P^{\text{mkt}}(0,u)$.

It is very important to note that if we choose the function $\phi(t)$ at
date 0 to match the market, then when we want to recalibrate the model
at some later date to match the market at that date, we will have to
select a different $\phi$ function at the later date. In other words, we
use a model today that we know we will discard as incorrect tomorrow.
The $\phi$ function (as well as the $\kappa$ and $\sigma$ functions in
the general Hull-White model) is continually discarded and refit to
match the market. This is an unpleasant reality, but it is not really
too different from using implied volatilities in the Black-Scholes
formula. We know that the implied volatility curve changes over time, so
the volatility we use tomorrow may well be different from the volatility
we use today. No model is every a literally correct description of the
real world. As has been said, the test of the pudding is in the tasting.
The test of a model is whether it generates reasonably correct values
and hedges. This is an empirical question, and it is not equivalent to
the question of whether the assumptions of the model are correct.

# Discount Bond Options, Caps and Floors {#s_vasicek_discounts}

We can use Black's formula to value discount bond options in the Vasicek
model and in its extensions. As explained in the previous chapter, caps
and floors are portfolios of discount bond options, so the values of
caps (floors) can be computed by summing the values of the individual
caplets (floorlets).
The reason we can apply Black's formula is that the volatility of the
forward price of a discount bond is non-random in the Vasicek model and
its extensions.

Consider valuing at date 0 an option maturing at date $T$ on a discount
bond maturing at $u>T$. Because forward must equal spot at maturity, an
option written on a forward contract maturing at $T$ is equivalent.[^1]
The forward price of the discount bond at date $t \leq T$ for a forward
contract maturing at $T$ is given by

[^1]: This is the same reasoning we used to derive Merton's formulas
    from Black's formulas in
    Sect. [\[s_merton\]](#s_merton){reference-type="ref"
    reference="s_merton"}.
    $$F(t) =\frac{P(t,u)}{P(t,T)}\; .$$
From Itô's formula and the
equation [\[extendedvasicekbondreturn\]](#extendedvasicekbondreturn){reference-type="eqref"
reference="extendedvasicekbondreturn"} for the discount bond returns, we
have
\begin{align*}
\frac{\D F(t)}{F(t)} &= \text{something}\,\D t + \frac{\D P(t,u)}{P(t,u)} - \frac{\D P(t,T)}{P(t,T)}\\
&= \text{something}\,\D t -\sigma[b(u-t)-b(T-t)]\,\D B(t)\;.
\end{align*}
Thus, the volatility depends on the non-random function $b$.

In the continuous-time Ho-Lee model, we have
$$b(u-t)-b(T-t) = u-T\; .$$
Therefore, the forward price has a constant volatility equal to $(u-T)\sigma$.  In the Hull-White model, we have
$$b(u-t)-b(T-t) = \frac{1}{\kappa}\left(\E^{-\kappa(T-t)}-\E^{-\kappa(u-t)}\right) = \frac{\left(\E^{-\kappa T} - \E^{-\kappa u}\right)\E^{\kappa t}}{\kappa} \; .$$
Thus, the volatility is time varying (it depends on $t$), so we compute the average 
volatility as in Sects.~\ref{s_timevaryingvolatility} and~\ref{s_volatility}.  Specifically,
\begin{align}
\sigma_{\text{avg}} &= \frac{\sigma\left(\E^{-\kappa T} - \E^{-\kappa u}\right)}{\kappa} \sqrt{\frac{1}{T}\int_0^T \E^{2\kappa t}\,\D t}\notag\\
&=\frac{\sigma\left(\E^{-\kappa T} - \E^{-\kappa u}\right)}{\kappa}\sqrt{\frac{\E^{2\kappa T}-1}{2\kappa T}}\;.\label{vasiceksigmaavg}
\end{align}

Substituting $P^{\text{mkt}}(0,u)/P^{\text{mkt}}(0,T)$ as the forward price of the discount bond maturing at $u$ in Black's formula gives the following.

\mybox{Consider an option with exercise price $K$ maturing at date $T$ on a discount bond maturing at date $u>T$.  In the extended Vasicek model, the values at date~0 of such options are
\begin{subequations}\label{vasicekdiscountcallput}
\begin{align}
\text{Call Price} &=P^{\text{mkt}}(0,u)\N(d_1) - P^{\text{mkt}}(0,T)K\N(d_2)\;,\label{vasicekdiscountcall}\\
\text{Put Price} &= P^{\text{mkt}}(0,T)K\N(-d_2)-P^{\text{mkt}}(0,u)\N(-d_1)\;,\label{vasicekdiscountput}
\end{align}
where
\begin{align}
d_1 &= \frac{\log P^{\text{mkt}}(0,u) - \log\left(P^{\text{mkt}}(0,T)K\right) +\frac{1}{2}\sigma_{\text{avg}}^2T}{
\sigma_{\text{avg}}\sqrt{T}}\;,\label{vasicekdiscountcall_d1}\\
d_2 &= d_1 - \sigma_{\text{avg}}\sqrt{T}\;. \label{vasicekdiscountcall_d2}
\end{align}
\end{subequations}
The volatility $\sigma_{\text{avg}}$ is defined as $\sigma_{\text{avg}} = (u-T)\sigma$ in the continuous-time Ho-Lee model and according to the formula \eqref{vasiceksigmaavg} in the Hull-White model.
}
As our notation indicates, the discount bond prices appearing in these
formulas should be taken to be the *market* prices of the bonds at the
date the options are valued, rather than the *model* prices. Of course,
if we have fit the model to the market prices of discount bonds, there
is no distinction. Using model prices that are different from market
prices would be similar to inputting a stock price in the Black-Scholes
formula obtained from a discounted-cash-flow analysis rather than using
the market price of the stock. This is not something that one would
normally do.

Because the discount bond volatilities are the same in the
continuous-time Ho-Lee model as in the basic Vasicek model with
$\kappa=0$ and are the same in the Hull-White model as in the basic
Vasicek model with $\kappa>0$, the formulas for the values of discount
bond options are the same in the corresponding models. These extensions
of the basic Vasicek model permit one to match model bond prices to
market bond prices, but they have no effect on the values of discount
bond options, provided we remember to use the market prices in
[\[vasicekdiscountcallput\]](#vasicekdiscountcallput){reference-type="eqref"
reference="vasicekdiscountcallput"}.

As noted before, these option pricing formulas can be used to value
caplets and floorlets. A caplet with reset date $t_i$ and payment date
$t_{i+1}$ is equivalent, as discussed in
Sect. [\[s_caps2\]](#s_caps2){reference-type="ref" reference="s_caps2"},
to $1+\bar{R}\,\varDelta$ put options maturing at $t_i$ on the discount
bond maturing at $t_{i+1}$, with the exercise price of each option being
$1/(1+\bar{R}\,\varDelta t)$. When we make these substitutions in the
above formulas (and the same for floorlets) we obtain the following.
\mybox{Consider a caplet and a floorlet with reset date $t_i$ and payment date $t_{i+1}$.  Define $\varDelta t = t_{i+1}-t_i$.  Let $\bar{R}$ denote the cap and floor rate.  In the extended Vasicek model, the values at date 0 of the caplet and floorlet are as follows.
\begin{subequations}\label{vasicekcapletfloorlet}
\begin{align}
\text{Floorlet Price} &=(1+\bar{R}\,\varDelta t)P^{\text{mkt}}(0,t_{i+1})\N(d_1) - P^{\text{mkt}}(0,t_i)\N(d_2)\;,\label{vasicekfloorlet}\\
\text{Caplet Price} &= P^{\text{mkt}}(0,t_i)\N(-d_2)-(1+\bar{R}\,\varDelta t)P^{\text{mkt}}(0,t_{i+1})\N(-d_1)\;,\label{vasicekcaplet}
\end{align}
where
\begin{align}
d_1 &= \frac{\log\left((1+\bar{R}\,\varDelta t)P^{\text{mkt}}(0,t_{i+1})\right) -\log P^{\text{mkt}}(0,t_i)  +\frac{1}{2}\sigma_{\text{avg}}^2t_i}{
\sigma_{\text{avg}}\sqrt{t_i}}\;,\label{vasicekcaplet_d1}\\
d_2 &= d_1 - \sigma_{\text{avg}}\sqrt{t_i}\;, \label{vasicekcaplet_d2}
\end{align}
The volatility $\sigma_{\text{avg}}$ is defined as $\sigma\,\varDelta t$ in the continuous-time Ho-Lee model and as
\begin{equation}
\sigma_{\text{avg}} = \frac{\sigma \E^{-\kappa t_i}\left(1- \E^{-\kappa \,\varDelta t}\right) }{\kappa}\sqrt{\frac{\E^{2\kappa t_i}-1}{2\kappa t_i}}
\end{equation}
\end{subequations}
in the Hull-White model.
}


A reasonable way to choose the parameter $\sigma$ in the continuous-time Ho-Lee model and the parameters  $\kappa$ and $\sigma$ in the  Hull-White model would be to fit the model as well as possible to market prices of caps and/or floors.  The function $\phi(t)$ can then be chosen as discussed in the preceding section.  

We also used Black's formula to value caplets and floorlets in
Sect. [\[s_valuingcaps\]](#s_valuingcaps){reference-type="ref"
reference="s_valuingcaps"}. However, the formulas in this section and
the formulas in
Sect. [\[s_valuingcaps\]](#s_valuingcaps){reference-type="ref"
reference="s_valuingcaps"} give different values, because they are based
on different assumptions. In the Vasicek model and its extensions, the
forward price
$$F(t) = \frac{P(t,t_{i+1})}{P(t,t_i)}$$
of the discount bond corresponding to the caplet with payment date
$t_{i+1}$ has a non-random volatility, and this is the assumption on
which
[\[vasicekcapletfloorlet\]](#vasicekcapletfloorlet){reference-type="eqref"
reference="vasicekcapletfloorlet"} is based. In
Sect. [\[s_valuingcaps\]](#s_valuingcaps){reference-type="ref"
reference="s_valuingcaps"}, we assumed the forward LIBOR rate had a
non-random volatility. The
definition [\[forward2\]](#forward2){reference-type="eqref"
reference="forward2"} of the forward rate is
$$R_i(t) = \frac{P(t,t_i)}{P(t,t_{i+1})} - 1 = \frac{1}{F(t)}-1\; .$$
If the forward price has a non-random volatility, then the forward rate is the sum of a variable ($1/F(t)$) with a constant volatility and a constant ($-1$) and hence will have a random volatility.  Likewise, if the forward rate has a non-random volatility, then the forward price will have a random volatility.  Therefore, the assumptions of the two models are inconsistent.



# Coupon Bond Options and Swaptions {#s_vasicek_swaptions}

In this section, we will discuss the valuation of coupon bond options in
the extended Vasicek models. As discussed in
Sect. [\[s_swaptionscouponbondoptions\]](#s_swaptionscouponbondoptions){reference-type="ref"
reference="s_swaptionscouponbondoptions"}, swaptions are equivalent to
options on coupon bonds, so the valuation methods can also be applied to
swaptions.

Consider a bond paying a coupon of \$$c$ at dates
$t_1, t_2, \ldots, t_N$ and its face value of \$1 at date $t_N$.
Consider a European call option on the bond maturing at date $T$. In the
case of a European swaption, all of the coupon payment dates occur after
the option maturity ($t_i > T$ for $i=1,\ldots,N$), and the coupon is
taken to be $c=\bar{R}\,\varDelta t$, where $\bar{R}$ is the swap rate.
In the case of an option on a coupon bond, some of the coupons may occur
before the option maturity, but naturally the value of the option
depends only on the coupons that occur after the option matures, because
those are the only coupons to which an exerciser of the option would be
entitled. By focusing only on those coupons, we can take $t_i > T$ for
$i=1,\ldots,N$.


A coupon bond is a portfolio of discount bonds, so an option on a coupon
bond is an option on a portfolio of discount bonds. In general, an
option on a portfolio is worth less than a portfolio of options, so an
option on a coupon bond should be worth less than a portfolio of
discount bond options. However, in any "single-factor" model, it is
possible to define the strike prices of the discount bond options so
that the option on the coupon bond is worth exactly the same as a
portfolio of discount bond options.[^1] This reduces the valuation
problem for coupon bond options to the problem of valuing discount bond
options, which we have already solved for this model. We will use the
same technique in
Sect. [\[s_captions\]](#s_captions){reference-type="ref"
reference="s_captions"} to value options on caps ("captions") and
options on floors ("floortions").

[^1]: This method was first described by Jamshidian [@Jamshidian89].

As shown in
[\[extendedvasicekbond\]](#extendedvasicekbond){reference-type="eqref"
reference="extendedvasicekbond"}, the single factor that determines all
discount bond prices in this model is the random variable $\hat{r}$. We
let $r^*$ denote the value of $\hat{r}(T)$ such that, according to the
model, the coupon bond option will be at the money at maturity when
$\hat{r}(T)=r^*$. Being at the money means of course that
\begin{equation}\label{swaptions101}
\sum_{i=1}^N cP(T,t_i) + P(T,t_N) = K\;.
\end{equation}
Thus, based on the formula \eqref{extendedvasicekbond} for the discount bond prices, we define~$r^*$ by
\begin{multline}\label{swaptions102}
\sum_{i=1}^N c\exp\left(-\int_T^{t_i} \phi(s)\,\D s-a(t_i-T)-b(t_i-T)r^*\right) \\+ \exp\left(-\int_T^{t_N} \phi(s)\,\D s-a(t_N-T)-b(t_N-T)r^*\right) = K\;. \tag{\ref{swaptions101}$'$}
\end{multline}
According to the model, if $\hat{r}(T)$ is lower than $r^*$, then the bond prices will be higher and the call option will be in the money; conversely, if $\hat{r}(T)$ is higher than $r^*$, then the bond prices will be lower and the call option will be out of the money.  

For $i=1,\ldots,N$, define $K_i$ to be the model value of the discount bond price $P(T,t_i)$ when $\hat{r}(T)=r^*$.  In other words, define $K_i$ as 
\begin{equation}\label{swaptions103}
K_i = \exp\left(-\int_T^{t_i} \phi(s)\,\D s-a(t_i-T)-b(t_i-T)r^*\right)\;.
\end{equation}
Note that equations \eqref{swaptions102} and \eqref{swaptions103} imply
\begin{equation}\label{swaption100000}
\sum_{i=1}^N cK_i + K_N = K\; .
\end{equation}

Consider for each $i$ ($i=1,\ldots,N$) a hypothetical call option maturing at~$T$ with the underlying for the option being the discount bond maturing at $t_i$.  Let $K_i$ be the exercise price of option $i$.  According to the model, the value of the underlying at date~$T$ for option~$i$ will be 
$$P(T,t_i) = \exp\left(-\int_T^{t_i} \phi(s)\,\D s-a(t_i-T)-b(t_i-T)\hat{r}(T)\right)\; .$$
By the definition of $K_i$, therefore, option~$i$ will be in the money if and only if 
$\hat{r}(T) < r^*$.
Thus, all of the options are in (or out) of the money in the same circumstances.  

Now consider the portfolio consisting of $c$ units of option $i$ for
$i=1,\ldots,N-1$ and $1+c$ units of option $N$. According to the model,
the value of the portfolio will be zero at date $T$ if
$\hat{r}(T) \geq r^*$, and, if $\hat{r}(T)<r^*$, it follows from
[\[swaption100000\]](#swaption100000){reference-type="eqref"
reference="swaption100000"} that the value of the portfolio will be
$$
\sum_{i=1}^{N-1}c\big[P(t,t_i)-K_i\big]+ (1+c)\big[P(t,T_N)-K_N\big] 
= \sum_{i=1}^NcP(t,t_i)+ P(t,T_N) - K,
$$
which is the intrinsic value of the coupon bond option when $r(T)<r^*$.
Therefore, according to the model, the coupon bond option is equivalent
to this portfolio of discount bond options. We can value the discount
bond options from the formulas in the previous section and then value
the portfolio and hence the coupon bond option by summing.
The same type of reasoning also allows us to value put options on coupon bonds.

The only issue in implementing this method is that we need to compute
the exercise prices $K_i$. Of course, we define them by
[\[swaptions103\]](#swaptions103){reference-type="eqref"
reference="swaptions103"}, given $r^*$. To do this requires that we
calculate the factor
\begin{equation}\label{vasicekfactor100}
\exp\left(-\int_T^{t_i} \phi(s)\,\D s\right),
\end{equation}
by fitting the model to market bond prices, as discussed in
Sect. [\[s_vasicek_fitting\]](#s_vasicek_fitting){reference-type="ref"
reference="s_vasicek_fitting"}. We will explain this more explicitly in
the next paragraph. In order to apply
equation [\[swaptions103\]](#swaptions103){reference-type="eqref"
reference="swaptions103"}, we need to compute $r^*$, which is given by
equation [\[swaptions102\]](#swaptions102){reference-type="eqref"
reference="swaptions102"}. We can
solve [\[swaptions102\]](#swaptions102){reference-type="eqref"
reference="swaptions102"} for $r^*$ by bisection or some other
root-finding method. Again, we need to know the factors
[\[vasicekfactor100\]](#vasicekfactor100){reference-type="eqref"
reference="vasicekfactor100"}
 in order to solve this equation.

To compute the factors \eqref{vasicekfactor100},
we use  \eqref{vasicekcalibration101}.  We repeat it here twice, for maturity dates $t_i$ and $T$:
\begin{align*}
\exp\left(-\int_0^{t_i} \phi(s)\,\D s\right) &= \exp\left(a(t_i)+b(t_i)r(0)\right)P^{\text{mkt}}(0,t_i)\; ,\\
\exp\left(-\int_0^{T} \phi(s)\,\D s\right) &= \exp\left(a(T)+b(T)r(0)\right)P^{\text{mkt}}(0,T)\;.
\end{align*}
If we divide the top equation by the bottom, then on the left-hand side we obtain
\begin{align*}
\frac{\exp\left(-\int_0^{t_i} \phi(s)\,\D s\right)}{\exp\left(-\int_0^{T} \phi(s)\,\D s\right)} &= \exp\left(-\int_0^{t_i} \phi(s)\,\D s + \int_0^{T} \phi(s)\,\D s\right) \\
&= \exp\left(-\int_T^{t_i} \phi(s)\,\D s\right)\; ,
\end{align*}
which is the number we want.  Hence, we obtain by dividing the right-hand sides of the above equations:
\begin{equation}\label{swaptions104}
\exp\left(-\int_T^{t_i} \phi(s)\,\D s\right) = \exp\left\{a(t_i)-a(T) + [b(t_i)-b(T)]r(0)\right\}\frac{P^{\text{mkt}}(0,t_i)}{P^{\text{mkt}}(0,T)}\;.
\end{equation}



# Captions and Floortions {#s_captions}

In this section, we will consider options on caps and floors, which are
sometimes called "captions" and "floortions" respectively. For
specificity, we will consider a call option on a cap.
A cap is a portfolio of caplets, and each caplet is a call option on a spot rate.  Therefore a call option on a cap is a call option on a portfolio of calls on spot rates and hence is a bet on (or insurance against) high spot rates.  

Of course, high spot rates are equivalent to low bond prices, so a call
on a cap can also be seen as a bet on low bond prices. We will actually
take this latter approach and view a cap as a portfolio of put options
on discount bonds, as in
Sect. [\[s_vasicek_discounts\]](#s_vasicek_discounts){reference-type="ref"
reference="s_vasicek_discounts"}. This means that we will analyze a call
option on a cap as a call on a portfolio of puts. We will use the trick
of the previous section and reduce this call on a portfolio of puts to a
portfolio of calls on puts. Each call on a put is a compound option and
can be valued as in
Chap. [\[c_exotics\]](#c_exotics){reference-type="ref"
reference="c_exotics"}. The assumptions made in
Chap. [\[c_exotics\]](#c_exotics){reference-type="ref"
reference="c_exotics"} for compound options are valid here, because the
forward prices of the discount bonds (which are the underlyings for the
puts) have non-random volatilities in the extended Vasicek models.

Consider a cap with reset dates $t_0,\ldots t_{N-1}$ and payment dates
$t_1,\ldots, t_N$, with $t_{i+1}-t_i=\varDelta t$ for each $i$. Let
$\bar{R}$ denote the fixed rate on the cap. We consider a call option on
the cap maturing at date $T \leq t_0$ and having exercise price $K$. In
the model, the value of the cap at the option maturity will depend on
the random variable $\hat{r}(T)$. As in the previous section, we will
let $r^*$ denote the value of $\hat{r}(T)$ such that the call option on
the cap is at the money at date $T$ when $\hat{r}(T)=r^*$. If
$\hat{r}(T)>r^*$ then the cap will be more valuable, so the call will be
in the money; conversely if $\hat{r}(T)<r^*$ the call will be out of the
money. Also, similar again to the previous section, we will let $K_i$
denote the value of the caplet with reset date $t_i$ and payment date
$t_{i+1}$ ($i=0,\ldots,N-1$) when $\hat{r}(T)=r^*$. We consider
hypothetical call options on the individual caplets with exercise prices
$K_i$. If $\hat{r}(T)>r^*$, then, according to the model, all of the
calls on the caplets will be in the money, and the sum of their values
will equal the value of the call on the cap. On the other hand, if
$\hat{r}(T)<r^*$ then all of the calls on the caplets will be out of the
money, as will be the call on the cap. Thus, the value of the call on
the cap is the sum of the values of the calls on the caplets.

In order to apply the methods developed in
Chap. [\[c_exotics\]](#c_exotics){reference-type="ref"
reference="c_exotics"} for valuing compound options to value the calls
on the caplets (i.e., the calls on puts on discount bonds), all we need
to do is to calculate the rate $r^*$ and the exercise prices $K_i$. We
will explain this only briefly.

Consider the caplet with payment date $t_{i+1}$. According to the
valuation formula
[\[vasicekcaplet\]](#vasicekcaplet){reference-type="eqref"
reference="vasicekcaplet"}, the value of the caplet at date $T$, when
there is a remaining time to maturity of $t_i-T$, will be[^1]

[^1]: We use now the model prices for the discount bonds at date $T$.
    Obviously, the market prices at the caption maturity date $T$ are
    unknown at date 0, the date at which we are valuing the caption.
    
    \begin{subequations}\label{captions13combined}
\begin{equation}\label{captions1}
\text{Caplet Value at Date $T$} = P(T,t_{i})N(-d_2) - (1+\bar{R}\varDelta t)P(T,t_{i+1})N(-d_1)\;,
\end{equation}
where
\begin{align}
d_1 &= \frac{\log\left((1+\bar{R}\varDelta t)P(T,t_{i+1})\right) - \log P(T,t_{i})+\frac{1}{2}\sigma_{\text{avg}}^2(t_{i}-T)}{
\sigma_{\text{avg}}\sqrt{t_{i}-T}}\;,\label{captions2}\\
d_2 &= d_1 - \sigma_{\text{avg}}\sqrt{t_{i}-T}\;.\label{captions3}
\end{align}
\end{subequations}
Here $\sigma_{\text{avg}}$ denotes the average volatility of the forward
price of the discount bond between the option valuation date $T$ and the
option maturity date $t_{i}$. This shows that the values of the caplets
and hence the value of the cap depend on the discount bond prices at
date $T$, which, according to the model, depend on $\hat{r}(T)$. One can
use bisection or some other root-finding method again to find the value
of $\hat{r}(T)$ such that, according to the model, the value of the cap
will be $K$ at date $T$. Substituting this value of $\hat{r}(T)$ into
the bond pricing formula
[\[extendedvasicekbondcombined\]](#extendedvasicekbondcombined){reference-type="eqref"
reference="extendedvasicekbondcombined"} and then substituting the bond
prices $P(T,t_{i})$ and $P(T,t_{i+1})$ into
[\[captions13combined\]](#captions13combined){reference-type="eqref"
reference="captions13combined"}, we define $K_i$ as the caplet value in
[\[captions1\]](#captions1){reference-type="eqref"
reference="captions1"}.



# Yields and Yield Volatilities {#s_HW_yields}

We are denoting the price at date $t$ of a discount bond maturing at
$u$, with remaining time to maturity of $\tau = u-t$, as $P(t,u)$.
However, as in
Sect. [\[s_yieldcurve\]](#s_yieldcurve){reference-type="ref"
reference="s_yieldcurve"}, we will denote the corresponding yield as
$y(t,\tau)$. The yield is defined as
$$y(t,\tau) = \frac{-\log P(t,u)}{\tau}\; .$$
In the extended Vasicek model, the yield is given by the bond pricing formula \eqref{vasicekbond} as
$$y(t,\tau) = \frac{\int_t^{t+\tau} \phi(s)\,\D s + a(\tau) + b(\tau)\hat{r}(t)}{\tau}\; .$$
Note that the component
$$\frac{a(\tau) + b(\tau)\hat{r}(t)}{\tau}$$
of the yield $y(t,t+\tau)$ is independent of $t$, except for its dependence on $\hat{r}(t)$.  For example, in the continuous-time Ho-Lee model, this component equals
$$-\frac{\sigma^2\tau^2}{6} + \hat{r}(t)\; .$$
This is a decreasing function of the time to maturity $\tau$ with intercept equal to $\hat{r}(t)$.  At a different date $t$, this component of the yield curve would be the same, except for having a different intercept.\footnote{Note that this part decreases to $-\infty$ at long maturities ($\tau \rightarrow \infty$), which is very strange for yields, which should be nonnegative.  To compensate for this strange behavior, one needs the part $$\frac{1}{\tau}\int_t^{t+\tau} \phi(s)\,\D s\; ,$$
which is the average of $\phi(s)$ between $t$ and $t+\tau$ to be growing sufficiently with $\tau$.  This phenomenon is a consequence of the absence of mean reversion.}  This is the reason for the statement in Sect.~\ref{s_vasicekhedging} that only parallel shifts in the yield curve are possible in this model (and hence duration hedging works in the model).

The volatility at date $t$ of the yield at a fixed maturity $\tau$
is[^1] $\sigma b(\tau)/\tau$.

[^1]: By "volatility" here we mean the instantaneous standard deviation
    of $\D y(t,\tau)$ not the instantaneous standard deviation of
    $\D y(t,\tau)/y(t,\tau)$.
    In the continuous-time Ho-Lee model, this is $\sigma$ and in the  Hull-White model it is $\sigma\left(1-\E^{-\kappa\tau}\right)/(\kappa\tau)$.  In Sect.~\ref{s_vasicek_discounts} we mentioned that one might choose the parameter~$\sigma$ in the Ho-Lee model and the parameters $\sigma$ and $\kappa$ in the  Hull-White model to fit cap or floor prices as well as possible.  An alternative would be to choose them to match estimated yield volatilities.  Of course the fit to either cap prices or yield volatilities will be of limited quality, given that there is only one or two parameters in these models.  On the other hand, an exact fit can be obtained with the general Hull-White model.



# The General Hull-White Model {#s_generalHW}

We will briefly discuss the general Hull-White model, in which
\begin{equation}\label{hw600}
\D r(t) = \theta(t)\,\D t -\kappa(t)r(t)\,\D t + \sigma(t)\,\D B(t)\;.
\end{equation}
By differentiating the following, one can see that the short rate $r$ in the general Hull-White model satisfies
\begin{subequations}
\begin{equation}\label{hw601}
r(s) = \phi(s) + \hat{r}(s)\;,
\end{equation}
where
\begin{equation}\label{phi101}
\phi(s) =  \int_0^s\exp\left(-\int_y^s\kappa(x)\,\D x\right)\theta(y)\,\D y\;.
\end{equation}
and
\begin{equation}\label{rhat101}
\hat{r}(s) = \exp\left(-\int_0^s\kappa(x)\,\D x\right)r(0)+\int_0^s\exp\left(-\int_y^s\kappa(x)\,\D x\right)\sigma(y)\,\D B(y)\;.
\end{equation}
\end{subequations}
As before, discount bond prices are
\begin{equation}\label{hw602}
P(t,u) = \exp\left(-\int_t^u \phi(s)\,\D s\right)E^R_t \left[ \exp\left(-\int_t^u \hat{r}(s)\,\D s\right)\right]\;.
\end{equation}
Moreover,  \eqref{rhat101} implies, for $s>t$, 
%\begin{equation}\label{rhat1001}
$$\hat{r}(s) = \exp\left(-\int_t^s\kappa(x)\,\D x\right)\,\hat{r}(t)+\int_t^s\exp\left(-\int_y^s\kappa(x)\,\D x\right)\sigma(y)\,\D B(y)\;.
$$
Using this fact, the expectation in
[\[hw602\]](#hw602){reference-type="eqref" reference="hw602"} can be
calculated as before as the expectation of the exponential of a normally
distributed random variable, leading to the result
\begin{subequations}
\begin{equation}\label{hw603}
P(t,u) = \exp\left(-\int_t^u \phi(s)\,\D s-a(t,u)-b(t,u)\hat{r}(t)\right)\;,
\end{equation}
where
\begin{align}
b(t,u) &= \int_t^u \exp\left(-\int_t^s\kappa(x)\,\D x\right)\,\D s\; ,\\
a(t,u) &=  -\frac{1}{2}\int_t^u b(y,u)^2\sigma(y)^2\,\D y\;.
\end{align}
\end{subequations}
Note that the functions $a$ and $b$ now depend on the date $t$ of valuation and the date $u$ of maturity rather than being determined entirely by the time to maturity $u-t$.  Note also that we can write
\begin{align}
b(t,u) &= \exp\left(\int_0^t\kappa(x)\,\D x\right)\int_t^u\exp\left(-\int_0^s\kappa(x)\,\D x\right)\,\D s\notag\\
&= \exp\left(\int_0^t\kappa(x)\,\D x\right)\\
&\qquad \times\left[\int_0^u\exp\left(-\int_0^s\kappa(x)\,\D x\right)\,\D s - \int_0^t\exp\left(-\int_0^s\kappa(x)\,\D x\right)\,\D s\right]\notag\\
&=\exp\left(\int_0^t\kappa(x)\,\D x\right)\big(b(0,u)-b(0,t)\big)\;.\label{hw2btu}
\end{align}
Therefore, we can recover the functions $b(t,u)$ and  $a(t,u)$ from the functions $b(0,t)$, $\exp\left(\int_0^t\kappa(x)\,\D x\right)$, and $\sigma(t)$.

\vfil\eject
The returns of discount bonds satisfy
\begin{equation}\label{extendedvasicekbondreturn2}
\frac{\D P(t,u)}{P(t,u)} = r(t)\,\D t - \sigma(t) b(t,u)\,\D B(t)\;.
\end{equation}
Hence, hedge ratios, which depend on relative volatilities, are  determined by the function~$b$ as before.  Given the functions $\kappa$ and $\sigma$, the model can be calibrated to market discount bond prices by choosing the function $\phi$ exactly as discussed in Sect.~\ref{s_vasicek_fitting}.  

The pricing of fixed-income derivatives discussed in Sects.
\[$$s_vasicek_discounts$$\](#s_vasicek_discounts)reference-type=\"ref\"
reference=\"s_vasicek_discounts\"--\[$$s_captions$$\](#s_captions)reference-type=\"ref\"
reference=\"s_captions\" was based on forward prices of discount bonds
having non-random volatilities. This is true also in the general
Hull-White model. Given dates $t<T<u$, the forward price at date $t$ of
the discount bond maturing at date $u$, when the forward contract
matures at $T$, is, as before, $F(t)=P(t,u)/P(t,T)$. In the general
Hull-White model, we have
\begin{align*}
\frac{\D F(t)}{F(t)} &= \text{something}\,\D t + \frac{\D P(t,u)}{P(t,u)} - \frac{\D P(t,T)}{P(t,T)}\\
&= \text{something}\,\D t -\sigma(t)[b(t,u)-b(t,T)]\,\D B(t)\\
&= \text{something}\,\D t -\sigma(t)\exp\left(\int_0^t\kappa(x)\,\D x\right)\big[b(0,u)-b(0,T)\big]\,\D B(t)\;.
\end{align*}
Thus, the average volatility, from date 0 to date T, is 
$$\sigma_{\text{avg}} = \big[b(0,u)-b(0,T)\big]\sqrt{\frac{1}{T}\int_0^T \sigma(t)^2\exp\left(2\int_0^t\kappa(x)\,\D x\right)\,\D t}\; .$$
With this substitution,  the pricing of fixed-income derivatives is the same as in the basic Hull-White model discussed in Sects.~\ref{s_vasicek_discounts}--\ref{s_captions}.


The advantage of the general Hull-White model is that it allows more flexibility in fitting the model to current market conditions.  This may (though there is certainly no guarantee) provide better pricing and hedging of interest-rate derivatives.  Hull and White suggest choosing the volatility function $\sigma$ to fit anticipated future volatilities of the short rate and choosing the mean-reversion function $\kappa$ to fit market cap/floor prices or yield volatilities.  
We will assume that the volatility function $\sigma$ has been chosen, and we will describe how to choose the mean-reversion function to fit the model to estimated yield volatilities or cap prices.  As usual, we let date~0 denote the date at which we are fitting the model.



The simplest approach is to take the function $\kappa(t)$ to be piecewise constant.  Consider dates $0=t_0 < t_1 < \cdots t_M$ with $t_i-t_{i-1}=\varDelta t$ for each $i$.  For valuing a swaption, for example, we would want $t_M$ to be the sum of the time to maturity of the swaption and the length of the swap.  Thus, we are fitting the model until the end of the swap underlying the swaption.  We want to find numbers $\kappa_1,\ldots,\kappa_M$ and will set the function $\kappa$ to equal $\kappa_i$ for~$t$ between $t_{i-1}$ and $t_i$.

Given this definition, we have
\begin{align*}
\exp\left(-\int_0^{t_1}\kappa(x)\,\D x\right) &= \E^{-\kappa_1\,\varDelta t}\; ,\\
\exp\left(-\int_0^{t_2}\kappa(x)\,\D x\right) &= \E^{-\kappa_1\,\varDelta t}\E^{-\kappa_2\,\varDelta t}\; ,\\
\exp\left(-\int_0^{t_3}\kappa(x)\,\D x\right) &= \E^{-\kappa_1\,\varDelta t}\E^{-\kappa_2\,\varDelta t}\E^{-\kappa_3\,\varDelta t}\;,
\end{align*}
etc.  Furthermore,
\begin{align*}
b(0,t_1) &= \E^{-\kappa_1\,\varDelta t}\varDelta t\; ,\\
b(0,t_2) &= \E^{-\kappa_1\,\varDelta t}\,\varDelta t + \E^{-\kappa_1\,\varDelta t}\E^{-\kappa_2\,\varDelta t}\,\varDelta t\; ,\\
b(0,t_3) &= \E^{-\kappa_1\,\varDelta t}\,\varDelta t + \E^{-\kappa_1\,\varDelta t}\E^{-\kappa_2\,\varDelta t}\,\varDelta t + \E^{-\kappa_1\,\varDelta t}\E^{-\kappa_2\,\varDelta t}\E^{-\kappa_3\,\varDelta t}\,\varDelta t\;,
\end{align*}
etc.
This yields the following recursive structure for the $b(0,t_i)$.
\begin{subequations}\label{generalhwrecursive}
\begin{align}
b(0,t_1) &= \E^{-\kappa_1\,\varDelta t}\varDelta t\; ,\\
b(0,t_2) &= b(0,t_1) + b(0,t_1)\E^{-\kappa_2\,\varDelta t}\; ,\\
(\forall i \geq 3) \quad b(0,t_i) &= b(0,t_{i-1}) + [b(0,t_{i-1})-b(0,t_{i-2})]\E^{-\kappa_i\,\varDelta t}\;.
\end{align}
\end{subequations}

Matching the yield volatilities in the model to estimated market
volatilities is extremely simple. The same analysis presented in
Sect. [\[s_HW_yields\]](#s_HW_yields){reference-type="ref"
reference="s_HW_yields"} for the basic Hull-White model shows that the
volatility at date 0 of the yield at maturity $t_i$ in the general
Hull-White model is
$$\frac{\sigma(0) b(0,t_i)}{t_i}\; .$$
Given the estimated yield volatility, we can define $b(0,t_i)$ by equating the model volatility to the estimated volatility.  Using \eqref{generalhwrecursive}, the $\kappa_i$ can be computed from the $b(0,t_i)$ for $i=1,2,\ldots$.

It is equally easy to match the model to market cap or floor prices.
Suppose we have estimated implied volatilities for caplets using the
pricing formula
[\[vasicekcapletfloorlet\]](#vasicekcapletfloorlet){reference-type="eqref"
reference="vasicekcapletfloorlet"}. Suppose the first caplet has reset
date $t_1$ and payment date $t_2$, the second has reset date $t_2$ and
payment date $t_3$, etc. According to the model, the average volatility
of the forward price of the discount bond underlying the caplet with
reset date $t_i$ and payment date $t_{i+1}$ is
$$ \big[b(0,t_{i+1})-b(0,t_i)\big]\sqrt{\frac{1}{t_i}\int_0^{t_i} \sigma(t)^2\exp\left(2\int_0^t\kappa(x)\,\D x\right)\,\D t}\; .$$
Notice that everything in this expression, except $b(0,t_{i+1})$, is
determined by $\kappa_1,\ldots,\kappa_i$ and the $\sigma$ function.  Therefore, we can select the number $b(0,t_{i+1})$ to match the model volatility to the implied volatility for this caplet.  This defines $\kappa_{i+1}$ from \eqref{generalhwrecursive}.  Continuing in this way, we can successively define $\kappa_1, \kappa_2, \ldots.$

# Calculations in VBA

## Discount Bond Options {#discount-bond-options .unnumbered}
Rather than calculating $\sigma_{\text{avg}}$ from the volatility
$\sigma$ of the short rate and the constant $\kappa$ or function
$\kappa(t)$, we will treat $\sigma_{\text{avg}}$ as an input into the
option pricing formulas. This is necessary if one wants to use (i.e.,
invert) the following functions to imply $\sigma_{\text{avg}}$ from
market prices and then used the implied $\sigma_{\text{avg}}$ to
calibrate the model.

\addcontentsline{lof}{figure}{Vasicek Discount Bond Call}
\small\begin{verbatim}
Function Vasicek_Discount_Bond_Call(Underlying,K,MatDisc,sigavg,T)
'
' Inputs are Underlying = price of underlying discount bond
'            K = strike price
'            MatDisc = price of bond maturing when option matures
'            sigavg = average volatility of the forward bond price
'            T = time to maturity
'
Dim F
F = Underlying / MatDisc  ' forward price of the underlying
Vasicek_MatDisc_Bond_Call = Black_Call(F, K, MatDisc, sigavg, T)
End Function
\end{verbatim}\normalsize

\addcontentsline{lof}{figure}{Vasicek Discount Bond Put}
\small\begin{verbatim}
Function Vasicek_Discount_Bond_Put(Underlying,K,MatDisc,sigavg,T)
'
' Inputs are Underlying = price of underlying discount bond
'            K = strike price
'            MatDisc = price of bond maturing when option matures
'            sigavg = average volatility of the forward bond price
'            T = time to maturity
'
Dim F
F = Underlying / MatDisc  ' forward price of the underlying
Vasicek_Discount_Bond_Put = Black_Put(F, K, MatDisc, sigavg, T)
End Function
\end{verbatim}\normalsize

## Caps {#caps .unnumbered}
We input the first reset date $t_0$, the time between payments
$\varDelta t$, the total number of payments $N$ and the cap rate
$\bar{\mathcal{R}}$. As in
Sect. [\[s_fixedincomederivatives_matlab\]](#s_fixedincomederivatives_matlab){reference-type="ref"
reference="s_fixedincomederivatives_matlab"}, we input the price of the
discount bond maturing at $t_0$ as `P0`, and we input a vector `P`
containing the $N$ discount bond prices $P(0,t_1),\ldots,P(0,t_{N})$. We
will allow different volatilities for the different caplets. The input
`sigavg` should have elements 1 through $N$, with `sigavg(i)` being the
average volatility of the forward price of the discount bond maturing at
$t_i$, where the forward contract matures at $t_{i-1}$, and the average
volatility is computed from date 0 to date $t_{i-1}$, according to the
formulas in
Sect. [\[s_vasicek_discounts\]](#s_vasicek_discounts){reference-type="ref"
reference="s_vasicek_discounts"}. Specifically, `sigavg(i)` should be
$\sigma\,\varDelta t$ for the continuous-time Ho-Lee model, and
`sigavg(i)` should be
 \begin{equation}\label{vasicekvbacap}
 \frac{\sigma \E^{-\kappa t_{i-1}}\left(1- \E^{-\kappa \,\varDelta t}\right) }{\kappa}\sqrt{\frac{\E^{2\kappa t_{i-1}}-1}{2\kappa t_{i-1}}}
 \end{equation}
 for the Hull-White model.  

\addcontentsline{lof}{figure}{Vasicek Cap}
\small\begin{verbatim}
Function Vasicek_Cap(P0, P, rbar, sigavg, N, t0, dt)
'
' Inputs are P0 = price of discount bond maturing at t0
'            P = N-vector of discount bond prices, from t1 to tN
'            rbar = fixed rate in the cap
'            sigavg = N-vector of average vols of forward prices
'            N = number of reset (or payment) dates
'            t0 = time until first reset date
'            dt = time between reset (or payment) dates
'
Dim K, x, MatDisc, Underlying, mat, i
K = 1 / (1 + rbar * dt) ' exercise price of each caplet
If t0 = 0 Then
'   if valuing at the reset date of the first caplet,
'   the value of the first caplet is its intrinsic value
    x = P(1) * Application.Max(0, 1 / P(1) - 1 - rbar * dt)
Else          ' if valuing before maturity of first caplet
    MatDisc = P0
    Underlying = P(1)
    x = _
    Vasicek_Discount_Bond_Put(Underlying,K,MatDisc,sigavg(1),t0)
End If
For i = 1 To N - 1
    MatDisc = P(i)         ' price of bondmaturing at reset date
    Underlying = P(i + 1)   ' price of bondmaturing at payment date
    mat = t0 + i * dt       ' reset date of i-th caplet
    x = x + _
    Vasicek_Discount_Bond_Put(Underlying,K,MatDisc,sigavg(i+1),mat)
Next i
Vasicek_Cap = (1 + rbar * dt) * x ' each caplet is (1+rbar*dt) puts
End Function
\end{verbatim}\normalsize

## Coupon Bond Options in the Hull-White Model {#coupon-bond-options-in-the-hull-white-model .unnumbered}

We will value a European call option on a coupon bond. First we create
functions to calculate $a(\tau)$ defined in
[\[extendedvasicek_a\]](#extendedvasicek_a){reference-type="eqref"
reference="extendedvasicek_a"}, $b(\tau)$ defined in
[\[extendedvasicek_b\]](#extendedvasicek_b){reference-type="eqref"
reference="extendedvasicek_b"}, and $\sigma_{\text{avg}}$ defined in
[\[vasiceksigmaavg\]](#vasiceksigmaavg){reference-type="eqref"
reference="vasiceksigmaavg"}.

\small\begin{verbatim}
Function hwa(sigma, kappa, tau)
hwa = -sigma ^ 2 * (2 * kappa * tau - Exp(-2 * kappa * tau) _
      + 4 * Exp(-kappa * tau) - 3) / (4 * kappa ^ 3)
End Function
\end{verbatim}\normalsize

\small\begin{verbatim}
Function hwb(kappa, tau)
hwb = (1 - Exp(-kappa * tau)) / kappa
End Function
\end{verbatim}\normalsize

\small\begin{verbatim}
Function hwsigavg(sigma, kappa, T, u)
hwsigavg = (sigma * (Exp(-kappa * T) - Exp(-kappa * u)) / kappa) _
         * Sqr((Exp(2 * kappa * T) - 1) / (2 * kappa * T))
End Function
\end{verbatim}\normalsize
We calculate the model value of the coupon bond at date $T$ (given by
the left-hand side of
[\[swaptions102\]](#swaptions102){reference-type="eqref"
reference="swaptions102"} for $r=r^*$) in the function `HW_Coup_Bond`.
The vector `Cal` contains $N$ elements, and `Cal(i)` represents the
calibration factor $\E^{-\int_T^{t_i} \phi(s)\,\D s}$, which will be
calculated from [\[swaptions104\]](#swaptions104){reference-type="eqref"
reference="swaptions104"} in the main function `HW_Coup_Bond_Call`.

\addcontentsline{lof}{figure}{HW Coup Bond}
\small\begin{verbatim}
Function HW_Coup_Bond(Coup,N,t1,dt,Cal,r,sigma,kappa,T)
Dim x, tau, a, b, i
x = 0
For i = 1 To N - 1                 ' coupon dates before maturity
    tau = t1 + (i - 1) * dt - T                ' tau = ti  - T
    a = hwa(sigma, kappa, tau)                 ' a(ti - T)
    b = hwb(kappa, tau)                        ' b(ti - T)
    x = x + Coup * Cal(i) * Exp(-a - b * r)
Next i
tau = t1 + (N - 1) * dt - T                    ' tau = tN - T
a = hwa(sigma, kappa, tau)                     ' a(tN - T)
b = hwb(kappa, tau)                            ' b(tN - T)
x = x+(1+Coup)*Cal(N)*Exp(-a-b*r)  ' face and coupon at maturity
HW_Coup_Bond = x
End Function
\end{verbatim}\normalsize
In the main function `HW_Coupon_Bond_Call`, we input the coupon paid by
the bond, the number `N` of coupon payments, the amount of time `t1`
before the first coupon payment, the amount of time `dt` between coupon
payments, the strike price `K` of the option, the price `MatDisc` of the
discount bond maturing at the option maturity date $T$, a vector `P`
containing the `N` market prices of the discount bonds maturing at the
coupon payment dates $t_1, \ldots, t_N$, the current short rate `r`, the
parameters `sigma` and `kappa` of the Vasicek model, and the amount of
time `T` until the option matures.
\addcontentsline{lof}{figure}{HW Coup Bond Call}
\small\begin{verbatim}
Function HW_Coup_Bond_Call(Coup,N,t1,dt,K,MatDisc,P,r,sigma,kappa,T)
'
' Inputs are Coup = amount of each coupon
'            N = number of coupons
'            t1 = time until first coupon
'            dt = time between coupon payment dates
'            K = strike price
'            MatDisc = price of bond maturing when option matures
'            P = N-vector of bond prices from t1 to tN 
'            r = initial value of the short rate
'            sigma = volatility of the short rate
'            kappa = mean-reversion of the short rate
'            T = time to maturity
'
Dim tol, guess, fguess, rstar, x, tau, lower, flower, upper, fupper
Dim a, b, aT, bT, strike, sigavg, Cal(), i
ReDim Cal(1 To N)
'
' First we calibrate the model to market bond prices
'
aT = hwa(sigma, kappa, T)
bT = hwb(kappa, T)
For i = 1 To N
    tau = t1 + (i - 1) * dt                          ' tau = ti
    a = hwa(sigma, kappa, tau)                       ' a(ti)
    b = hwb(kappa, tau)                              ' b(ti)
    Cal(i) = Exp(a - aT + (b - bT) * r) * P(i) / MatDisc
Next i
'
'  We find upper and lower bounds for rstar
'
lower = 0                  ' first try at lower bound
flower = HW_Coup_Bond(Coup,N,t1,dt,Cal,lower,sigma,kappa,T)-K
Do While flower < 0        ' reduce lower for a lower bound
    lower = lower - 1
    flower = _
    HW_Coup_Bond(Coup,N,t1,dt,Cal,lower,sigma,kappa,T)-K
Loop
upper = 1                  ' first try at upper bound
fupper = HW_Coup_Bond(Coup,N,t1,dt,Cal,upper,sigma,kappa,T)-K
Do While fupper > 0        ' increase upper for an upper bound
    upper = upper + 1
    fupper = _
    HW_Coup_Bond(Coup,N,t1,dt,Cal,upper,sigma,kappa,T)-K
Loop
'
' Now we do the bisection to find rstar
'
tol = 10 ^ -8
guess = 0.5 * lower + 0.5 * upper
fguess = HW_Coup_Bond(Coup,N,t1,dt,Cal,guess,sigma,kappa,T)-K
Do While upper - lower > tol
    If fupper * fguess < 0 Then
        lower = guess
        flower = fguess
        guess = 0.5 * lower + 0.5 * upper
        fguess = _
        HW_Coup_Bond(Coup,N,t1,dt,Cal,guess,sigma,kappa,T)-K
    Else
        upper = guess
        fupper = fguess
        guess = 0.5 * lower + 0.5 * upper
        fguess = _
        HW_Coup_Bond(Coup,N,t1,dt,Cal,guess,sigma,kappa,T)-K
    End If
Loop
rstar = guess
'
' Now we calculate the exercise prices and 
' sum the values of the discount bond options
'
For i = 1 To N - 1
    tau = t1 + (i - 1) * dt - T             ' tau = ti - T
    a = hwa(sigma, kappa, tau)              ' a(ti - T)
    b = hwb(kappa, tau)                     ' b(ti - T)
    strike = Cal(i) * Exp(-a - b * rstar)   ' Ki
    sigavg = hwsigavg(sigma,kappa,T,T+tau)  ' sigavg for option i
    x = x + _
    Coup*Vasicek_Discount_Bond_Call(P(i),strike,MatDisc,sigavg,T)
Next i
tau = t1 + (N - 1) * dt - T                 ' tau = tN
a = hwa(sigma, kappa, tau)                  ' a(tN - T)
b = hwb(kappa, tau)                         ' b(tN - T)
strike = Cal(N) * Exp(-a - b * rstar)       ' KN
sigavg = hwsigavg(sigma,kappa,T,T+tau)      ' sigavg for option N
x = x + _
(1+Coup)*Vasicek_Discount_Bond_Call(P(N),strike,MatDisc,sigavg,T)
HW_Coup_Bond_Call = x
End Function
\end{verbatim}\normalsize



# Problems {#problems .unnumbered}
\begin{prob} Modify the function `Vasicek_Cap` so that rather than taking the
vector $P$ of discount bond prices as an input, it "looks up" discount
bond prices from a function `DiscountBondPrice` that returns a discount
bond price for any maturity, as in
Exercise [\[c_fixedincomederivatives\]](#c_fixedincomederivatives){reference-type="ref"
reference="c_fixedincomederivatives"}.[\[exercise121\]](#exercise121){reference-type="ref"
reference="exercise121"}.
\end{prob}\begin{prob} Create a function `ContinuousHoLee_Cap` by modifying the function
`Vasicek_Cap` so that the average volatilities are computed as
$\sigma\varDelta t$. In other words, input $\sigma$ rather than the
vector $\sigma_{\text{avg}}$. Write the function so that it looks up
discount bond prices as in the previous exercise.
\end{prob}\begin{prob} Create a function `ContinuousHoLee_ImpliedVol` using bisection that takes the same inputs as the previous function, except taking a cap price as input rather than $\sigma$, and which returns the volatility $\sigma$ that is consistent with the cap price.\label{e_holeeimplied}
\end{prob}\begin{prob} Create a function `HW_Cap` by modifying the function `Vasicek_Cap` so
that the average volatilities are calculated from
equation [\[vasicekvbacap\]](#vasicekvbacap){reference-type="eqref"
reference="vasicekvbacap"}. Thus, $\sigma$ and $\kappa$ should be input
rather than the vector $\sigma_{\text{avg}}$. Write the function so that
it looks up discount bond prices as in the previous exercises.

\end{prob}\begin{prob} Create an Excel worksheet in which the user inputs $\bar{r}$, $\sigma$
and $\kappa$. Compute the values of caps using the function `HW_Cap` for
caps of length $N = 1, \ldots 20$. Take $t_0=0$ and $\varDelta t=0.5$
and look up discount bond prices. For each $N$, use the Excel solver
tool or the function created in
Exercise [\[c_vasicek\]](#c_vasicek){reference-type="ref"
reference="c_vasicek"}.[\[e_holeeimplied\]](#e_holeeimplied){reference-type="ref"
reference="e_holeeimplied"} to compute the volatility $\sigma$ for which
the `ContinuousHoLee_Cap` function gives the same cap price. In other
words, compute the implied Ho-Lee volatilities, given the cap prices.
What is the pattern in implied volatilities and why?

\end{prob}\begin{prob} Create a VBA function `Vasicek_Floor` to value a floor in the extended
Vasicek model, looking up discount bond prices from the
`DiscountBondPrice` function.
\end{prob}\begin{prob} Modify the function `HW_Coup_Bond_Call` so that it looks up discount
bond prices from the `DiscountBondPrice` function.
\end{prob}\begin{prob} Create a VBA function `HW_Coup_Bond_Put` to value a put option on a
coupon bond in the basic Hull-White Model, looking up discount bond
prices from the `DiscountBondPrice` function.
\end{prob}\begin{prob} Create a VBA function `HW_Payer_Swaption` to value a payer swaption in
the basic Hull-White Model, looking up discount bond prices from the
`DiscountBondPrice` function.
\end{prob}\begin{prob} Create a VBA function `HW_Receiver_Swaption` to value a receiver
swaption in the basic Hull-White Model, looking up discount bond prices
as in previous exercises.
\end{prob}\begin{prob} Repeat Prob. [\[e_eicchorn\]](#e_eicchorn){reference-type="ref"
reference="e_eicchorn"}, assuming the basic Hull-White Model, for
various values of $\sigma$ and $\kappa$.
\end{prob}