{{< include macros.qmd >}}

# Arbitrage Pricing {#sec-c_arbitrage}

This chapter introduces the change of measure (or change of numeraire or martingale)  method for valuing derivative securities.  The method is introduced in a two-state model and then extended to more general (continuum of states) models.  Computations in the more general model require the continuous-time mathematics presented in @sec-c_continuoustime.  

The pricing and hedging results in this book are not tied to any particular currency.  However, for specificity, the discussion will generally be in terms of dollars.  Multiple currencies are addressed in @sec-c_foreignexchange.

## Fundamental Ideas in a Simple Setting {#sec-s_oneperiodbinomial}

We consider in this section the following very simple framework.  \index{binomial model} There is a stock with price $S$ today (which we call date $0$).  At the end of some period of time of length $T$, the stock price will take one of two values: either $S_u$ or $S_d$, where $S_u > S_d$.  If the stock price equals $S_u$ we say we are in the up state of the world, and if it equals $S_d$ we say we are in the down state.  The stock does not pay a dividend prior to $T$.  There is also a risk-free asset earning a continuously compounded rate of interest $r$.  Finally we want to consider a European call option on the stock with maturity $T$ and strike $K$.   A call option gives the owner the right (but not the obligation) to buy the stock at the fixed price called the strike.  The value of this at the option maturity $T$ is the excess of the stock price over $K$ if the excess is positive and is zero otherwise, which we write as $C_u=\max(0,S_u-K)$ in the up state and $C_d=\max(0,S_d-K)$ in the down state. 

We assume
$$
\frac{S_u}{S} > \mathrm{e}^{rT} > \frac{S_d}{S}\;.
$$ {#eq-binomialnoarbitrage}
This condition means that the rate of return on the stock in the up state is greater than the risk-free rate, and the rate of return on the stock in the down state is less than the risk-free rate.  If it were not true, there would be an arbitrage opportunity: \index{arbitrage} if the rate of return on the stock were greater than the risk-free rate in both states, then one should buy an infinite amount of the stock on margin, and conversely if the rate of return on the stock were less than the risk-free rate in both states, then one should short an infinite amount of stock and put the proceeds in the risk-free asset.  So what we are assuming is that there are no arbitrage opportunities in the market for the stock and risk-free asset.

### Option Deltas and Replication 

The delta of the call option is defined to be the difference between the call values in the up and down states divided by the difference between the underlying values; that is, $\delta = (C_u-C_d)/(S_u-S_d)$.  \index{delta} Multiplying by $S_u-S_d$ gives us $\delta(S_u-S_d) = C_u-C_d$ and rearranging yields  $\delta S_u - C_u = \delta S_d-C_d$, which is critical to what follows.  Consider purchasing $\delta$ shares of the stock at date $0$ and borrowing
$$\mathrm{e}^{-rT}(\delta S_u-C_u) = \mathrm{e}^{-rT}(\delta S_d-C_d)$$
dollars at date $0$.  Then you will owe 
$$\delta S_u-C_u = \delta S_d-C_d$$
dollars at date $T$, and hence the value of the portfolio at date $T$ in the up state will be
$$\text{value of delta shares} - \text{dollars owed} = \delta S_u - (\delta S_u-C_u) = C_u\; ,$$
and the value of the portfolio at date $T$ in the down state will be
$$\text{value of delta shares} - \text{dollars owed} = \delta S_d - (\delta S_d-C_d) = C_d\;\;.$$
Thus, this portfolio of buying delta shares and  borrowing money (i.e., buying delta shares on margin) replicates the call option.  \index{replicating strategy} \index{delta hedge} Consequently, the value $C$ of the option at date $0$ must be the date--0 cost of the portfolio; i.e.,
$$
C = \text{cost of delta shares} - \text{dollars borrowed}$$
$$ = \delta S - \mathrm{e}^{-rT}(\delta S_u-C_u)\;.
$$ {#eq-C0}


### State Prices

We now rewrite the option pricing @eq-C0 in terms of what are called state prices. \index{state price}
By substituting for $\delta$ in @eq-C0, we can rearrange it as


$$
C = \frac{S-\mathrm{e}^{-rT}S_d}{S_u-S_d} \times C_u + \frac{\mathrm{e}^{-rT}S_u-S}{S_u-S_d}\times C_d\; .
$$ {#eq-binomialC1}

A little algebra also shows that
$$
S = \frac{S-\mathrm{e}^{-rT}S_d}{S_u-S_d} \times 
S_u + \frac{\mathrm{e}^{-rT}S_u-S}{S_u-S_d}\times S_d\; ,
$$ {#eq-binomialS1}

and
$$
1 = \frac{S-\mathrm{e}^{-rT}S_d}{S_u-S_d} \times \mathrm{e}^{rT}+ \frac{\mathrm{e}^{-rT}S_u-S}{S_u-S_d}\times \mathrm{e}^{rT}\;.
$$ {#eq-binomialR1}


It is convenient to denote the factors appearing in these equations as
$$
\pi_u = \frac{S-\mathrm{e}^{-rT}S_d}{S_u-S_d} \quad \text{and} \quad \pi_d = \frac{\mathrm{e}^{-rT}S_u-S}{S_u-S_d}\;.
$$ {#eq-binomialstateprices}

The numbers $\pi_u$ and $\pi_d$ are called the state prices, for reasons that will be explained below.

With these definitions, we can write @eq-binomialC1--@eq-binomialR1 as

$$
C = \pi_uC_u + \pi_dC_d\;,
$$ {#eq-binomialC2}

$$
S = \pi_uS_u+\pi_dS_d\;,
$$ {#eq-binomialS2}

$$
1 = \pi_u\mathrm{e}^{rT} + \pi_d \mathrm{e}^{rT}\;.
$$ {#eq-binomialR2}


These equations have the following interpretation: the value of a security today is its value in the up state times $\pi_u$ plus its value in the down state times $\pi_d$.  This applies to @eq-binomialR2 by considering an investment of \$1 today in the risk-free asset---it has value 1 today and will have value $\mathrm{e}^{rT}$ in both the up and down states at date $T$.  Moreover, this same equation holds for any other derivative asset -- for example, a put option -- for the same $\pi_u$ and $\pi_d$ defined in @eq-binomialstateprices.  

In this model, we can think of any security as a portfolio of what are called Arrow securities (in recognition of the seminal work of Kenneth Arrow [@Arrow]).  \index{Arrow security} One of the Arrow securities pays \$1 at date $T$ if the up state occurs and the other pays \$1 at date $T$ if the down state occurs.  For example, the stock is equivalent to a portfolio consisting of $S_u$ units of the first Arrow security and $S_d$ units of the second, because the stock is worth $S_u$ dollars in the up state and $S_d$ dollars in the down state.   @eq-binomialC2--@eq-binomialR2 show that~ $\pi_u$ is the price of the first Arrow security and $\pi_d$ is the price of the second.  For example, the right-hand side of @eq-binomialS2 is the value of the stock at date $0$ viewed as a portfolio of Arrow securities when the Arrow securities have prices $\pi_u$ and $\pi_d$.  Because the stock clearly is such a portfolio, its price today must equal its value as that portfolio, which is what @eq-binomialS2 asserts.

As mentioned before, the prices $\pi_u$ and $\pi_d$ of the Arrow securities are called the state prices, because they are the prices of receiving \$1 in the two states of the world.  The state prices should be positive, because the payoff  of each Arrow security is nonnegative in both states and positive in one.  A little algebra shows that the conditions $\pi_u>0$ and $\pi_d>0$  are exactly equivalent to our no-arbitrage assumption @eq-binomialnoarbitrage.  Thus, we conclude that 

::: Principle
In the absence of arbitrage opportunities, there exist positive state prices such that the price of any security is the sum across the states of the world of its payoff multiplied by the state price.
:::

This conclusion generalizes to other models, including models in which the stock price takes a continuum of possible values.  We discuss more general models later in this chapter.  It is a powerful result that tremendously simplifies derivative security pricing.  

### Risk-Neutral Probability

To apply the statement about state prices appearing in boldface type above in the most convenient way, we manipulate the state prices  so we can interpret the sums on the right-hand sides of  @eq-binomialC2--@eq-binomialR2 in terms of  expectations.  \index{expectation} The expectation (or mean) of a random variable is of course its probability-weighted average value.

Set $p_u = \pi_u\mathrm{e}^{rT}$ for the up state and $p_d = \pi_d\mathrm{e}^{rT}$ for the down state. @eq-binomialC2--@eq-binomialR2 can be written as

$$
C = \mathrm{e}^{-rT}[p_uC_u+p_dC_d]\;,
$$ {#eq-binomialC3}

$$
S = \mathrm{e}^{-rT}[p_uS_u+p_dS_d]\;,
$$ {#eq-binomialS3}

$$
1= p_u+p_d\;.
$$ {#eq-binomialR3}


The numbers $p_u$ and $p_d$ are called the risk-neutral probabilities of the up and down states.  The numbers are both positive (because the state prices are positive under our no-arbitrage assumption) and @eq-binomialR3 states that they sum to one, so it is indeed sensible to consider them as (artificial) probabilities.
 @eq-binomialC3 and @eq-binomialS3 state that the value of a security today is its expected value at date $T$ (the expectation taken with respect to the risk-neutral probabilities) discounted at the risk-free rate.  Thus, these are present value formulas.  Unlike the Capital Asset Pricing Model, for example, there is no risk premium in the discount rate.  This is the calculation we would do to price assets under the actual probabilities if investors were risk neutral (or for zero-beta assets).  So, we can act as if investors are risk neutral by adjusting the probabilities.^[This fundamental idea is due to Cox and Ross [@CR].]  Of course, we are not really assuming investors are risk neutral.  We have simply embedded any risk premia in the probabilities.

### Martingales

 @eq-binomialC3 and @eq-binomialS3 can be written in an equivalent form, which, though somewhat less intuitive, generalizes more readily.  First, let's introduce some notation for the price of the risk-free asset.  Considering an investment of \$1 today which grows to $\mathrm{e}^{rT}$ at date $T$, it is sensible to take the price today to be $R=1$ and the price in the up and down states at date $T$ to be $R_u=R_d=\mathrm{e}^{rT}$.^[All of the equations appearing below  are also true if instead we take $R=\mathrm{e}^{-rT}$ and $R_u=R_d=1$.]  In terms of this notation,  @eq-binomialC3--@eq-binomialR3 can be written as:

$$
\frac{C}{R} = p_u \frac{C_u}{R_u} + p_d \frac{C_d}{R_d}\;, 
$$ {#eq-binomialC4}

$$
\frac{S}{R} = p_u \frac{S_u}{R_u} + p_d \frac{S_d}{R_d}\;, 
$$ {#eq-binomialS4}

$$
1=p_u+p_d\;.
$$ {#eq-binomialR4}


@eq-binomialC4 and @eq-binomialS4 each state that the price of a security today divided by the price of the risk-free asset equals the expected future value of the same ratio, when we take expectations using the risk-neutral probabilities.  In other words, the mean of the date--$T$ value of the ratio is equal to the ratio today.  
A variable that changes randomly over time with the expected future value being always equal to the current value is called a martingale.  Thus, we have shown that the ratio of the stock price to the price of the risk-free asset is a martingale when using the risk-neutral probabilities.

The ratio of one price to another is the value of the first (numerator) asset  when we are using the second (denominator) asset  as the numeraire.  \index{numeraire} The term numeraire means a unit of measurement.  For example, the ratio $C/R$ is the value of the call when we use the risk-free asset as the unit of measurement: it is the number  of units of the risk-free asset for which one call option can be exchanged (to see this, note that $C/S$ shares is worth $C/R \times R = C$ dollars, so $C/R$ units of the risk-free asset is worth the same as one call). Thus, we have shown that asset prices using the risk-free asset as numeraire are martingales relative to the risk-neutral probabilities.

### Other Numeraires

Note that the risk-neutral probabilities are the state prices multiplied by the gross return on the risk-free asset.  Analogously, define numbers $q_u = \pi_uS_u/S$ and $q_d = \pi_dS_d/S$.  Substituting for $\pi_u$ and $\pi_d$ in  @eq-binomialC2--@eq-binomialR2 and continuing to use the notation $R$ for the price of the risk-free asset, we obtain

$$
\frac{C}{S} = q_u \frac{C_u}{S_u} + q_d \frac{C_d}{S_d}\;, 
$$ {#eq-binomialC5}

$$
1 = q_u + q_d\;,
$$ {#eq-binomialS5}

$$
\frac{R}{S} = q_u \frac{R_u}{S_u} + q_d \frac{R_d}{S_d}\;. 
$$ {#eq-binomialR5}


@eq-binomialS5 establishes that we can view the $q$'s as probabilities (like the risk-neutral probabilities, they are positive because the state prices are positive).   @eq-binomialC5 and @eq-binomialR5 both state that the ratio of a security price to the price of the stock is a martingale when we use the $q's$ as probabilities.  Thus, asset prices using the stock as numeraire are martingales when we use the $q$ probabilities.

An assignment of probabilities to events is called a probability measure, or simply a measure (because it measures the events, in a sense).  Thus, we have described two different probability measures: one using the risk-free asset as numeraire and one using the stock as numeraire.  The probability measure using the risk-free asset as numeraire defined in the previous section is universally called the risk-neutral probability.  When we use one of these probabilities, we commonly say that we are changing numeraires.

::: Principle
If there are no arbitrage opportunities, then for each (non-dividend-paying) asset, there exists a probability measure  such that the ratio of any other (non-dividend-paying) asset price to the first (numeraire) asset price is a martingale.
:::

We have applied this statement to the risk-free asset, which pays dividends (interest).  However, the price $R_u=R_d=\mathrm{e}^{rT}$ includes the interest, so no interest has been withdrawn---the interest has been reinvested---prior to the maturity $T$ of the option.  This is what we mean by a non-dividend-paying asset.  In general, we apply the formulas developed in this and the following section to dividend-paying assets by considering the portfolios in which dividends are reinvested.

### Practical Implementation

For this exposition, it was convenient to first calculate the state prices and then calculate the various probabilities.  However, that is not the most efficient way to proceed in most applications.  In a typical application, we would view the prices of the stock and risk-free asset in the various states of the world as given, and we would be attempting to compute the value of the call option.  Note that t @eq-binomialC2--@eq-binomialR2, @eq-binomialC4--@eq-binomialR4, and @eq-binomialC5--@eq-binomialR5 are all equivalent.  In each case we would consider that there are three unknowns---the value $C$ of the call option and either two state prices or two probabilities.  In each case the state prices or probabilities can be computed from the last two equations in the set of three equations and then the call value $C$ can be computed from the first equation in the set.  All three sets of equations produce the same call value.  

In fact, as we will see, it is not even necessary to calculate the probabilities.  The fact  that ratios of non-dividend paying asset prices to the numeraire asset price are martingales tell us enough about the probabilities to calculate derivative values without having to calculate the probabilities themselves.

### Stochastic Discount Factor 

We now consider yet another reformulation of the pricing relations @eq-binomialC2--@eq-binomialR2.  This formulation generalizes more easily to pricing when there are a continuum of states.  
Let $\text{prob}_u$ denote the actual probability of the up state and $\text{prob}_d$ denote the probability of the down state.  These probabilities are irrelevant for pricing derivatives in the two-state up-and-down model, but we use them to write the pricing relations @eq-binomialC2--@eq-binomialR2 as expectations with respect to the actual probabilities.  To do this, we can define
\begin{align*}
m_u &= \frac{\pi_u}{\text{prob}_u}\; ,\\
m_d &= \frac{\pi_d}{\text{prob}_d}\;.
\end{align*}
Then @eq-binomialC2--@eq-binomialR2 can be written as

$$
C = \text{prob}_um_uC_u + \text{prob}_dm_dC_d\;,
$$ {#eq-binomialC6}

$$
S = \text{prob}_um_uS_u + \text{prob}_dm_dS_d\;,
$$ {#eq-binomialS6}

$$
R = \text{prob}_um_uR_u + \text{prob}_dm_dR_d\;.
$$ {#eq-binomialR6}


The right-hand sides are expectations with respect to the actual probabilities.  For example, the right-hand side of @eq-binomialC6 is the expectation of the random variable that equals $m_uC_u$ in the up state and $m_dC_d$ in the down state.  The risk-neutral probabilities can be calculated from $m_u$ and $m_d$ as
$p_u=\text{prob}_um_uR_u/R$ and $p_d=\text{prob}_dm_dR_d/R$.  Likewise, the probabilities using the stock as the numeraire can be calculated from $m_u$ and $m_d$ as
$q_u=\text{prob}_um_uS_u/S$ and $q_d=\text{prob}_dm_dS_d/S$.  

We call the random variable $m$ the stochastic discount factor.  @eq-binomialS6--@eq-binomialR6 show that we can calculate an asset value as the expectation of its future value discounted (multiplied) by the the stochastic factor $m$.

## More General Models

Now, we drop the assumption that there are only two possible future prices of the stock and allow a general distribution with potentially a continuum of possible values.  Denote the future price as $S(T)$.   Our principle regarding the stochastic discount factor developed in the preceding section can in general be expressed as:^[We have proven this in the two-state model, but we will not prove it in general.  As is standard in the literature, we simply adopt it as an assumption.  A general proof is in fact difficult and requires a definition of no arbitrage that is considerably more complicated than the simple assumption @eq-binomialnoarbitrage that is sufficient in thetwo-state up-and-down model.] 

::: Principle
If there are no arbitrage opportunities, then there exists for each date $T$ a positive random variable $m(T)$ such that the date--$0$ value of any non-dividend-paying security with price $P$ is 
$$
P(0) = E[m(T)P(T)]\;.
$$ {#eq-continuum1}
:::

Here, $E[m(T)S(T)]$ denotes the expectation of the random variable $m(T)S(T)$.  The random variable $m(T)$ is the stochastic discount factor.  In a two-state model (or in any model with only a finite number of states of the world), the concept of an expectation is clear: it is just a weighted average of outcomes, the weights being the probabilities.  In the two-state model, the right-hand side of @eq-binomialS6 is the same as the right-hand side of @eq-continuum1.^[
In general the expectation (or mean) of a random variable is an intuitive concept, and an intuitive understanding  is sufficient for this book, so we will not give a formal definition.  It should be understood that we are assuming implicitly, whenever necessary, that the expectation exists (which is not always the case).  In this regard, it is useful to note in passing that a product of two random variables $XY$ has a finite mean whenever $X$ and $Y$ have finite variances.]  


To convert from state prices to probabilities corresponding to different numeraires, we follow the same procedure as at the end of the previous section: we multiply together (i) the probability of the state, (ii) the value of $m(T)$ in the state, and (iii)  the gross return of the numeraire in the state.  If there is a continuum of states, then the actual probability of any individual state is typicallt zero, so this multiplication produces a zero probability.  However, we can nevertheless add up these probabilities to define the probability of any event $A$, an event being a set of states of the world.  To do this, let $1_A$ denote the random variable that takes the value 1 when $A$ is true and which is zero otherwise.  Then the probability of $A$ using $S$ as the numeraire is defined as \index{change of measure} \index{change of numeraire}
$$
E\left[1_Am(T)\frac{S(T)}{S(0)}\right]\;.
$$ {#eq-probSnumeraire}

This makes sense as a probability because it is nonnegative and because, if $A$ is the set of all states of the world, then its probability is  $E[m(T)S(T)/S(0)]$, which equals one by virtue of @eq-continuum1.  From @eq-probSnumeraire of the probability of any event $A$, it can be shown that the expectation of any random variable $X$ using $S$ as the numeraire is
$$
E\left[Xm(T)\frac{S(T)}{S(0)}\right]\;.
$$ {#eq-expSnumeraire}


Different numeraires lead to different probability measures and hence to different expectations.  To keep this straight, we use the numeraire as a superscript on the expectation symbol: for example, $E^S$ denotes expectation with respect to the probability measure that corresponds to $S$ being the numeraire.  Also, we use the symbol $\text{prob}^S(A)$ to denote the probability of an event $A$ when we use $S$ as the numeraire.  So, @eq-probSnumeraire and @eq-expSnumeraire are written as 

$$
\text{prob}^S(A) = E\left[1_Am(T)\frac{S(T)}{S(0)}\right]\;,
$$ {#eq-probSnumeraire2}

$$
E^S[X] = E\left[Xm(T)\frac{S(T)}{S(0)}\right]\;.
$$ {#eq-expSnumeraire2}


### Fundamental Pricing Formula

Our key result in the two-state up-and-down example considered earlier was that the ratio of the price of any non-dividend paying asset to the price of the numeraire asset is not expected to change when we use the probability measure corresponding to the numeraire.  We now demonstrate the same result in this more general model.   Recall that $T$ denotes an arbitrary but fixed date at which we have defined the probabilities using $S$ as the numeraire in @eq-probSnumeraire.  At each date $t<T$, let $E^P_t$ denote the expectation given information at time $t$ and using a non-dividend-paying asset price $P$ as the numeraire (we continue to write the expectation at date $0$ without a subscript; i.e., $E^S$ has the same meaning as $E^S_0$).  Let $Y$ denote the price of another non-dividend-paying asset.  We will show that
$$
\frac{Y(t)}{P(t)} = E^P_t \left[\frac{Y(T)}{P(T)}\right]\;.
$$ {#eq-preformula}

Thus, the expected future (date--$T$) value of the ratio $Y/S$ always equals the current (date--$t$) value when we use $S$ as the numeraire.  As discussed in the preceding section, the mathematical term for a random variable whose expected future value always equals its current value is martingale.  Thus, we can express @eq-preformula as stating that the ratio $Y/P$ is a martingale when we compute expectations using the probability measure that corresponds to $S$ being the numeraire.

The usefulness of @eq-preformula is that it gives us a formula for the asset price $Y(t)$ at any time $t$---and recall that this formula holds for every non-dividend paying asset.  The formula is obtained from @eq-preformula by multiplying through by $P(t)$:

::: Principle
In the absence of arbitrage opportunities, prices $P$ and $Y$ of non-dividend-paying assets satisfy
$$
Y(t) = P(t)E^P_t \left[\frac{Y(T)}{P(T)}\right]\;.
$$ {#eq-formula}
:::

We call @eq-formula the fundamental pricing formula. \index{fundamental pricing formula}
It is at the heart of modern pricing of derivative securities.  It is a present value relation: the value at time $t$ of the asset with price $Y$ is the expectation, under the appropriate probability measure, of its value $Y(T)$ at time $T$ discounted by the (possibly random) factor $P(t)/P(T)$.  

For example, letting $P(t) = R(t)$ denote the value $\mathrm{e}^{rt}$ of the risk-free asset and using it as the numeraire, @eq-formula becomes
$$
Y(t) = \mathrm{e}^{rt}E^R_t\left[\frac{Y(T)}{\mathrm{e}^{rT}}\right] = \mathrm{e}^{-r(T-t)}E^R_t [Y(T)]\;,
$$ {#eq-riskneutralformula}

which means that the value $Y(t)$ is the expected value of $Y(T)$ discounted at the risk-free rate for the remaining time $T\!-\!t$, when the expectation is computed under the risk-neutral probability.


We end this section with a proof of @eq-preformula, a proof that the reader may skip if desired.^[The proof is due to Harrison and Kreps [@HK].  See also Geman, El Karoui and Rochet [@GKR].  We omit here technical assumptions regarding the existence of expectations.]  

::: Extra

 Consider any time $t$ and any event $A$ that is distinguishable by time $t$.  Consider the trading strategy of buying one share of the asset with price $Y$ at time $t$ when $A$ has happened and financing this purchase by short selling $Y(t)/P(t)$ shares of the asset with price $P$.  Each share of this asset that you short brings in $P(t)$ dollars, so shorting $Y(t)/P(t)$ shares brings in $Y(t)$ dollars, exactly enough to purchase the desired share of the first asset.  Hold this portfolio until time $T$ and then liquidate it.  Liquidating it s 
$$1_A\left(Y(T)-\frac{Y(t)}{P(t)}P(T)\right)$$
dollars.  The multiplication by the random variable $1_A$ is because we only implement this strategy when $A$ occurs (i.e., when $1_A=1$).  Consider the security that pays this number of dollars at time $T$.  Because we obtained it with a trading strategy that required no investment at time $t$, its price at time 0 must be 0.  We already observed that we can represent the price in terms of state prices, so we conclude that
$$E \left[m(T)1_A\left(Y(T)-\frac{Y(t)}{P(t)}P(T)\right)\right] = 0\;\;.$$
When we divide by $P(0)$, this still equals zero.  Factoring $P(T)$ outside the parentheses gives
$$E \left[1_A\frac{P(T)}{P(0)}m(T)\left(\frac{Y(T)}{P(T)}-\frac{Y(t)}{P(t)}\right)\right] = 0\;\;.$$
We see from @eq-expSnumeraire2 for expectations using $P$ as the numeraire that we can write this as
$$E^P\left[1_A\left(\frac{Y(T)}{P(T)}-\frac{Y(t)}{P(t)}\right)\right]=0\;.$$
This is true for any event $A$ distinguishable at time $t$, so the expectation of $Y(T)/P(T)-Y(t)/P(t)$ must be zero given any information at time $t$ when we use $P$ as the numeraire; i.e.,
$$E^P_t\left[\frac{Y(T)}{P(T)}-\frac{Y(t)}{P(t)}\right]=0\; ,$$
or, equivalently
$$E^P_t\left[\frac{Y(T)}{P(T)}\right] = \frac{Y(t)}{P(t)}\;.$$
:::



## Exercises


::: {.Exercise #e_binomialcall}
 
 
Create a Python function in which the user inputs $S$, $S_d$, $S_u$, $K$, $r$ and $T$.  Check that the no-arbitrage condition @eq-binomialnoarbitrage is satisfied.  Compute the value of a call option in each of the following ways:

1. Compute the delta and use  @eq-C0.
2. Compute the state prices and use  @eq-binomialC2.
3. Compute the risk-neutral probabilities and use  @eq-binomialC3.
4. Compute the probabilities using the stock as numeraire and use  @eq-binomialC5.

Verify that all of these methods produce the same answer.
:::

::: Exercise
 
In a two-state model, a put option is equivalent to $\delta_p$ shares of the stock, where $\delta_p = (P_u-P_d)/(S_u-S_d)$ (this will be negative, meaning a short position) and some money invested in the risk-free asset.  Derive the amount of money $x$ that should be invested in the risk-free asset to replicate the put option.  The value of the put at date $0$ must  be $x+\delta_pS$.
:::

::: Exercise

Using the result of the previous exercise, repeat Problem~\ref{e_binomialcall} for a put option.
:::

