# Forward, Futures, and Exchange Options {#c_forwardexchange}

In this chapter, we will derive three important generalizations of the
Black-Scholes formula. We will derive them from the Black-Scholes
formula, which shows that all of the formulas are equivalent. We will
start with Margrabe's [@Margrabe] formula for an option to exchange one
asset for another. Standard calls and puts are special cases, involving
the exchange of cash for an asset or an asset for cash. From Margrabe's
formula, we will derive Black's [@Black] formulas for options on forward
and futures contracts. Then, from Black's formulas, we will derive
Merton's [@Merton] formulas for calls and puts in the absence of a
constant risk-free rate.

Unless explicitly stated otherwise, we will not assume in this chapter
the existence of a risk-free asset (or even an instantaneously risk-free
asset as described in
Sect. [\[s_continuouscompounding\]](#s_continuouscompounding){reference-type="ref"
reference="s_continuouscompounding"}). This implies that the market is
incomplete and there are many risk-neutral measures. Nevertheless, we
can price exchange options, forward and futures options, and stock
options by arbitrage. Understanding this issue is not essential for
deriving the formulas in this chapter---as mentioned, they will all be
derived from the Black-Scholes formula---but the issue is nonetheless
important. It is discussed in the final section of the chapter.

Naturally, all of the option-pricing formulas discussed in this chapter are quite similar.  The similarity can be seen from the Black-Scholes formula for a call option, which we can write as follows (replacing $d_1$ by $x$ and $d_2$ by $y$):
\begin{subequations}\begin{equation}\label{blackscholesagain}
\E^{-qT}S(0)\N(x) - \E^{-rT}K\N(y)\;,
\end{equation}
where
\begin{align} 
x&=\frac{\log\left(\frac{S(0)}{K}\right)+\left(r-q+\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\label{d1again}\\
y &= x -\sigma\sqrt{T}\;.\label{d2again}
\end{align}\end{subequations}
Note that $\E^{-qT}S(0)$ is the present value at date 0 of the stock that would be acquired if the option is exercised, because it is the cost that one must pay at date 0 to have one share of the stock at date $T$ with no withdrawal of dividends in the interim.  Obviously, $\E^{-rT}K$ is the present value of the cash that is paid if the option is exercised.  Moreover, $x$ is equal to
$$\frac{\log \left(\frac{\E^{-qT}S(0)}{\E^{-rT}K} \right)+ \frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\; ,$$
and the logarithm in the numerator is of the ratio of present values.  All of the option pricing formulas in this chapter have the same form:  the present value of the asset to be acquired multiplied by $\N(x)$ minus the present value of the asset to be delivered multiplied by $\N(y)$.  Moreover in each case $x$ is the logarithm of the ratio of present values plus one-half $\sigma^2T$ all divided by $\sigma\sqrt{T}$, and in each case $y$ is defined by \eqref{d2again}.  Notice that the Black-Scholes put option formula has this structure also.  The Black-Scholes put option formula is
\begin{subequations}\begin{equation}\label{blackscholesputagain}
\E^{-rT}K\N(x) - \E^{-qT}S(0)\N(y)\;,
\end{equation}
where
\begin{align}
x &=-d_2\notag
\\& =  - \frac{\log\left(\frac{S(0)}{K}\right)+\left(r-q-\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\notag\\
&=\frac{\log \left(\frac{\E^{-rT}K}{\E^{-qT}S(0)} \right)+ \frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\;,\label{d2again2}\\
y&=-d_1\notag
\\& = - \frac{\log\left(\frac{S(0)}{K}\right)+\left(r-q+\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\notag\\
&=x - \sigma\sqrt{T}\;.
\end{align}\end{subequations}
This similarity is discussed further in Sect.~\ref{s_matlabimplementations}, where the pricing formulas are implemented in VBA.



# Margrabe's Formula {#s_margrabe}

Consider two assets with prices $S_1$ and $S_2$ and a European option to exchange asset 2 for asset 1 at date $T$.  The value of the option at maturity is
$$\max(0,S_1(T)-S_2(T))\; .$$
Note that there is no real difference between a put and a call: the
exchange option can be viewed as a call on the first asset with random
strike $S_2(T)$ or as a put on the second asset with random strike
$S_1(T)$.

Assume the assets pay constant dividend yields $q_i$ and assume the prices satisfy
$$\frac{\D S_i}{S_i} = \mu_i\,\D t+\sigma_i\,\D B_i$$
where each $B_i$ is a Brownian motion under the actual probability measure.  As before, the drifts $\mu_i$ can be quite general random processes.  We also allow the volatilities $\sigma_i$ and the correlation $\rho$ of the Brownian motions to be random processes; however, we make the assumption that $\sigma$ defined as
\begin{equation}\label{margrabesigma}
\sigma = \sqrt{\sigma_1^2 + \sigma_2^2 - 2\rho\sigma_1\sigma_2}
\end{equation}
is a constant.  As shown in \eqref{volatilityratio}, $\sigma$ is the volatility of $S_1/S_2$ (and also $S_2/S_1$).  So, the assumption we are making is that the volatility of the ratio of the asset prices is constant.  In Sect.~\ref{s_volatility}, we will relax this assumption to allow $\sigma$ to be time-varying (though still non-random).  

The following is the formula of Margrabe [@Margrabe]:

\mybox{The value of a European option to exchange two assets at date $T$  is
\begin{subequations}\begin{equation}\label{margrabeoption}
\E^{-q_1 T}S_1(0)\N(d_1)-\E^{-q_2 T}S_2(0)\N(d_2)\;,
\end{equation}
where 
\begin{align}
d_1&= \frac{\log\left(\frac{S_1(0)}{S_2(0)}\right)+\left(q_2-q_1+
\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\;,\label{margrabe_d1}\\
d_2&=d_1-\sigma\sqrt{T}\;,\label{margrabe_d2}
\end{align}\end{subequations}
}

Margrabe's derivation is a very simple argument based on the
Black-Scholes formula. We noted in
Chap. [\[c_foreignexchange\]](#c_foreignexchange){reference-type="ref"
reference="c_foreignexchange"} that the Black-Scholes formula does not
depend on the currency---if the underlying asset and risk-free asset are
dollar denominated, the formula gives the dollar value of an option; if
they are yen denominated, the formula gives the yen value of an option,
etc. So we can take the "currency" to be units of the second asset;
i.e., we will use the second asset as numeraire. With this numeraire,
the value of the first asset is $S_1/S_2$. The value of the exchange
option at maturity is
$$\max(0,S_1(T)-S_2(T)) = S_2(T)\max\left(0,\frac{S_1(T)}{S_2(T)}-1\right)\; .$$
This is the value in the natural currency (e.g., dollars).  The value using the second asset as numeraire is obtained by dividing by $S_2(T)$, so it is
$$\max\left(0,\frac{S_1(T)}{S_2(T)}-1\right)\; .$$
This is the value of a standard call option, the underlying being the
first asset measured in units of the second. We can apply the
Black-Scholes formula to obtain the value of the option (in units of the
second asset) at date 0. Multiplying this value by $S_2(0)$ will give
the option value in the natural currency.

The risk-free rate when the second asset is the numeraire is the
dividend yield on the second asset $q_2$. To see this, note that the
price of the second asset is always equal to one; moreover, an
investment in the second asset will accumulate at the rate $q_2$ via
reinvestment of dividends. Therefore, $q_2$ is a risk-free rate of
return.

The dividend yield on the first asset remains $q_1$. To see this, note
that the dividend paid in the natural currency is $q_1S_1(t)\,\D t$ in
an instant $\D t$ and the value of this dividend using the second asset
as numeraire is $[q_1S_1(t)/S_2(t)]\,\D t$, which is the fraction
$q_1\,\D t$ of the value $S_1(t)/S_2(t)$ of the first asset using the
second asset as numeraire.

The volatility of the first asset using the second as numeraire is the
volatility of the ratio $S_1(t)/S_2(t)$, which is $\sigma$ defined in
[\[margrabesigma\]](#margrabesigma){reference-type="eqref"
reference="margrabesigma"}. Applying the Black-Scholes formula with
these inputs yields Margrabe's formula directly.[^1]

[^1]: Of course, it is possible to give a direct proof, without relying
    on the Black-Scholes formula. A sketch is given in
    Sect. [\[s_margrabecomplete\]](#s_margrabecomplete){reference-type="ref"
    reference="s_margrabecomplete"}.

# Black's Formula {#s_black}
Black [@Black] gives formulas for the values of options on futures
contracts when interest rates are deterministic (i.e., non-random). It
is well known (and we will establish this in
Sect. [\[s_futuresforwards\]](#s_futuresforwards){reference-type="ref"
reference="s_futuresforwards"}) that, when interest rates are
deterministic, futures prices should equal forward prices, so Black's
formulas also yield formulas for the values of options on forward
contracts when interest rates are deterministic. However, the formulas
for options on forwards are valid more generally (even when interest
rates vary randomly) and now a mention of Black's formulas is more
likely to be referring to the formulas for options on forwards, instead
of the formulas for options on futures. In any case, we will start with
the formulas for options on forwards and then in
Sect. [\[s_futuresoptions\]](#s_futuresoptions){reference-type="ref"
reference="s_futuresoptions"} derive the formulas for options on futures
when interest rates are deterministic.

We consider a forward contract that matures at some date $T'$ and a call
or put option on the forward that matures at $T \leq T'$. The meaning of
a call option on a forward is that exercise of the call creates a long
position in the forward contract with forward price equal to the strike
price of the option. The long forward contract means that the investor
will receive the underlying asset at $T'$ and pay the forward price (the
strike of the option) at $T'$. Thus, the strike price is not paid at the
date of exercise but instead is paid when the underlying asset is
delivered. Symmetrically, the exercise of a put creates a short position
in the forward contract with forward price equal to the strike of the
put, which means that the exerciser must deliver the underlying at $T'$
and will receive the strike price at $T'$.

We will denote the market forward price by $F(t)$.  We assume the forward price satisfies
\begin{equation}\label{dforward}
\frac{\D F}{F} = \mu\,\D t + \sigma\,\D B\;,
\end{equation}
where $B$ is a Brownian motion. As before, $\mu$ can be a quite general
random process. We will assume in this section that the volatility
$\sigma$ is a constant and generalize to a time-varying (but non-random)
volatility in
Sect. [\[s_volatility\]](#s_volatility){reference-type="ref"
reference="s_volatility"}. In
Sect. [\[s_merton\]](#s_merton){reference-type="ref"
reference="s_merton"}, we will discuss the relations of the forward
price and its volatility to the price and volatility of the underlying.

Black's formulas are particularly useful when interest rates are assumed
to be random, as we will see in
Part [\[p_fixedincome\]](#p_fixedincome){reference-type="ref"
reference="p_fixedincome"} of the book when we study fixed income
derivatives. Therefore, we do not assume here that there is a constant
risk-free rate. Instead we will assume that there is a "discount bond"
that pays \$1 at date $T'$. It is called a "discount bond" because its
price is the appropriate discount factor for computing the present value
of nonrandom cash flows at date $T'$. Such a bond is also called a "zero
coupon" bond because it does not pay any cash flows until $T'$, when it
pays its face value (which we take simply for convenience to be \$1). We
will let $P(t,T')$ denote the price of the bond at date $t$.[^1]

[^1]: In this section we could drop the $T'$ in $P(t,T')$ and simply
    write $P(t)$, because we only consider one maturity date, but we
    will use the same notation when discussing multiple maturities in
    Part [\[p_fixedincome\]](#p_fixedincome){reference-type="ref"
    reference="p_fixedincome"}.

Black's formulas are:
\mybox{The values at date 0 of European options with strike $K$ and maturity $T$  on a forward contract with maturity $T'$ are
\begin{subequations}\label{blackcombined}\begin{align}
\text{Call Price} &=P(0,T')F(0)\N(d_1)-P(0,T')K\N(d_2)\label{black}\; ,\\
\text{Put Price} &=P(0,T')K\N(-d_2)-P(0,T')F(0)\N(-d_1)\label{black_put}\; ,\\
\intertext{where}
d_1&= \frac{\log\left(\frac{F(0)}{K}\right)+\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\;,\label{black_d1}\\
d_2&=d_1-\sigma\sqrt{T}\;.\label{black_d2}
\end{align}\end{subequations}}

Black's formulas are a simple consequence of Margrabe's formula. To see
this, we first need to describe the value of an option on a forward at
the maturity date $T$ of the option. Consider a call option. Exercise of
the call results in a long forward position with forward price $K$. The
value of the long forward is given by its market price $F(T)$, but we
must keep in mind that the forward price is not paid until the
underlying is delivered at date $T'$. So suppose that you exercise the
call and then sell a forward contract at the market forward price
$F(T)$. The delivery/receipt obligations of the long and short forwards
cancel, leaving you with the obligation to pay $K$ dollars at date $T'$
and with an asset of $F(T)$ dollars to be received at date $T'$. The
value of the net cash flow at date $T$ is $P(T,T')[F(T)-K]$. This is the
value if exercised, so the value of the call at date $T$ is

\begin{equation}\label{blackcallexchange1}
\max\big(0, P(T,T')[F(T)-K]\big) = \max\big(0,P(T,T')F(T)-P(T,T')K\big)\;.\end{equation}
We can write this as
\begin{equation}\label{blackcallexchange2}
\max(0,S_1(T)-S_2(T))
\end{equation}
if we define
\begin{equation}\label{blackexchange}
S_1(t) = P(t,T')F(t) \quad \text{and} \quad S_2(t) = P(t,T')K
\end{equation}
for $t=T$ (and more generally for $t \leq T$).  Thus, the value at maturity of a call option on a forward is the value at maturity of an option to exchange the two assets with prices $S_1$ and $S_2$ (we will establish in a moment that $S_1$ and $S_2$ are actually asset prices).  It follows that the value at date 0 of a call option on a forward is the value at date 0 of an option to exchange the two assets.

Now consider a put option on a forward.  Exercising the put and unwinding the short forward position by buying a forward at the market price $F(T)$ will leave one with a net cash flow of $K-F(T)$ to be received at the maturity date $T'$ of the forward.  Therefore the value of the put at maturity is
\begin{equation}\label{blackputexchange}
\max(0,P(T,T')[K-F(T)]) = \max(S_2(T)-S_1(T))\;.
\end{equation}
Therefore, the value at date 0 of the put option on a forward must be
the value at date 0 of an exchange option, where asset one in
[\[blackexchange\]](#blackexchange){reference-type="eqref"
reference="blackexchange"} is exchanged for asset two.

The key assumption in deriving Margrabe's formula is that the volatility
of the ratio of asset prices is a constant. For a call option on a
forward, the relevant ratio is $S_1/S_2 = F/K$. Because $K$ is a
constant, the volatility of the ratio is the volatility $\sigma$ of the
forward price $F$, which we have assumed to be constant. For a put
option on a forward, the relevant ratio is $S_2/S_1 = K/F$. Itô's
formula implies
\begin{align*}
\frac{d(K/F)}{K/F} &= -\frac{\D F}{F} + \left(\frac{\D F}{F}\right)^2\; ,\\
&= (-\mu +\sigma^2)\,\D t - \sigma\,\D B\\
&= (-\mu+\sigma^2)\,\D t + \sigma (-\D B),
\end{align*}
The purpose of the last equality displayed here is to emphasize that we
should take the volatility of $K/F$ to be the positive number $\sigma$.
We can do this by using $-B$ as the Brownian motion instead of $B$.[^1]
Thus, we can apply Margrabe's formula to value calls and puts on
forwards (once we verify that $S_1$ and $S_2$ are indeed asset prices).

[^1]: This is really nothing more than the usual convention of defining
    the standard deviation of a random variable to be the positive
    square root of the variance.

To obtain Black's formula [\[black\]](#black){reference-type="eqref"
reference="black"} for a call on a forward from Margrabe's formula
[\[margrabeoption\]](#margrabeoption){reference-type="eqref"
reference="margrabeoption"}, we simply substitute $S_1(0)=P(0,T')F(0)$,
$S_2(0)=P(0,T')K$, $q_1=0$ and $q_2=0$ in Margrabe's formula. A put
option is the reverse exchange, so Margrabe's formula gives
\begin{equation}\label{margrabeput}
P(0,T')K\N(d^m_1) - P(0,T')F(0)\N(d^m_2)\;,
\end{equation}
where
\begin{align*}
d^m_1&= \frac{\log\left(\frac{P(0,T')K}{P(0,T')F(0)}\right)+\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\; ,\\
d^m_2 &=d^m_1-\sigma\sqrt{T}.
\end{align*}
We introduce the superscript $m$ here to distinguish these numbers in Margrabe's formula from the $d_1$ and $d_2$ defined in \eqref{black_d1} and \eqref{black_d2}.  Notice that
\begin{align*}
d^m_1& = -\frac{\log\left(\frac{F(0)}{K}\right)-\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}} = -d_2\\
d^m_2 &= -\frac{\log\left(\frac{F(0)}{K}\right)+\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}} =-d_1,
\end{align*}
so Margrabe's formula
[\[margrabeput\]](#margrabeput){reference-type="eqref"
reference="margrabeput"} is the same as Black's formula
[\[black_put\]](#black_put){reference-type="eqref"
reference="black_put"} for a put option on a forward.

We still need to explain why $S_1$ and $S_2$ defined in
[\[blackexchange\]](#blackexchange){reference-type="eqref"
reference="blackexchange"} are asset prices, in fact the prices of
non-dividend-paying assets since we have taken $q_1=q_2=0$ in applying
Margrabe's formula. The case of $S_2$ should be clear: it is the price
of $K$ units of the discount bond maturing at $T'$. The case of $S_1$ is
more subtle. It is the price of the following portfolio constructed at
date 0 and held until date $T$: go long one forward contract and buy
$F(0)$ units of the discount bond maturing at $T'$. The value at date
$t$ of the bonds in the portfolio is $F(0)P(t,T')$. The value at date
$t$ of the long forward contract can be seen by considering unwinding it
by selling a forward at date $t$ at the market price $F(t)$. This
cancels the delivery/receipt obligations on the underlying and results
in a net cash flow of $F(t)-F(0)$ to be received at date $T'$. The value
at date $t$ of this future cash flow is $P(t,T')[F(t)-F(0)]$ and when we
add this to the value of the bonds we obtain $P(t,T')F(t) = S_1(t)$.

Put-call parity \index{put-call parity} for options on forwards is
$$\text{Call Price}  + P(0,T')K = \text{Put Price}  + P(0,T')F(0)\; .$$
The left-hand side is the cost of the call and $K$ units of the discount bond, which have value $\max(F(T),K)P(T,T')$ at time $T$.  The right-hand side is the cost of the put option and $F(0)$ units of the discount bond, which, together with a long forward contract initiated at date 0, also have value $\max(F(T),K)P(T,T')$ at time $T$.
  
# Merton's Formula {#s_merton}
Now we reconsider the Black-Scholes model but without assuming there is
a constant risk-free rate. We assume instead that there is a discount
bond maturing at the same date as the option. Letting $T$ denote the
maturity date of the option and discount bond, we write the price of the
discount bond at dates $t \leq T$ as $P(t,T)$. We continue to assume
that the stock has a constant dividend yield $q$ but we make a different
assumption about volatility---instead of assuming that the volatility of
the stock is constant, we assume that the volatility of its forward
price is constant. We relax this to allow time-varying but non-random
volatility of the forward price in
Sect. [\[s_volatility\]](#s_volatility){reference-type="ref"
reference="s_volatility"}.

The forward contract we consider is a forward contract for the stock
maturing at the date $T$ that the option matures. Let $F(t)$ denote the
forward price for this contract at dates $0 \leq t\leq T$. Because the
forward price must equal the spot price at the maturity of a forward
contract, we have $F(T)=S(T)$. Consider a call option on the forward,
with the call maturing at $T$ also. In the notation of the previous
section, we have $T'=T$ and hence $P(T,T')=1$ (the discount bond is
worth \$1 at maturity). Therefore the value
[\[blackcallexchange1\]](#blackcallexchange1){reference-type="eqref"
reference="blackcallexchange1"} of the call on the forward at its
maturity $T$ is
$$\max(0,F(T)-K) = \max(0,S(T)-K)\; ,$$
which is the same as the value of the call on the stock. Therefore, the
value at date 0 of the call on the stock must equal the value at date 0
of the call on the forward, and we can use Black's formula
[\[black\]](#black){reference-type="eqref" reference="black"} for a call
option on a forward to price a call option on the stock, assuming the
forward price has a constant volatility.

Likewise, the value at the maturity date $T$ of a put option on the same
forward contract is, from
[\[blackputexchange\]](#blackputexchange){reference-type="eqref"
reference="blackputexchange"},
$$\max(0,K-F(T)) = \max(0,K-S(T))\; .$$
Hence, we can use Black's formula
[\[black_put\]](#black_put){reference-type="eqref"
reference="black_put"} to price a put option on the stock, assuming the
forward price has a constant volatility.

It is not necessary that the forward contract be traded, because we can create a synthetic forward using the stock.  To create a synthetic forward at date $t$ we buy $\E^{-q(T-t)}$ shares of the stock at cost $\E^{-q(T-t)}S(t)$.  With reinvestment of dividends, this will accumulate to one share at date $T$.  We finance the purchase of the stock by shorting $\E^{-q(T-t)}S(t)/P(t,T)$ units of the discount bond.  This results in a liability of $\E^{-q(T-t)}S(t)/P(t,T)$ dollars at date $T$, so the forward purchase is arranged by promising to pay $\E^{-q(T-t)}S(t)/P(t,T)$ dollars at the delivery date; i.e., the forward price is\footnote{If there is a constant risk-free rate $r$, then it must be that $P(t,T) = \E^{-r(T-t)}$, so  \eqref{forwardprice} becomes 
$$F(t) = \E^{(r-q)(T-t)}S(t)\; ,$$
which is the same as the covered interest parity condition \eqref{forwardexchangerate}---recall that we interpret the exchange rate as the price of an asset with dividend yield $q=r_f$.}
\begin{equation}\label{forwardprice}
F(t) = \frac{\E^{-q(T-t)}S(t)}{P(t,T)}\;.
\end{equation}
The assumption we need to apply Black's formulas is that
\begin{equation}\label{mertonforward}
\frac{\D F}{F} = \mu\,\D t+\sigma\,\D B\;,
\end{equation}
where $B$ is a Brownian motion, $\mu$ can be a quite general random
process, and $\sigma$ is a constant. At the end of this section, we will
discuss the meaning of this assumption in terms of the volatilities of
the stock and bond and their correlation.

Under this assumption, the following formulas originally due to Merton
[@Merton] follow immediately from Black's formulas
[\[blackcombined\]](#blackcombined){reference-type="eqref"
reference="blackcombined"} by substituting $F(0) = \E^{-qT}S(0)/P(0,T)$.
\mybox{Assuming the forward price has a constant volatility $\sigma$, the values at date 0 of European calls and puts maturing at date $T$ on a stock with a constant dividend yield $q$ are
\begin{subequations}\begin{align}
\text{Call Price} & = \E^{-q T}S(0)\N(d_1)-P(0,T)K\N(d_2)\;,\label{mertoncall}\\
\text{Put Price} &= P(0,T)K\N(-d_2) - \E^{-qT}S(0)\N(-d_1)\;,\label{mertonput}
\intertext{where}
d_1&= \frac{\log\left(\frac{S(0)}{KP(0,T)}\right)-qT+\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\;,\label{merton_d1}\\
d_2&=d_1-\sigma\sqrt{T}\;.\label{merton_d2}
\end{align}\end{subequations}
} \index{Merton's formula}



These formulas are clearly similar to the Black-Scholes formulas.  The similarities are made more apparent by writing the discount bond price in terms of its yield.  The yield $y$ of the discount bond is defined as \index{discount bond yield}
$$y = \frac{-\log P(0,T)}{T} \qquad\Longleftrightarrow \qquad P(0,T) = \E^{-yT}\; .$$
Substituting this into the expressions above, we have:
\mybox{Assuming the forward price has a constant volatility $\sigma$, the values at date 0 of European calls and puts maturing at date $T$ on a stock with a constant dividend yield $q$ are
\begin{subequations}\label{Mertoncombined}\begin{align}
\text{Call Price} &=\E^{-q T}S(0)\N(d_1)-\E^{-yT}K\N(d_2)\;,\label{merton}\\
\text{Put Price} &=\E^{-yT}K\N(-d_2)-\E^{-q T}S(0)\N(-d_1), \label{merton2}\\
d_1 &= \frac{\log\left(\frac{S(0)}{K}\right)+\left(y-q+\frac{1}{2}\sigma^2\right)T}{\sigma\sqrt{T}}\;,\label{merton_d1again}\\
d_2 &= d_1 - \sigma\sqrt{T}\;.\label{merton_d2again}
\end{align}\end{subequations}
}
This shows that the Merton call and put formulas can be calculated from
the Black-Scholes call and put functions given in
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"} by inputting the yield of the discount bond
as the risk-free rate and by inputting the volatility of the forward
price as $\sigma$.

This shows that the Merton call and put formulas can be calculated from
the Black-Scholes call and put functions given in
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"} by inputting the yield of the discount bond
as the risk-free rate and by inputting the volatility of the forward
price as $\sigma$. If one wants to assume that there is a constant
risk-free rate, then the discount bond price will have to be $\E^{-rT}$
and its yield will be the risk-free rate $r$. In this case, the forward
price is $\E^{(r-q)T}S(0)$ and it has the same volatility as $S$. Making
these substitutions, the Merton formulas
[\[Mertoncombined\]](#Mertoncombined){reference-type="eqref"
reference="Mertoncombined"} are the same as the Black-Scholes formulas.
However, the Merton formulas are an important generalization. It is
common practice to use the yield of the discount bond as the risk-free
rate that is input into the Black-Scholes formulas. The Merton formulas
justify this practice. It is less common to attempt to estimate the
volatility of the forward price and use this (as one should since the
risk-free rate really is not constant) as the volatility in the
Black-Scholes-Merton formulas. However, this does little damage for
pricing short-term options, because the volatility of the forward
price---see [\[mertonsigma\]](#mertonsigma){reference-type="eqref"
reference="mertonsigma"} below---will be approximately the same as the
volatility of the underlying for short-term options, due to the low
volatility of short-term bond prices. Moreover, when one computes an
implied volatility from the Black-Scholes formula (using the discount
bond yield as the risk-free rate), it should be regarded as the market's
view of the forward price volatility, and it is perfectly appropriate to
input it into the Black-Scholes-Merton formulas to price another option
(assuming of course that the forward price volatility can be regarded as
constant).

The volatility of the forward price can be computed in terms of the  volatilities and correlation of the stock and discount bond as follows.  Assume that \index{forward price volatility}
\begin{align*}
\frac{\D S}{S}& = \mu_s\,\D t + \sigma_s\,\D B_s\; ,\\
\frac{\D P}{P}& = \mu_p\,\D t + \sigma_p\,\D B_p,
\end{align*}
where $B_s$ and $B_p$ are Brownian motions with correlation $\rho$.  Then  \eqref{volatilityproduct} and \eqref{volatilityratio} show that the volatility of $F(t) = \E^{-q(T-t)}S(t)/P(t,T)$ is $\sigma$ defined as 
\begin{equation}\label{mertonsigma}
\sigma = \sqrt{\sigma_s^2+\sigma_p^2 - 2\rho\sigma_s\sigma_p}\;.
\end{equation}
As mentioned before, we will consider in
Sect. [\[s_volatility\]](#s_volatility){reference-type="ref"
reference="s_volatility"} that the the volatility
[\[mertonsigma\]](#mertonsigma){reference-type="eqref"
reference="mertonsigma"} may vary over time in a non-random way.

# Deferred Exchange Options

A call option on a forward can be viewed as an option to exchange $K$
dollars (or, equivalently, $K$ units of the discount bond maturing at
the maturity date of the forward) for the underlying asset, with the
exchange taking place at the maturity date of the forward. Therefore, it
is an exchange option in which the exchange takes place at a fixed date
after the option matures. We can easily extend Margrabe's formula to
value options to exchange other assets when the option maturity precedes
the date of the exchange.

As in Sect. [\[s_margrabe\]](#s_margrabe){reference-type="ref"
reference="s_margrabe"}, consider two assets with prices $S_i$ and
constant dividend yields $q_i$ and assume the prices satisfy
$$\frac{\D S_i}{S_i} = \mu_i\,\D t + \sigma_i\,\D B_i\; ,$$
where the drifts $\mu_i$, the volatilities $\sigma_i$ and the
correlation $\rho$ of the two Brownian motions can be general random
processes. However, also as in
Sect. [\[s_margrabe\]](#s_margrabe){reference-type="ref"
reference="s_margrabe"}, assume that the volatility
$$\sigma = \sqrt{\sigma_1^2 + \sigma_2^2 - 2\rho\sigma_1\sigma_2}$$
of the ratio of asset prices is constant.  

Consider an option maturing at date $T$ to exchange the second asset for
the first asset at date $T'\geq T$. To understand the value of the
option at date $T$, suppose it is exercised. To unwind the positions in
the two assets, one can sell a forward contract on the asset to be
received and buy a forward contract on the asset to be delivered, with
the forward contracts maturing at the date of the exchange. Then the
difference $F_1(T)-F_2(T)$ in the forward prices is a cash flow to be
received/paid at the exchange date $T'$ and its value at date $T$ is
$P(T,T')[F_1(T)-F_2(T)]$. Therefore, the value of the option at its
maturity $T$ is
$$\max(0,P(T,T')F_1(T) - P(T,T')F_2(T))\; .$$
As in Sect. [\[s_black\]](#s_black){reference-type="ref"
reference="s_black"}, this valuation does not require the existence of
traded forward contracts, because synthetic forwards can be created.
Also as in Sect. [\[s_black\]](#s_black){reference-type="ref"
reference="s_black"} we know that
$$S^*_1(t) = P(t,T')F_1(t) \quad \text{and} \quad S^*_2(t) = P(t,T')F_2(t)$$
are the prices of non-dividend-paying assets. Therefore, the option to
exchange the assets at date $T'$ must have the same value as an option
to exchange at date $T$ the assets with prices $S^*_i$.

We recall here the arbitrage formula
[\[forwardprice\]](#forwardprice){reference-type="eqref"
reference="forwardprice"} for the forward prices (making the change that
here the forwards mature at $T'$):
$$F_i(t) =  \frac{\E^{-q_i(T'-t)}S_i(t)}{P(t,T')}\; .$$
Thus,
$$S^*_i(t) = \E^{-q_i(T'-t)}S_i(t)\; .$$
This implies that the volatility of the ratio $S_1^*/S_2^*$ is the same
as the volatility of the ratio $S_1/S_2$. Therefore, we can price a
deferred exchange option from Margrabe's formula, inputting the prices
$S^*_i(0) = \E^{-q_iT'}S_i(0)$ as the initial asset prices and zero as
their dividend yields. This formula is:
\mybox{The value of a European option maturing at date $T$ to exchange two assets at date $T'$ is
\begin{subequations}\begin{equation}\label{margrabedeferredoption}
\E^{-q_1 T'}S_1(0)\N(d_1)-\E^{-q_2 T'}S_2(0)\N(d_2)\;,
\end{equation}
where 
\begin{align}
d_1&= \frac{\log\left(\frac{S_1(0)}{S_2(0)}\right)+(q_2-q_1)T'+
\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\;,\label{margrabedeferred_d1}\\
d_2&=d_1-\sigma\sqrt{T}\;,\label{margrabedeferred_d2}
\end{align}\end{subequations}
}


# Calculations in VBA {#s_matlabimplementations}

We could of course write entirely separate programs for the options
discussed so far in this chapter but it seems useful to emphasize their
common structure. As discussed in the introduction to this chapter, each
is the present value of what is received upon exercise multiplied by
$\N(x)$ minus the present value of what is delivered upon exercise
multiplied by $\N(y)$ and $x$ in each case is the logarithm of the ratio
of present values plus one-half $\sigma^2T$, all divided by
$\sigma\sqrt{T}$. In the case of options on forwards, the present values
are the present values of what is received or delivered at the maturity
of the forward contract. We can do this calculation in the following
program.
\addcontentsline{lof}{figure}{Generic Option}
\small\begin{verbatim}
Function Generic_Option(P1, P2, sigma, T)
'
' Inputs are P1 = present value of asset to be received
'            P2 = present value of asset to be delivered
'            sigma = volatility
'            T = time to maturity
'
Dim x, y, N1, N2
x = (Log(P1 / P2) + 0.5 * sigma * sigma * T) / (sigma * Sqr(T))
y = x - sigma * Sqr(T)
N1 = Application.NormSDist(x)
N2 = Application.NormSDist(y)
Generic_Option = P1 * N1 - P2 * N2
End Function
\end{verbatim}\normalsize
Now we can use the following one-line programs to value exchange and
forward options. We will explain in
Sect. [\[s_futuresoptions\]](#s_futuresoptions){reference-type="ref"
reference="s_futuresoptions"} why (and in what circumstance) the Black
call and put functions are appropriate for options on futures.

\addcontentsline{lof}{figure}{Margrabe}
\small\begin{verbatim}
Function Margrabe(S1, S2, sigma, q1, q2, T)
'
' Inputs are S1 = price of asset to be received
'            S2 = price of asset to be delivered
'            sigma = volatility of ratio of prices
'            q1 = dividend yield of asset to be received
'            q2 = dividend yield of asset to be delivered
'            T = time to maturity
'
Margrabe = Generic_Option(Exp(-q1*T)*S1,Exp(-q2*T)*S2,sigma,T)
End Function
\end{verbatim}\normalsize

\addcontentsline{lof}{figure}{Black Call}
\small\begin{verbatim}
Function Black_Call(F, K, P, sigma, T)
'
' Inputs are F = forward price
'            K = strike price
'            P = price of bond maturing when forward matures
'            sigma = volatility of forward price
'            T = time to maturity
'
' To value a futures option, input F = futures price and 
' P = price of bond maturing when option matures.
'
Black_Call = Generic_Option(P * F, P * K, sigma, T)
End Function
\end{verbatim}\normalsize

\addcontentsline{lof}{figure}{Black Put}
\small\begin{verbatim}
Function Black_Put(F, K, P, sigma, T)
'
' Inputs are F = forward price
'            K = strike price
'            P = price of bond maturing when forward matures
'            sigma = volatility of forward price
'            T = time to maturity
'
' To value a futures option, input F = futures price and 
' P = price of bond maturing when option matures.
'
Black_Put = Generic_Option(P * K, P * F, sigma, T)
End Function
\end{verbatim}\normalsize

\addcontentsline{lof}{figure}{Margrabe Deferred}
\small\begin{verbatim}
Function Margrabe_Deferred(S1, S2, sigma, q1, q2, Tm, Te)
'
' Inputs are S1 = price of asset to be received
'            S2 = price of asset to be delivered
'            sigma = volatility of ratio of prices
'            q1 = dividend yield of asset to be received
'            q2 = dividend yield of asset to be delivered
'            Tm = time to maturity of option
'            Te = time until exchange >= Tm
'
Margrabe_Deferred = _
        Generic_Option(Exp(-q1*Te)*S1,Exp(-q2*Te)*S2,sigma,Tm)
End Function
\end{verbatim}\normalsize


\noindent
We could also have calculated the Black-Scholes call formula as
\small
\begin{center}
\verb!Generic_Option(Exp(-q*T)*S, Exp(-r*T)*K, sigma, T)!
\end{center}
\normalsize
and the Black-Scholes put formula as
\small
\begin{center}
\verb!Generic_Option(Exp(-r*T)*K, Exp(-q*T)*S, sigma, T)!.
\end{center}
\normalsize


# Greeks and Hedging {#s_forwardhedging}

The Greeks for the Margrabe and Black formulas can be calculated in the
same way that we calculated them in
Chap. [\[c_blackscholes\]](#c_blackscholes){reference-type="ref"
reference="c_blackscholes"} for the Black-Scholes formula. In analogy
with [\[greeksimplify\]](#greeksimplify){reference-type="eqref"
reference="greeksimplify"}, it can be shown for the Margrabe formula
that
$$\E^{-q_1T}S_1(0)\nd(d_1) = \E^{-q_2T}S_2(0)\nd(d_2)\; ,$$
and again this simplifies the calculations.  This equation applies to the Black call formula by taking $q_1=q_2=0$, $S_1(0)=P(0,T')F(0)$, and $S_2(0)=P(0,T')K$, leading to
$$F(0)\nd(d_1) = K\nd(d_2)\; .$$
The Greeks for the Black call formula and the Margrabe formula are: \index{Greeks}
\small
\mybox{
\begin{align*}
&\textbf{Black Call} && \textbf{Margrabe}\\
& & & \\
\frac{\partial}{\partial F} &= P(0,T')\N(d_1)  % Black delta1
&\frac{\partial}{\partial S_1}&= \E^{-q_1T}\N(d_1)\\ % Margrabe delta1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frac{\partial}{\partial P} &= F(0)\N(d_1)-K\N(d_2)% Black delta2
&\frac{\partial}{\partial S_2}&=-\E^{-q_2T}\N(d_2)\\ % Margrabe delta2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frac{\partial^2}{\partial F^2} &= \frac{P(0,T')\nd(d_1)}{\sigma\sqrt{T}F(0)}  % Black gamma1
&\frac{\partial^2}{\partial S_1^2}&= \frac{\E^{-q_1T}\nd(d_1)}{\sigma\sqrt{T}S_1(0)}\\ % Margrabe gamma1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frac{\partial^2}{\partial P^2} &= 0 % Black gamma2
&\frac{\partial^2}{\partial S_2^2}&=\frac{\E^{-q_2T}\nd(d_2)}{\sigma\sqrt{T}S_2(0)}\\ %Margrabe gamma2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frac{\partial^2}{\partial F \partial P} &= \N(d_1)&\frac{\partial^2}{\partial S_1 \partial S_2}% Black crossgamma
&= -\frac{\E^{-q_1T}\nd(d_1)}{\sigma\sqrt{T}S_2(0)}\\ % Margrabe crossgamma
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-\frac{\partial}{\partial T} &= -\frac{\sigma P(0,T')F(0)\nd(d_1)}{2\sqrt{T}}%Black theta part1
& -\frac{\partial}{\partial T}&=q_1\E^{-q_1T}S_1(0)\N(d_1)\\ %Margrabe theta part1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
& &&-q_2\E^{-q_2T}S_2(0)\N(d_2)\\ % Margrabe theta part2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
&&&-\frac{\sigma \E^{-q_1T}S_1(0)\nd(d_1)}{2\sqrt{T}}\\ % Margrabe theta part3
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frac{\partial}{\partial \sigma} &= \sqrt{T}P(0,T')F(0)\nd(d_1) % Black vega
&\frac{\partial}{\partial \sigma}&=\sqrt{T}\E^{-q_1T}S_1(0)\nd(d_1) % Margrabe vega
\end{align*}
}
\normalsize

Hedging for the Margrabe formula is much the same as for the
Black-Scholes formula. We would delta-hedge a written exchange option by
holding $\delta_1=\E^{-q_1T}\N(d_1)$ shares of the first asset and
$\delta_2 =- \E^{-q_2T}\N(d_2)$ shares of the second asset (which means
shorting the second asset). This position would be financed by borrowing
at the risk-free rate (or shorting the discount bond). The same argument
that we used in
Sect. [\[s_deltahedging\]](#s_deltahedging){reference-type="ref"
reference="s_deltahedging"} shows that this zero-cost portfolio will
have a zero return if continuously rebalanced.

Because the Black formulas are a special case of the Margrabe formula,
we can delta-hedge options on forwards in the same way. Putting
$q_1=q_2=0$, $S_1(0)=P(0,T')F(0)$ and $S_2(0)=P(0,T')K$, we would
delta-hedge a written call option by buying $\N(d_1)$ shares of the
first asset and shorting $\N(d_2)$ shares of the second, where $d_1$ and
$d_2$ are defined in the Margrabe formulas
[\[margrabe_d1\]](#margrabe_d1){reference-type="eqref"
reference="margrabe_d1"} and
[\[margrabe_d2\]](#margrabe_d2){reference-type="eqref"
reference="margrabe_d2"} and equivalently in the Black formulas
[\[black_d1\]](#black_d1){reference-type="eqref" reference="black_d1"}
and [\[black_d2\]](#black_d2){reference-type="eqref"
reference="black_d2"}. This position would be financed by shorting the
discount bond to raise the difference between the cost of the portfolio
and the option value so that the cost of the total portfolio (including
the short discount bond) equals the option value. However, the first
asset here consists of a long forward contract plus $F(0)$ units of the
discount bond, and the second asset is $K$ units of the discount bond.
Furthermore, we are using the discount bond to finance the position
(including the buying and shorting of the discount bond!). We can
conclude that buying $\N(d_1)$ units of the first asset means that we
should buy $\N(d_1)$ forward contracts. This has zero cost. Therefore,
the portfolio value will equal the value of the discount bonds, and this
must equal the option value. So, we actually invest the option value
$$P(0,T')F(0)\N(d_1) - P(0,T')K\N(d_2)\; ,$$
in the discount bond, which means buying $F(0)\N(d_1)-K\N(d_2)$ units of the bond.

A more direct analysis of hedging options on forwards is possible and
instructive. We will consider that topic further in
Sect. [\[s_hedgingforwards\]](#s_hedgingforwards){reference-type="ref"
reference="s_hedgingforwards"}.

# The Relation of Futures Prices to Forward Prices {#s_futuresforwards}

The difference between futures and forward contracts is that futures are
marked to market, which means that daily gains and losses are posted to
the investor's margin account. Thus, there are interim cash flows on a
futures contract, whereas the only cash flows on a forward contract are
at the maturity of the forward. We will establish three useful facts in
this section, the last of which follows from the first two:

\begin{enumerate}
\renewcommand{\labelenumi}{(\arabic{enumi})}
\item Futures prices are martingales under the risk-neutral measure. 
\item Forward prices are martingales when we use the discount bond with the same maturity as the forward as the numeraire.
\item When interest rates are non-random, futures prices equal forward prices.
\end{enumerate}


We consider the idealized case in which the futures contract is
continuously marked to market. Assume there is an instantaneously
risk-free asset with rate of return $r$, which could vary randomly over
time, and define, as in
Sect. [\[s_continuouscompounding\]](#s_continuouscompounding){reference-type="ref"
reference="s_continuouscompounding"},
$$R(t) = \exp\left(\int_0^t r(s)\,ds\right)\; ,$$
which is the value at date $t$ of a \$1 investment in the asset at date 0, with interest continuously reinvested.
Let $T'$ denote the maturity of the futures contract, and let $F^*(t)$
denote the futures price at dates $t \leq T'$ (the $^*$ notation is to
distinguish the futures price from the forward price $F$). Consider the portfolio strategy that starts with zero dollars and one long futures contract at price $F^*(0)$ and which continuously invests
and withdraws from the risk-free asset the gains and losses on the
futures contract. Let $V(t)$ denote the value of this portfolio at
date $t$. The change in the value of the portfolio at any instant is the
interest earned (or paid, if $V<0$) on the risk-free asset plus the
gain/loss on the futures. This means that
$$\D V = rV\,\D t + \D F^*\; .$$
Because all gains and losses on this portfolio are reinvested, $V$ is
the price of a non-dividend-paying asset. Therefore, under the
risk-neutral measure (i.e., using $R$ as the numeraire), the ratio $V/R$
must be a martingale and hence have zero drift. From Itô's formula,
\begin{align*}
\frac{\D (V/R)}{V/R} &= \frac{\D V}{V} - \frac{\D R}{R}\\
&=\frac{rV\,\D t + \D F^*}{V} - r\,\D t\\
&= \frac{\D F^*}{V}\;.
\end{align*}
Thus, the drift of $V/R$ being zero implies the drift of $F^*$ is zero.
We need to assume (and can assume) that $F^*$ is an Itô process with
finite expected quadratic variation---cf. condition
[\[regularity1\]](#regularity1){reference-type="eqref"
reference="regularity1"}---in which case the absence of a drift implies that it is a martingale.  

Now we turn to fact (2). Consider a forward contract with maturity $T'$
and a discount bond also maturing at $T'$. Let $F(t)$ denote the forward
price and let $P(t,T')$ denote the price of the discount bond at dates
$t \leq T'$. We observed in Sect. [\[s_black\]](#s_black){reference-type="ref" reference="s_black"}
that there is a non-dividend paying asset with price $P(t,T')F(t)$. When
we use the discount bond as the numeraire, the ratio
$P(t,T')F(t)/P(t,T') = F(t)$ must be a martingale, which is fact (2).
Because of this fact, a probability measure corresponding to a discount
bond being the numeraire is called a "forward measure." \index{forward measure}

Suppose now that interest rates are deterministic, that is, even if $r$
varies over time, it does so in a non-random way. Then the discount bond
price at date 0 must be the discount factor
$$P(0,T') = \exp\left(-\int_0^{T'} r(t)\,\D t\right)\; .$$
Equation \eqref{probSnumeraire} gives the probability of any event $A$ when the discount bond is used as the numeraire as
$$\text{prob}^P[A] = E\left[1_A\phi(T')\frac{P(T',T')}{P(0,T')}\right] = \exp\left(-\int_0^{T'} r(t)\,\D t\right)E[1_A\phi(T')]\; ,$$
where $\phi$ denotes the state prices.
On the other hand, the same equation gives the probability of $A$ when $R$ is used as the numeraire as
$$\text{prob}^R[A] = E\left[1_A\phi(T')\frac{R(T')}{R(0)}\right] = \exp\left(-\int_0^{T'} r(t)\,\D t\right)E[1_A\phi(T')]\; .$$
Therefore, the two probability measures are the same, and consequently the expectations $E^P$ and $E^R$ are the same.  Now using the fact that both the futures price and the forward price must equal the spot price at maturity, we have $F^*(T') = F(T')$, and, from the martingale properties,
$$F^*(t) = E_t^P[F^*(T')] = E_t^P[F(T')] = E_t^R[F(T')] = F(t)\; ,$$
which is fact (3).



# Futures Options {#s_futuresoptions}

Now we consider options on futures contracts, \index{futures option} assuming that interest rates are deterministic.  We just showed that in this circumstance the futures price will equal the forward price for a contract of the same maturity.  However, the values of options on a futures contract do not equal the values of options on the corresponding forward contract.  

The difference is due to marking to market. Consider futures and forward
contracts with maturity $T'$ and options maturing at $T \leq T'$.
Exercise of a call option on a futures contract will roll the investor
into a long futures contract with futures price equal to the market
futures price at that date. The difference $F^*(T)-K$ between the market
futures price and the strike price of the option is immediately credited
to the investor's margin account. On the other hand, exercise of an
option on a forward and sale of the forward results in a cash flow of
$F(T) - K$ that is received at the maturity date $T'$ of the forward.
Therefore, the value at maturity of a call option on a futures contract
is
$\max(0,F^*(T)-K)$, whereas, as noted before, the value of a call option on a forward at the maturity of the option is $P(T,T')\max(0,F(T)-K)$

As in the analysis of options on forwards, an options on a futures contract can be viewed as an exchange option, where one exchanges the asset with price
$S_2(t) = P(t,T)K$ at date $t\leq T$ for the asset with price
$S_1(t) = P(t,T)F^*(t)$. The asset with price $S_2$ is of course $K$
units of the discount bond maturing at $T$. Assuming interest rates are
deterministic, we have $F^*(t) = F(t)$, and we noted in
Sect. [\[s_black\]](#s_black){reference-type="ref" reference="s_black"}
that $P(t,T)F(t)$ is the price of a non-dividend-paying asset. Thus, we
can apply Margrabe's formula to price call (and put) options on futures
when interest rates are deterministic. Compared to options on forwards,
the difference is that the discount bonds defining the prices $S_1$
and $S_2$ mature at the maturity date of the option rather than at the
maturity date of the futures or forward contract. The result is:
\mybox{When interest rates are deterministic and the futures price $F^*$ has a constant volatility $\sigma$, the values of  European calls and puts on a futures contract are
\begin{subequations}\label{blackcombinedfutures}\begin{align}
\text{Call Price} &=P(0,T)F^*(0)\N(d_1)-P(0,T)K\N(d_2)\label{black2}\; ,\\
\text{Put Price} &=P(0,T)K\N(-d_2)-P(0,T)F^*(0)\N(-d_1)\label{black_put2}\; ,\\
\intertext{where}
d_1&= \frac{\log\left(\frac{F^*(0)}{K}\right)+\frac{1}{2}\sigma^2T}{\sigma\sqrt{T}}\;,\label{black_d12}\\
d_2&=d_1-\sigma\sqrt{T}\;.\label{black_d22}
\end{align}\end{subequations}
}
We can calculate these values from the `Black_Call` and `Black_Put`
functions by inputting the price of the discount bond maturing when the
option matures rather than the price of the discount bond maturing when
the forward/futures matures.
We will derive delta hedges for futures options in
Sect. [\[s_hedgingforwards\]](#s_hedgingforwards){reference-type="ref"
reference="s_hedgingforwards"}.

# Time-Varying Volatility {#s_volatility}

All of the option pricing formulas in this chapter were derived from
Margrabe's formula, the main assumption of which is that the logarithm
of the ratio of asset prices at date $T$ is normally distributed with
variance equal to $\sigma^2T$. As in
Sect. [\[s_timevaryingvolatility\]](#s_timevaryingvolatility){reference-type="ref"
reference="s_timevaryingvolatility"} regarding the Black-Scholes
formulas, the formulas in this chapter can easily be adapted to allow a
time-varying but non-random volatility. If the volatility is a
non-random function $\sigma(t)$ of time, then we define
$\sigma_{\text{avg}}$ to be the number such that
\begin{equation}\label{averagesigma}
\sigma_{\text{avg}}^2 = \frac{1}{T}\int_0^T \sigma^2(t)\,\D t\;.
\end{equation} 
We should input $\sigma_{\text{avg}}$ as (i) the volatility of the ratio
of asset prices in Margrabe's formula and the deferred exchange option
formula if $\sigma(t)$ is the volatility of the ratio at date $t$ or as
(ii) the volatility of the forward price in Black's and Merton's
formulas if $\sigma(t)$ is the volatility of the forward price at date
$t$.
As in
Sect. [\[s_timevaryingvolatility\]](#s_timevaryingvolatility){reference-type="ref"
reference="s_timevaryingvolatility"},
equation [\[averagesigma\]](#averagesigma){reference-type="eqref"
reference="averagesigma"} enables one to interpret and apply different
implied volatilities computed at different maturities. Another
circumstance in which it can be useful is in conjunction with bond price
models such as the Vasicek and extended Vasicek models described in
Chap. [\[c_vasicek\]](#c_vasicek){reference-type="ref"
reference="c_vasicek"} that imply a time-varying non-random volatility
for discount bond prices.[^1] If we assume a constant volatility for the
price of the underlying and a constant correlation between the
underlying and the discount bond, then we will have a time-varying
non-random forward price volatility via
[\[mertonsigma\]](#mertonsigma){reference-type="eqref"
reference="mertonsigma"}, and we should input the "average volatility"
$\sigma_{\text{avg}}$ defined in
[\[averagesigma\]](#averagesigma){reference-type="eqref"
reference="averagesigma"} for the forward price volatility in Black's
and Merton's formulas. As mentioned in
Sect. [\[s_merton\]](#s_merton){reference-type="ref"
reference="s_merton"}, this will be more important for long-term options
than for short-term options.

[^1]: The volatility of a discount bond price cannot be constant because
    it must go to zero as the bond approaches maturity.

# Hedging with Forwards and Futures {#s_hedgingforwards}

In Chap. [\[c_foreignexchange\]](#c_foreignexchange){reference-type="ref"
reference="c_foreignexchange"}, we considered hedging quanto contracts
with currency forwards. In
Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"}, we considered hedging options on forwards
with forwards. To present a more complete analysis of these topics, we
need to discuss the gains and losses that accrue from trading forwards.

Consider dates $t<u$ and a forward contract with maturity $T$. Suppose
we purchase $x(t)$ forwards at date $t$ and then change our position in
forwards to $x(u)$ at time $u$. The purchase/sale of $x(u)-x(t)$ new
contracts does not affect the portfolio value, so the change in the
value of the portfolio is the change in the value of the $x(t)$
contracts purchased at date $t$. These contracts were worth zero at date
$t$, because forward contracts have zero value at initiation. Selling
them at date $u$ cancels the obligation to deliver/receive the
underlying, leaving one with a cash flow of $x(t)[F(u)-F(t)]$ dollars to
be received at date $T$. The value of this cash flow at date $u$ is
$x(t)P(u,T)[F(u)-F(t)]$. We can write this as
\begin{align*}
x(t)P(u,T)&[F(u)-F(t)]  \\\begin{split}&= x(t)\big[P(t,T)[F(u)-F(t)] + [P(u,T)-P(t,T)][F(u)-F(t)]\big]\\
&= x(t)\big[P(t,T)\,\varDelta F + (\varDelta P)(\varDelta F)\big]\;.
\end{split}
\end{align*}
This motivates the following definition:
\mybox{
The change in the value of a portfolio of forward contracts at date $t$ is
\begin{equation}\label{changeforwardvalue}
x(t)\big[P(t,T)\,\D F(t) + \D P(t,T)\times \D F(t)]\;,
\end{equation}
where $x(t)$ denotes the number of forward contracts held, $F(t)$ denotes the forward price, $P(t,T)$ denotes the price of a discount bond maturing at $T$, and $T$ is the maturity of the forward contract.}


Hedging with futures is a bit simpler, because the gains and losses are
received instantaneously (daily, at least) rather than being deferred to
the contract maturity. Letting $x(t)$ denote the number of futures
contracts held at date $t$ and $F^*(t)$ the futures price, the cash flow
from the contracts is $x(t)\,\D F^*(t)$. This is also the change in the
value of the portfolio, because marking to market means that the
contracts always have zero value.

To compare hedging with futures and forwards, assume  there is a constant risk-free rate~$r$.  Let $T$ denote the maturity of the futures and forward contracts.  Because there is a constant risk-free rate, we have $P(t,T) = \E^{-r(T-t)}$, which implies $(\D P)(\D F) =0$.  Moreover, futures prices equal forward prices.  Thus,
\mybox{If there is a constant risk-free rate $r$, the change in the value of a portfolio of forward contracts at date $t$ is
\begin{equation}\label{forwardchange100}
x(t)\E^{-r(T-t)}\,\D F(t)
\end{equation}
and the change in the value of a portfolio of futures contracts is
\begin{equation}\label{futureschange100}
x(t)\,\D F(t)\;,
\end{equation}
where $x(t)$ denotes the number of futures/forward contracts held at date~$t$, $T$ is the maturity of the futures and forward contracts and $F(t)$ is the futures (= forward) price at date $t$.}
Comparing \eqref{forwardchange100} and \eqref{futureschange100}, we see that if $x(t)$ is the number of forward contracts that should be held in a hedge, then 
\begin{equation}\label{futuresxy}
y(t) = \E^{-r(T-t)}x(t)
\end{equation}
is the number of futures contracts that should be held, because with this number of contracts we have
\begin{align*}
\text{Change in Forward Portfolio} & = x(t)\E^{-r(T-t)}\,\D F(t)\\
& = y(t)\,\D F(t)\\
& = \text{Change in Futures Portfolio}\;.
\end{align*}
In short, we don't require as many futures contracts as forward contracts, and the scaling factor to convert from forwards to futures is just the present value factor $\E^{-r(T-t)}$.

For example, the result of
Sect. [\[s_replicatingquantos\]](#s_replicatingquantos){reference-type="ref"
reference="s_replicatingquantos"} on replicating the payoff
$\bar{X}S(T)$ with forward contracts leads to the following:

\mybox{To replicate the payoff $\bar{X}S(T)$ at date $T$, where $\bar{X}$ is a fixed exchange rate and $S$ is the foreign currency price of an asset, one should invest $V(t)$ units of domestic currency in the foreign asset and be short $\E^{(r_f-r)(T-t)}V(t)/X(t)$ currency futures at date $t$, where $V(t)$ is defined in \eqref{quanto2} and $X(t)$ is the spot exchange rate.}

We can use [\[futuresxy\]](#futuresxy){reference-type="eqref"
reference="futuresxy"} to determine how to delta hedge futures options.
As explained in
Sect. [\[s_futuresoptions\]](#s_futuresoptions){reference-type="ref"
reference="s_futuresoptions"}, assuming non-random interest rates,
futures options are more valuable than options on forwards because
futures are marked to market upon exercise of an option. Specifically,
Black's formulas
[\[blackcombined\]](#blackcombined){reference-type="eqref"
reference="blackcombined"} for options on forwards and
[\[blackcombinedfutures\]](#blackcombinedfutures){reference-type="eqref"
reference="blackcombinedfutures"} for options on futures show that the
values are the same except for the maturity of the discount bond
appearing in the equations. With a constant risk-free rate $r$, options
maturing at $T$ and futures/forwards maturing at $T'$, the relation is

$$\text{Value of Futures Option} = \E^{r(T'-T)} \times \text{Value of Forward Option}\; .$$
Because the scaling factor $\E^{r(T'-T)}$ does not change as time passes, this implies that as time passes we have
\begin{multline}\label{futures1001}
\text{Change in Futures Option Value } \\= \E^{r(T'-T)} \times \text{Change in Forward Option Value}\;.
\end{multline}
We can combine [\[futuresxy\]](#futuresxy){reference-type="eqref"
reference="futuresxy"} and
[\[futures1001\]](#futures1001){reference-type="eqref"
reference="futures1001"} to convert from a hedge of a forward option
using forward contracts, which we discussed in
Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"}, to a hedge of a futures option using
futures contracts. For example, we concluded in
Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"} that we should be long $\N(d_1)$ forwards
to hedge a short call option on a forward contract. Consequently,
[\[futuresxy\]](#futuresxy){reference-type="eqref"
reference="futuresxy"} shows that we can hedge a short call option on a
forward by being long $\E^{-r(T'-t)}\N(d_1)$ futures, and then we see
from [\[futures1001\]](#futures1001){reference-type="eqref"
reference="futures1001"} that the hedge for a short call on a futures is
being long
$$\E^{r(T'-T)}\E^{-r(T'-t)}\N(d_1) = \E^{-r(T-t)}\N(d_1)$$ 
futures contracts.

In Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"}, we derived the hedges for forward options
by considering them as exchange options. We can use the definition
[\[changeforwardvalue\]](#changeforwardvalue){reference-type="eqref"
reference="changeforwardvalue"} to confirm that our calculations were
correct. Consider hedging a short call maturing at $T$ on a forward
contract maturing at $T'$. We can assume interest rates vary randomly
and use discount bonds in the hedge. We stated in
Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"} that we should hold
$F(0)\N(d_1)-K\N(d_2)$
units of the discount bond maturing at~$T'$  and we should go long 
$\N(d_1)$ forwards to hedge the short call. 
This is a zero-cost portfolio when we include the proceeds from selling
the call. Using
[\[changeforwardvalue\]](#changeforwardvalue){reference-type="eqref"
reference="changeforwardvalue"}, we see that the change in the value of
the portfolio will be
\begin{equation}\label{forwardhedging1}
-\D C + [F(0)\N(d_1)-K\N(d_2)]\D P + \N(d_1)[P(0,T')\,\D F + (\D P)(\D F)]\;.
\end{equation}
The value of the call at date $t$ will be a function of $t$,  $P(t,T')$ and $F(t)$, which we write as $C(t,P,F)$.  From It\^o's formula,
\begin{align*}
\D C &= \frac{\partial C}{\partial t}\,\D t + \frac{\partial C}{\partial P}\,\D P + \frac{\partial C}{\partial F}\,\D F \\  &\qquad + \frac{1}{2}\frac{\partial^2 C}{\partial P^2}\, (\D P)^2   + \frac{1}{2}\frac{\partial^2 C}{\partial F^2}\, (\D F)^2 + \frac{\partial^2 C}{\partial F \partial P} (\D P)(\D F)\;.\\
&=\Theta\,\D t + \delta_P\,\D P + \delta_F\,\D F  + \frac{1}{2}\Gamma_{PP} (\D P)^2 + \frac{1}{2}\Gamma_{FF} (\D F)^2  + \Gamma_{FP}\,(\D P)(\D F)\;,
\end{align*}
where the $\delta$'s and $\Gamma$'s denote the first and second partial
derivatives indicated by the subscripts. Inserting this formula into
[\[forwardhedging1\]](#forwardhedging1){reference-type="eqref"
reference="forwardhedging1"} and making use of the formulas in the table
in Sect. [\[s_forwardhedging\]](#s_forwardhedging){reference-type="ref"
reference="s_forwardhedging"}, we see that the $\D P$ terms cancel
because $\delta_P = F(0)\N(d_1)-K\N(d_2)$. Furthermore, the $\D F$ terms
cancel because $\delta_F = \N(d_1)P(0,T')$. Thus, there is no exposure
in the portfolio to the two risky asset prices $P$ and $F$. Furthermore,
$\Gamma_{PP} = 0$ and the $(\D P)(\D F)$ terms cancel because
$\Gamma_{FP} = \N(d_1)$. These substitutions simplify the change
[\[forwardhedging1\]](#forwardhedging1){reference-type="eqref"
reference="forwardhedging1"} in the value of the portfolio to
$$-\Theta\,\D t - \frac{1}{2}\Gamma_{FF} (\D F)^2  = \frac{\sigma P(0,T')F(0)\nd(d_1)}{2\sqrt{T}}\,\D t  -  \frac{P(0,T')\nd(d_1)}{2\sigma\sqrt{T}F(0)}\,(\D F)^2\; ,$$
which we can see to be zero because $(\D F)^2 = \sigma^2F^2\,\D t$.
Thus, the hedge is perfect when continuously rebalanced.

# Market Completeness {#s_margrabecomplete}

A formal definition of market completeness \index{complete market} must specify which
state-contingent claims (random variables depending on the history of
prices) can be replicated by trading the marketed assets---for example,
one might want all of the claims with finite means to be replicable, or
only all of the claims with finite variances, etc. A formal analysis of
market completeness is not presented in this book, except for the
binomial and trinomial models in
Chap. [\[c_basics\]](#c_basics){reference-type="ref"
reference="c_basics"}. However, we have stated that stochastic
volatility models are incomplete. This follows intuitively from the fact
that a portfolio containing only one risky asset (the underlying) cannot
be perfectly correlated with the two Brownian motions that determine the
value of a derivative asset (the Brownian motions driving the price of
the underlying and its volatility). In general, a market must include an
instantaneously risk-free asset and as many risky assets as there are
Brownian motions in order to be complete.  

The exchange-option model of Margrabe---with two risky assets, two Brownian motions, and no risk-free asset---is obviously incomplete.  \index{incomplete market} For
example, it is impossible to have exactly \$100 at date $T$. With no
risk-free asset, there is simply no way to store money. This may seem
far-fetched, but we might be interested in payoffs in "real" (i.e.,
inflation-adjusted) dollars, in which case the absence of a risk-free
asset may be a normal situation. In any case, we have not assumed a
risk-free asset exists, but we have priced options without appealing to
"equilibrium" arguments. This deserves some clarification.

As mentioned above, a formal definition of market completeness must
specify which contingent claims are to be replicable. The Margrabe model
is complete for a certain set of contingent claims. Contingent claims of
the form $S_2(T)X(T)$ where $X(T)$ is a random variable depending on the
relative prices $S_1(t)/S_2(t)$ for $0 \leq t\leq T$ can be replicated.
Likewise, contingent claims of the form $S_1(T)X(T)$ can be replicated.
The payoffs of exchange options are of this form, so they can be priced
by arbitrage, even though there are other contingent claims (for
example, receiving exactly \$100 at date $T$) that cannot be replicated
and hence cannot be priced by arbitrage. Likewise, the Black and Merton
models in which there is a zero-coupon bond but no instantaneously
risk-free asset are examples of incomplete markets that are still
sufficiently complete to price options by arbitrage (the options can be
replicated). The proof that the Margrabe model is complete in the sense
stated here follows from the change of numeraire argument used to derive
Margrabe's formula from the Black-Scholes formula (recall that the
second asset is risk-free when we use it as the numeraire, so there is a
risk-free asset under the new numeraire) and a proof that the
Black-Scholes model is complete (which we have omitted, except to show
that European options can be replicated).

\begin{petit}
We will conclude with a proof of the Margrabe formula that does not
depend on the Black-Scholes formula. Let $x$ denote the random variable
taking the value 1 when $S_1(T)>S_2(T)$ and which is 0 otherwise. Then
the value of the exchange option at maturity is $xS_1(T)-xS_2(T)$. Let
$V_i$ denote the value of the portfolio beginning with $\E^{-q_iT}$
units of asset $i$ at date 0 and reinvesting dividends, to accumulate to
one share at date $T$. Then $V_i(T)=S_i(T)$ and from the fundamental
pricing formula [\[formula\]](#formula){reference-type="eqref"
reference="formula"} the value at date 0 of receiving $xS_i(T)$ at
date $T$ is
\begin{align*}
V_i(0)E^{V_i}\left[x\frac{S_i(T)}{V_i(T)}\right] &= \E^{-q_iT}S_i(0)E^{V_i}[x] \\
&= \E^{-q_iT}S_i(0)\times\text{prob}^{V_i}\big(V_1(T)>V_2(T)\big)\; .
\end{align*}
We can write the value of receiving $xS_1(T)$ as
$$\E^{-q_1T}S_1(0)\times\text{prob}^{V_1}\left(\frac{V_2(T)}{V_1(T)} < 1\right)$$
and the value of receiving $xS_2(T)$ as
$$\E^{-q_2T}S_2(0)\times\text{prob}^{V_2}\left(\frac{V_1(T)}{V_2(T)} > 1\right)\;.$$
Note that $V_2/V_1$ is a martingale when we use $V_1$ as the numeraire
and $V_1/V_2$ is a martingale when we use $V_2$ as the numeraire.
Because they are martingales, they have no drifts. The volatility of the
ratios is given in
[\[margrabesigma\]](#margrabesigma){reference-type="eqref"
reference="margrabesigma"}. Therefore, we have
\begin{align*}
\frac{\D (V_2/V_1)}{V_2/V_1} &= \sigma \,\D B^*_1,\\
\frac{\D (V_1/V_2)}{V_1/V_2} &= \sigma \,\D B^*_2,
\end{align*}
where $B^*_i$ is a Brownian motion when $V_i$ is used as the numeraire.
Margrabe's formula now follows from the tail probability formulas
[\[tailprob01\]](#tailprob01){reference-type="eqref"
reference="tailprob01"}--[\[tailprob02\]](#tailprob02){reference-type="eqref"
reference="tailprob02"}.
\end{petit}

# Problems {#problems .unnumbered}
\begin{prob} Derive the Greeks of a call option on a futures contract.
\end{prob}\begin{prob} Using the results of the previous exercise, show that the delta hedge of a written call on a futures contract that consists of $\E^{-r(T-t)}\N(d_1)$ long futures contracts and the value of the call invested in the risk-free asset is a riskless hedge.
\end{prob}\begin{prob} Derive a formula (like put-call parity) for the value of an option to exchange asset~1 for asset~2 in terms of the value of an option to do the reverse exchange.
\end{prob}\begin{prob} Create a VBA function `Black_Call_ImpliedVol` that uses bisection to
compute an implied forward price volatility from Black's formula and the
market price of a call option on a forward.
\end{prob}\begin{prob} Using a "synthetic forward" argument, derive the forward price for a
forward contract on a stock, where the forward matures at $T'$ and the
stock pays a single known cash dividend $D$ at date $T<T'$.
\end{prob}\begin{prob} Using the result of the previous exercise and Black's formula, derive a formula for the value of a European call option on a stock that pays a single known cash dividend before the option matures.
\end{prob}\begin{prob} Modify the function `Simulated_Delta_Hedge_Profits` to compute the
percentiles of gains and losses for an investor who writes a call option
on a forward contract and uses a discretely-rebalanced delta hedge. As
in Prob. [\[e_forwardhedging\]](#e_forwardhedging){reference-type="ref"
reference="e_forwardhedging"}, you will need to create a variable to
keep track of the net asset/liability from trading forwards and include
it in the valuation at date $T$.
\end{prob}\begin{prob} Consider the portfolio that promises to pay $\bar{X}S(T)$ at date $T$ and replicates the payoff using currency forwards described in Sect.~\ref{s_replicatingquantos}, where $\bar{X}$ is a fixed exchange rate and $S$ is the foreign currency price of an asset.  Using the definition \eqref{changeforwardvalue} of gains and losses from trading forwards, verify that the portfolio is riskless.
\end{prob}\begin{prob} Repeat the previous exercise using the futures hedge described in Sect. \ref{s_hedgingforwards}.
\end{prob}\begin{prob} It has been observed empirically that implied volatilities of stocks are
upward biased estimates of future volatility. Given that there is not
really a constant risk-free rate, implied volatilities should be
interpreted as implied forward-price volatilities, whereas the empirical
literature has measured "future volatility" as the subsequent volatility
of the stock. What assumptions about bond volatilities and the
correlation of bonds and stocks could explain the empirical finding;
i.e., what assumptions imply that the volatility of the forward price
exceeds the volatility of the stock?

\end{prob}\begin{prob} In the continuous-time Ho-Lee model described in
Chap. [\[c_vasicek\]](#c_vasicek){reference-type="ref"
reference="c_vasicek"}, the volatility of a discount bond with time
$\tau$ to maturity is $\sigma_r\tau$ for a constant $\sigma_r$. Under
this assumption, calculate the average volatility of the forward price
of a stock from date 0 to date $T$, where $T$ is the maturity of the
forward contract. Assume the stock has a constant volatility $\sigma_s$
and the correlation between the stock and bond is a constant $\rho$.

\end{prob}\begin{prob} Making the same assumptions as in the previous exercise, and using the
result of that exercise and Merton's formula, write a VBA function to
calculate the value of a call option on a stock. The inputs should be
$S$, $K$, $P$, $\sigma_s$, $\sigma_r$, $\rho$, $q$, and $T$.
\end{prob}
