# Preface {.unnumbered}

This is a partial draft of a python-based introduction to derivative security pricing.  

The github icon directly below the title on the left is a link to a Github repository of Jupyter notebooks.  The notebooks contain all of the code in the book and include "Open in Colab" buttons.  They can also be downloaded directly from the Github repo.

Figures in the text are interactive.  Hover your cursor over plot elements to see additional data.  Also, hover over footnote numbers to see footnotes.

This book is [Hypothesis](https://web.hypothes.is/) enabled.  Click the icons at the top right to log in or sign up and to create annotations or to highlight text.  The annotations and highlights will be visible to you in subsequent visits to the book once you log in to your Hypothesis account.  We prefer that you do not post annotations or highlights to the Public account.

There are some [Streamlit](https://streamlit.io/) applications embedded in the book.  If instead of an application you see a notice that it has "gone to sleep," then click somewhere within it and wait just a bit for it to reload.





