project:
  type: book

book:
  title: "A Course in Derivative Securities"
  author: "Kerry Back"
  date: "8/18/2022"
  chapters:
    - index.qmd
    

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    echo: false



